from .titlebar import QuteTitleBar as QuteTitleBar
from .utils import add_shadow_effect as add_shadow_effect, add_window_animation as add_window_animation, is_window_resizable as is_window_resizable, set_window_non_resizable as set_window_non_resizable
from qtpy.QtCore import QByteArray as QByteArray
from qtpy.QtGui import QShowEvent as QShowEvent
from qtpy.QtWidgets import QWidget

class QuteWindow(QWidget):
    def __init__(self, parent: QWidget | None = None) -> None: ...
    def titleBar(self) -> QWidget: ...
    def setTitleBar(self, titleBar: QWidget) -> None: ...
    def setNonResizable(self) -> None: ...
    def isResizable(self) -> None: ...
    def showEvent(self, event: QShowEvent) -> None: ...
    def nativeEvent(self, event_type: QByteArray, message: int): ...
    def resizeEvent(self, e) -> None: ...
    def setWindowTitle(self, title: str) -> None: ...
    def windowTitle(self) -> str: ...
