/*
 * Generated by asn1c-v0.9.27-1413-ge0c0052e-dirty for Python bindings (https://github.com/MatrixEditor/asn1c-bindings)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <StoreDomainContent-Request_Py.h>

/* class implementation */
PY_IMPL_SEQ_ATTR_FROMPY(StoreDomainContent_Request, domainName, PyAsnIdentifier_FromPython(value, (Identifier_t *)target));
PY_IMPL_SEQ_REF_ATTR_TOPY(StoreDomainContent_Request, domainName, Identifier);
PY_IMPL_SEQ_GETATTR(StoreDomainContent_Request, domainName);
PY_IMPL_SEQ_SETATTR(StoreDomainContent_Request, domainName);
PY_IMPL_SEQ_ATTR_FROMPY(StoreDomainContent_Request, fileName, PyAsnFileName_FromPython(value, (FileName_t *)target));
PY_IMPL_SEQ_REF_ATTR_TOPY(StoreDomainContent_Request, fileName, FileName);
PY_IMPL_SEQ_GETATTR(StoreDomainContent_Request, fileName);
PY_IMPL_SEQ_SETATTR(StoreDomainContent_Request, fileName);
PY_IMPL_SEQ_ATTR_GENERIC_FREE(StoreDomainContent_Request, thirdParty);
PY_IMPL_SEQ_ATTR_GENERIC_NEW(StoreDomainContent_Request, thirdParty, ApplicationReference_t);
PY_IMPL_SEQ_ATTR_INDIRECT_FROMPY(StoreDomainContent_Request, thirdParty, PyAsnApplicationReference_FromPython(value, (ApplicationReference_t *)target));
PY_IMPL_SEQ_REF_ATTR_INDIRECT_TOPY(StoreDomainContent_Request, thirdParty, ApplicationReference);
PY_IMPL_SEQ_OPT_GETATTR(StoreDomainContent_Request, thirdParty);
PY_IMPL_SEQ_OPT_SETATTR(StoreDomainContent_Request, thirdParty);
PY_IMPL_GENERIC_DEALLOC(StoreDomainContent_Request);
PY_IMPL_GENERIC_CHECK_CONSTRAINTS(StoreDomainContent_Request);
PY_IMPL_GENERIC_ENCODE(StoreDomainContent_Request);
PY_IMPL_GENERIC_DECODE(StoreDomainContent_Request);
PY_IMPL_SEQ_GENERIC_TOPY(StoreDomainContent_Request);
PY_IMPL_DECODE_BER(StoreDomainContent_Request);
PY_IMPL_ENCODE_SPECIFIC(StoreDomainContent_Request, ber, ATS_BER);
PY_IMPL_DECODE_DER(StoreDomainContent_Request);
PY_IMPL_ENCODE_SPECIFIC(StoreDomainContent_Request, der, ATS_DER);
PY_IMPL_DECODE_CER(StoreDomainContent_Request);
PY_IMPL_ENCODE_SPECIFIC(StoreDomainContent_Request, cer, ATS_BER);
PY_IMPL_DECODE_XER(StoreDomainContent_Request);
PY_IMPL_ENCODE_XER(StoreDomainContent_Request);
PY_IMPL_ENCODE_SPECIFIC(StoreDomainContent_Request, plain, ATS_NONSTANDARD_PLAINTEXT);
PY_IMPL_DECODE_JER(StoreDomainContent_Request);
PY_IMPL_ENCODE_JER(StoreDomainContent_Request);
PY_IMPL_GENERIC_NEW(StoreDomainContent_Request, &asn_DEF_StoreDomainContent_Request);
PY_IMPL_REPR(StoreDomainContent_Request);
PY_IMPL_GENERIC_IS_VALID(StoreDomainContent_Request);
PY_IMPL_SEQ_FROMPY(StoreDomainContent_Request, &asn_DEF_StoreDomainContent_Request,
	PY_IMPL_SEQ_INIT_ATTR(StoreDomainContent_Request, domainName, domainName);
	PY_IMPL_SEQ_INIT_ATTR(StoreDomainContent_Request, fileName, fileName);
	PY_IMPL_SEQ_INIT_ATTR(StoreDomainContent_Request, thirdParty, thirdParty);
);
PY_IMPL_SEQ_INIT(StoreDomainContent_Request);

/* class attributes definition */
static PyGetSetDef PyAsnStoreDomainContent_Request_getset[] = {
	PY_IMPL_GETSET_ITEM_INTERNAL(StoreDomainContent_Request, domainName, domainName),
	PY_IMPL_GETSET_ITEM_INTERNAL(StoreDomainContent_Request, fileName, fileName),
	PY_IMPL_GETSET_ITEM_INTERNAL(StoreDomainContent_Request, thirdParty, thirdParty),
	{NULL, NULL, NULL, NULL, NULL} /* sentinel */
};

/* class methods definition */
static PyMethodDef PyAsnStoreDomainContent_Request_methods[] = {
	PY_IMPL_METHODDEF_ITEM(StoreDomainContent_Request, is_valid, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(StoreDomainContent_Request, check_constraints, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(StoreDomainContent_Request, ber_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(StoreDomainContent_Request, ber_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(StoreDomainContent_Request, der_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(StoreDomainContent_Request, der_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(StoreDomainContent_Request, cer_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(StoreDomainContent_Request, cer_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(StoreDomainContent_Request, xer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(StoreDomainContent_Request, xer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{"to_text", (PyCFunction)PyAsnStoreDomainContent_Request__plain_encode, (METH_NOARGS), NULL},
	PY_IMPL_METHODDEF_ITEM(StoreDomainContent_Request, jer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(StoreDomainContent_Request, jer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{NULL, NULL, 0, NULL} /* sentinel */
};

/* type definition */
PyTypeObject PyAsnStoreDomainContent_Request_Type = {
	PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "_mms.StoreDomainContent_Request",
	.tp_basicsize = sizeof(PyAsnStoreDomainContent_RequestObject),
	.tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
	.tp_new = (newfunc)PyAsnStoreDomainContent_Request__new,
	.tp_repr = (reprfunc)PyAsnStoreDomainContent_Request__repr,
	.tp_dealloc = (destructor)PyAsnStoreDomainContent_Request__dealloc,
	.tp_init = (initproc)PyAsnStoreDomainContent_Request__init,
	.tp_getset = PyAsnStoreDomainContent_Request_getset,
	.tp_methods = PyAsnStoreDomainContent_Request_methods,
	.tp_doc = "ASN.1 StoreDomainContent_Request type",
};

/* module initializer */
int PyAsnStoreDomainContent_Request_ModSetupTypes(void) {
	if (PyType_Ready(&PyAsnStoreDomainContent_Request_Type) < 0) return -1;
    return 0;
}

void PyAsnStoreDomainContent_Request_ModClear(PyObject *mod) {
}

int PyAsnStoreDomainContent_Request_ModInit(PyObject *mod) {
	PY_IMPL_MOD_ADD_OBJECT(mod, StoreDomainContent_Request);
    return 0;
}

/* end of StoreDomainContent-Request_Py.c */
