from com.terraquantum.project.v1.project import create_project_request_pb2 as _create_project_request_pb2
from com.terraquantum.project.v1.project import get_project_request_pb2 as _get_project_request_pb2
from com.terraquantum.project.v1.project import list_projects_request_pb2 as _list_projects_request_pb2
from com.terraquantum.project.v1.project import list_projects_response_pb2 as _list_projects_response_pb2
from com.terraquantum.project.v1.project import project_pb2 as _project_pb2
from com.terraquantum.project.v1.project import update_project_request_pb2 as _update_project_request_pb2
from com.terraquantum.project.v1.project import list_all_projects_by_organization_id_request_pb2 as _list_all_projects_by_organization_id_request_pb2
from com.terraquantum.project.v1.project import list_organization_member_projects_request_pb2 as _list_organization_member_projects_request_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
