########### custom exceptions dict #############
# warnings are divided by code, then by reason
# every warning has its message that will be returned to print
CUSTOM_EXCEPTIONS = {
    500: {
        "UNDEFINED": "Undefined exception.",
        "USER_KEY_CREATE_ERROR": "Error while creating key.",
        "RESOURCE_SCALE_TEMPLATE_ERROR": "Error while scaling resource - resource not fully compatible with CGC.",
    },
    413: {
        "PVC_CREATE_STORAGE_LIMIT_EXCEEDED": "This request exceeds your storage limits.",
        "PVC_CREATE_NOT_ENOUGH_STORAGE_IN_CLUSTER": "No more storage available.",
        "REQUEST_RESOURCE_LIMIT_EXCEEDED": "This request exceeds your resource limits.",
        "RESOURCES_NOT_AVAILABLE_IN_CLUSTER": "Requested resources are not available.",
        "RESOURCE_SCALE_RESOURCES_LIMIT_EXCEEDED": "This request exceeds your resource limits.",
    },
    409: {
        "PVC_NAME_ALREADY_EXISTS": "A volume with this name already exists.",
        "PVC_DELETE_EXCEPTION": "Can't delete mounted volume. Try with force.",
        "RESOURCE_PORTS_ALREADY_EXISTS": "A port with this name already exists.",
        "RESOURCE_TEMPLATE_NAME_ALREADY_EXISTS": "A resource with this name already exists.",
        "JOB_CREATE_ALREADY_EXISTS": "A job with this name already exists.",
        "USER_KEY_ALREADY_EXISTS": "A key with this data already exists.",
    },
    404: {
        "PVC_CREATE_NO_SC": "Selected disk type and access mode are unavailable.",
        "BILLING_STATUS_NO_DATA": "No data to print.",
        "NOT_DELETED_ANYTHING_IN_COMPUTE_DELETE": "No app with this name to delete.",
        "API_KEY_DELETE_ERROR": "No API key with this ID to delete.",
        "PVC_MOUNT_NOT_FOUND_TEMPLATE": "App resource with this name not found.",
        "PVC_UNMOUNT_NOT_MOUNTED": "Volume with this name is not mounted.",
        "PVC_NOT_FOUND": "Volume with this name not found.",
        "PVC_DELETE_NOT_FOUND": "App with this name not found.",
        "COMPUTE_RESTART_TEMPLATE_NOT_FOUND": "App with this name not found.",
        "COMPUTE_CREATE_TEMPLATE_NOT_FOUND": "There is no template with this name.",
        "COMPUTE_TEMPLATE_NAME_NOT_FOUND": "No app with this name.",
        "COMPUTE_RESOURCE_QUOTA_NOT_FOUND": "You do not have enforced limits on your namespace.",
        "JOB_NOT_FOUND": "Job with this name not found.",
        "RESOURCE_NOT_FOUND": "Resource with this name not found.",
        "USER_KEY_NOT_FOUND": "Key with this ID not found.",
        "RESOURCE_SCALE_TEMPLATE_NOT_FOUND": "No app with this name.",
        "NotFound": "Resource not found.",
        "USER_SECRET_UPDATE_NOT_FOUND": "Secret not found.",
        "USER_SECRET_DELETE_NOT_FOUND": "Secret not found.",
        "PVC_SC_NOT_FOUND": "Storage class with this name is not defined.",
        "RESOURCE_RESTART_TEMPLATE_NOT_FOUND": "Resource with this name not found.",
        "NOT_DELETED_ANYTHING_IN_RESOURCE_DELETE": "There is nothing to delete with this name.",
    },
    400: {
        "WRONG_DATE_FORMAT": "Wrong date format.",
        "ENTITY_NOT_ALLOWED": "You can't create this entity.",
        "PVC_MOUNT_ALREADY_MOUNTED": "This volume is already mounted.",
        "PVC_MOUNT_PATH_ALREADY_EXIST": "This mount path is already being used.",
        "TEMPLATE_NAME_SYSTEM_RESERVED": "You can't create an app with this name.",
        "JOB_LACKS_REQUIRED_PARAMETER": "Job requires a container image parameter.",
        "RESOURCE_PORTS_EXCEPTION": "Resource with this name not found.",
    },
}
