/*
 * Generated by asn1c-v0.9.27-1413-ge0c0052e-dirty for Python bindings (https://github.com/MatrixEditor/asn1c-bindings)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Address_H_
#define	_Address_H_


#include <asn_application.h>

/* Including external dependencies */
#include <Unsigned32.h>
#include <MMSString.h>
#include <OCTET_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Address_PR {
	Address_PR_NOTHING,	/* No components present */
	Address_PR_numericAddress,
	Address_PR_symbolicAddress,
	Address_PR_unconstrainedAddress
} Address_PR;

/* Address */
typedef struct Address {
	Address_PR present;
	union Address_u {
		Unsigned32_t numericAddress;
		MMSString_t symbolicAddress;
		OCTET_STRING_t unconstrainedAddress;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Address_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Address;
extern asn_CHOICE_specifics_t asn_SPC_Address_specs_1;
extern asn_TYPE_member_t asn_MBR_Address_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _Address_H_ */
#include <asn_internal.h>
