from typing import Any, Protocol

from flask_resources import Resource
from invenio_records_resources.resources.errors import ErrorHandlersMixin

class OAIPMHService(Protocol):
    def search(self, identity, params: dict[str, Any] | None = None) -> Any: ...
    def create(self, identity, data: dict[str, Any], /) -> Any: ...
    def read(self, identity, id: int, /) -> Any: ...
    def update(self, identity, id: int, data: dict[str, Any], /) -> Any: ...
    def delete(self, identity, id: int, /) -> None: ...
    def read_all_formats(self, identity, /) -> Any: ...

class OAIPMHServerResource(ErrorHandlersMixin, Resource):
    service: OAIPMHService

    def __init__(self, config, service: OAIPMHService) -> None: ...
    def create_url_rules(self) -> list[dict[str, Any]]: ...
    def search(self) -> tuple[dict[str, Any], int]: ...
    def create(self) -> tuple[dict[str, Any], int]: ...
    def read(self) -> tuple[dict[str, Any], int]: ...
    def update(self) -> tuple[dict[str, Any], int]: ...
    def delete(self) -> tuple[str, int]: ...
    def read_formats(self) -> tuple[dict[str, Any], int]: ...
