from enum import StrEnum


class Break(StrEnum):
    CR = "a"
    """Carriage return"""
    LF = "b"
    """Line feed"""
    Control = "c"
    """Control character"""
    L = "d"
    """Conjoining Jamo - Leading consonant"""
    V = "e"
    """Conjoining Jamo - Vowel"""
    LV = "f"
    """Hangul - precomposed jamo Leading consonant/Vowel sequence"""
    T = "g"
    """Conjoining Jamo - Trailing consonant"""
    LVT = "h"
    """Hangul - precomposed jamo Leading consonant/Vowel/Trailing consonant sequence"""
    Prepend = "i"
    InCB_Consonant = "j"
    Extended_Pictographic = "k"
    Regional_Indicator = "l"
    Other = "m"
    Extend = "n"
    SpacingMark = "o"
    ZWJ = "p"
    """Zero width join"""
    InCB_Linker = "q"
    InCB_Extend = "r"
