import sourcepp._sourcepp_impl.vtfpp


def get_mip_dim(mip: int, dim: int) -> int: ...

def get_recommended_mip_count_for_dims(format: sourcepp._sourcepp_impl.vtfpp.ImageFormat, width: int, height: int) -> int: ...

def get_actual_mip_count_for_dims_on_console(width: int, height: int, depth: int = 1) -> int: ...
