
#                     !!! WARNING !!!
#             This is an auto-generated file!
#                 Generated by [Builder].
# Any manual modifications will be lost upon regeneration.
#             DO NOT EDIT THIS FILE DIRECTLY.

from .chats import Chats, TypeMessagesChats, ChatsSlice
from .bot_app import TypeMessagesBotApp, BotApp
from .dialogs import DialogsNotModified, TypeMessagesDialogs, DialogsSlice, Dialogs
from .web_page import WebPage, TypeMessagesWebPage
from .stickers import Stickers, TypeMessagesStickers, StickersNotModified
from .messages import MessagesSlice, MessagesNotModified, ChannelMessages, TypeMessagesMessages, Messages
from .chat_full import TypeMessagesChatFull, ChatFull
from .dh_config import TypeMessagesDhConfig, DhConfig, DhConfigNotModified
from .reactions import Reactions, ReactionsNotModified, TypeMessagesReactions
from .votes_list import TypeMessagesVotesList, VotesList
from .saved_gifs import TypeMessagesSavedGifs, SavedGifsNotModified, SavedGifs
from .bot_results import BotResults, TypeMessagesBotResults
from .high_scores import TypeMessagesHighScores, HighScores
from .my_stickers import TypeMessagesMyStickers, MyStickers
from .sticker_set import StickerSetNotModified, TypeMessagesStickerSet, StickerSet
from .peer_dialogs import PeerDialogs, TypeMessagesPeerDialogs
from .forum_topics import TypeMessagesForumTopics, ForumTopics
from .all_stickers import AllStickersNotModified, TypeMessagesAllStickers, AllStickers
from .emoji_groups import TypeMessagesEmojiGroups, EmojiGroupsNotModified, EmojiGroups
from .message_views import MessageViews, TypeMessagesMessageViews
from .peer_settings import TypeMessagesPeerSettings, PeerSettings
from .invited_users import TypeMessagesInvitedUsers, InvitedUsers
from .quick_replies import QuickRepliesNotModified, TypeMessagesQuickReplies, QuickReplies
from .saved_dialogs import TypeMessagesSavedDialogs, SavedDialogs, SavedDialogsNotModified, SavedDialogsSlice
from .search_counter import TypeMessagesSearchCounter, SearchCounter
from .inactive_chats import TypeMessagesInactiveChats, InactiveChats
from .history_import import TypeMessagesHistoryImport, HistoryImport
from .dialog_filters import DialogFilters, TypeMessagesDialogFilters
from .faved_stickers import FavedStickersNotModified, TypeMessagesFavedStickers, FavedStickers
from .found_stickers import TypeMessagesFoundStickers, FoundStickersNotModified, FoundStickers
from .translated_text import TypeMessagesTranslatedText, TranslateResult
from .recent_stickers import RecentStickersNotModified, TypeMessagesRecentStickers, RecentStickers
from .affected_history import TypeMessagesAffectedHistory, AffectedHistory
from .web_page_preview import TypeMessagesWebPagePreview, WebPagePreview
from .affected_messages import AffectedMessages, TypeMessagesAffectedMessages
from .message_edit_data import MessageEditData, TypeMessagesMessageEditData
from .archived_stickers import TypeMessagesArchivedStickers, ArchivedStickers
from .transcribed_audio import TranscribedAudio, TypeMessagesTranscribedAudio
from .featured_stickers import TypeMessagesFeaturedStickers, FeaturedStickers, FeaturedStickersNotModified
from .available_effects import AvailableEffectsNotModified, AvailableEffects, TypeMessagesAvailableEffects
from .discussion_message import TypeMessagesDiscussionMessage, DiscussionMessage
from .found_sticker_sets import FoundStickerSetsNotModified, TypeMessagesFoundStickerSets, FoundStickerSets
from .sponsored_messages import TypeMessagesSponsoredMessages, SponsoredMessages, SponsoredMessagesEmpty
from .bot_callback_answer import TypeMessagesBotCallbackAnswer, BotCallbackAnswer
from .available_reactions import AvailableReactions, TypeMessagesAvailableReactions, AvailableReactionsNotModified
from .saved_reaction_tags import TypeMessagesSavedReactionTags, SavedReactionTags, SavedReactionTagsNotModified
from .exported_chat_invite import ExportedChatInvite, ExportedChatInviteReplaced, TypeMessagesExportedChatInvite
from .history_import_parsed import HistoryImportParsed, TypeMessagesHistoryImportParsed
from .exported_chat_invites import ExportedChatInvites, TypeMessagesExportedChatInvites
from .chat_invite_importers import ChatInviteImporters, TypeMessagesChatInviteImporters
from .message_reactions_list import TypeMessagesMessageReactionsList, MessageReactionsList
from .sent_encrypted_message import SentEncryptedMessage, TypeMessagesSentEncryptedMessage, SentEncryptedFile
from .affected_found_messages import TypeMessagesAffectedFoundMessages, AffectedFoundMessages
from .search_results_calendar import SearchResultsCalendar, TypeMessagesSearchResultsCalendar
from .prepared_inline_message import TypeMessagesPreparedInlineMessage, PreparedInlineMessage
from .chat_admins_with_invites import TypeMessagesChatAdminsWithInvites, ChatAdminsWithInvites
from .search_results_positions import TypeMessagesSearchResultsPositions, SearchResultsPositions
from .sticker_set_install_result import StickerSetInstallResultSuccess, TypeMessagesStickerSetInstallResult, StickerSetInstallResultArchive
from .checked_history_import_peer import TypeMessagesCheckedHistoryImportPeer, CheckedHistoryImportPeer
from .bot_prepared_inline_message import TypeMessagesBotPreparedInlineMessage, BotPreparedInlineMessage

__all__ = [
    'TypeMessagesInactiveChats',
    'FeaturedStickersNotModified',
    'MessageViews',
    'TypeMessagesSearchCounter',
    'ExportedChatInvites',
    'VotesList',
    'AffectedHistory',
    'MessageEditData',
    'StickerSet',
    'FoundStickers',
    'TypeMessagesArchivedStickers',
    'ChatFull',
    'SentEncryptedMessage',
    'TypeMessagesMessageReactionsList',
    'TypeMessagesSentEncryptedMessage',
    'TypeMessagesChats',
    'SponsoredMessages',
    'InvitedUsers',
    'TypeMessagesBotPreparedInlineMessage',
    'BotCallbackAnswer',
    'SavedDialogs',
    'HistoryImportParsed',
    'TypeMessagesStickerSet',
    'StickerSetInstallResultSuccess',
    'FavedStickers',
    'TypeMessagesAffectedMessages',
    'Reactions',
    'TypeMessagesAvailableEffects',
    'TypeMessagesFavedStickers',
    'PeerDialogs',
    'RecentStickersNotModified',
    'TypeMessagesDialogs',
    'ReactionsNotModified',
    'FoundStickerSetsNotModified',
    'TypeMessagesSavedDialogs',
    'TypeMessagesBotCallbackAnswer',
    'AvailableReactions',
    'AvailableReactionsNotModified',
    'FeaturedStickers',
    'ExportedChatInviteReplaced',
    'TypeMessagesSearchResultsCalendar',
    'AllStickersNotModified',
    'TypeMessagesChatFull',
    'TypeMessagesQuickReplies',
    'ChatsSlice',
    'RecentStickers',
    'PreparedInlineMessage',
    'TypeMessagesMessages',
    'AffectedFoundMessages',
    'TypeMessagesForumTopics',
    'TypeMessagesBotResults',
    'AvailableEffects',
    'TypeMessagesPeerDialogs',
    'TypeMessagesWebPage',
    'TypeMessagesReactions',
    'SearchCounter',
    'TypeMessagesDialogFilters',
    'FavedStickersNotModified',
    'TypeMessagesRecentStickers',
    'SavedGifsNotModified',
    'TypeMessagesMyStickers',
    'Stickers',
    'DhConfigNotModified',
    'Chats',
    'TypeMessagesFeaturedStickers',
    'TypeMessagesAffectedFoundMessages',
    'SavedDialogsSlice',
    'TypeMessagesVotesList',
    'EmojiGroupsNotModified',
    'QuickReplies',
    'InactiveChats',
    'BotResults',
    'SearchResultsPositions',
    'TypeMessagesBotApp',
    'MessagesNotModified',
    'DiscussionMessage',
    'ChatInviteImporters',
    'Dialogs',
    'DialogFilters',
    'SavedGifs',
    'TypeMessagesInvitedUsers',
    'DialogsNotModified',
    'EmojiGroups',
    'TranscribedAudio',
    'FoundStickerSets',
    'TypeMessagesChatInviteImporters',
    'ForumTopics',
    'TypeMessagesHistoryImport',
    'TypeMessagesFoundStickers',
    'FoundStickersNotModified',
    'CheckedHistoryImportPeer',
    'TypeMessagesSearchResultsPositions',
    'TypeMessagesPeerSettings',
    'PeerSettings',
    'TypeMessagesCheckedHistoryImportPeer',
    'DialogsSlice',
    'AvailableEffectsNotModified',
    'ChannelMessages',
    'TypeMessagesExportedChatInvites',
    'TypeMessagesFoundStickerSets',
    'TypeMessagesTranscribedAudio',
    'TypeMessagesAffectedHistory',
    'SentEncryptedFile',
    'TypeMessagesWebPagePreview',
    'DhConfig',
    'TypeMessagesMessageViews',
    'TypeMessagesHistoryImportParsed',
    'MessageReactionsList',
    'TypeMessagesPreparedInlineMessage',
    'MessagesSlice',
    'TypeMessagesAllStickers',
    'TranslateResult',
    'TypeMessagesExportedChatInvite',
    'ArchivedStickers',
    'WebPage',
    'ExportedChatInvite',
    'TypeMessagesAvailableReactions',
    'TypeMessagesMessageEditData',
    'BotPreparedInlineMessage',
    'HistoryImport',
    'TypeMessagesChatAdminsWithInvites',
    'MyStickers',
    'HighScores',
    'SavedReactionTags',
    'TypeMessagesDhConfig',
    'SavedDialogsNotModified',
    'StickerSetNotModified',
    'Messages',
    'SponsoredMessagesEmpty',
    'TypeMessagesEmojiGroups',
    'AllStickers',
    'AffectedMessages',
    'TypeMessagesSavedReactionTags',
    'SearchResultsCalendar',
    'TypeMessagesStickerSetInstallResult',
    'TypeMessagesSponsoredMessages',
    'StickerSetInstallResultArchive',
    'TypeMessagesStickers',
    'TypeMessagesTranslatedText',
    'ChatAdminsWithInvites',
    'SavedReactionTagsNotModified',
    'TypeMessagesSavedGifs',
    'BotApp',
    'TypeMessagesDiscussionMessage',
    'QuickRepliesNotModified',
    'WebPagePreview',
    'TypeMessagesHighScores',
    'StickersNotModified'
]