/*
 * Generated by asn1c-v0.9.27-1413-ge0c0052e-dirty for Python bindings (https://github.com/MatrixEditor/asn1c-bindings)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <Conclude-RequestPDU_Py.h>

/* class implementation */
PY_IMPL_GENERIC_NEW(Conclude_RequestPDU, NULL);
PY_IMPL_GENERIC_INIT(Conclude_RequestPDU);
PY_IMPL_GENERIC_DEALLOC(Conclude_RequestPDU);
PY_IMPL_REPR(Conclude_RequestPDU);
PY_IMPL_GENERIC_STR(Conclude_RequestPDU);
PY_IMPL_GENERIC_CHECK_CONSTRAINTS(Conclude_RequestPDU);
PY_IMPL_GENERIC_IS_VALID(Conclude_RequestPDU);
PY_IMPL_GENERIC_ENCODE(Conclude_RequestPDU);
PY_IMPL_GENERIC_DECODE(Conclude_RequestPDU);
PY_IMPL_DECODE_BER(Conclude_RequestPDU);
PY_IMPL_ENCODE_SPECIFIC(Conclude_RequestPDU, ber, ATS_BER);
PY_IMPL_DECODE_DER(Conclude_RequestPDU);
PY_IMPL_ENCODE_SPECIFIC(Conclude_RequestPDU, der, ATS_DER);
PY_IMPL_DECODE_CER(Conclude_RequestPDU);
PY_IMPL_ENCODE_SPECIFIC(Conclude_RequestPDU, cer, ATS_BER);
PY_IMPL_DECODE_XER(Conclude_RequestPDU);
PY_IMPL_ENCODE_XER(Conclude_RequestPDU);
PY_IMPL_ENCODE_SPECIFIC(Conclude_RequestPDU, plain, ATS_NONSTANDARD_PLAINTEXT);
PY_IMPL_DECODE_JER(Conclude_RequestPDU);
PY_IMPL_ENCODE_JER(Conclude_RequestPDU);
PY_IMPL_MEMBER_GETSET(Conclude_RequestPDU, value, Conclude_RequestPDU, self->ob_value);

/* class attributes definition */
static PyGetSetDef PyAsnConclude_RequestPDU_getset[] = {
	PY_IMPL_GETSET_ITEM(Conclude_RequestPDU, value),
	{NULL, NULL, NULL, NULL, NULL} /* sentinel */
};

/* class methods definition */
static PyMethodDef PyAsnConclude_RequestPDU_methods[] = {
	PY_IMPL_METHODDEF_ITEM(Conclude_RequestPDU, is_valid, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Conclude_RequestPDU, check_constraints, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Conclude_RequestPDU, ber_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Conclude_RequestPDU, ber_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(Conclude_RequestPDU, der_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Conclude_RequestPDU, der_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(Conclude_RequestPDU, cer_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Conclude_RequestPDU, cer_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(Conclude_RequestPDU, xer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(Conclude_RequestPDU, xer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{"to_text", (PyCFunction)PyAsnConclude_RequestPDU__plain_encode, (METH_NOARGS), NULL},
	PY_IMPL_METHODDEF_ITEM(Conclude_RequestPDU, jer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(Conclude_RequestPDU, jer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{NULL, NULL, 0, NULL} /* sentinel */
};

/* type definition */
PyTypeObject PyAsnConclude_RequestPDU_Type = {
	PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "_mms.Conclude_RequestPDU",
	.tp_basicsize = sizeof(PyAsnConclude_RequestPDUObject),
	.tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
	.tp_new = (newfunc)PyAsnConclude_RequestPDU__new,
	.tp_repr = (reprfunc)PyAsnConclude_RequestPDU__repr,
	.tp_dealloc = (destructor)PyAsnConclude_RequestPDU__dealloc,
	.tp_init = (initproc)PyAsnConclude_RequestPDU__init,
	.tp_getset = PyAsnConclude_RequestPDU_getset,
	.tp_methods = PyAsnConclude_RequestPDU_methods,
	.tp_doc = "ASN.1 Conclude_RequestPDU type",
	.tp_str = (reprfunc)PyAsnConclude_RequestPDU__str,
};

/* module initializer */
int PyAsnConclude_RequestPDU_ModSetupTypes(void) {
	if (PyType_Ready(&PyAsnConclude_RequestPDU_Type) < 0) return -1;
    return 0;
}

void PyAsnConclude_RequestPDU_ModClear(PyObject *mod) {
}

int PyAsnConclude_RequestPDU_ModInit(PyObject *mod) {
	PY_IMPL_MOD_ADD_OBJECT(mod, Conclude_RequestPDU);
    return 0;
}

/* end of Conclude-RequestPDU_Py.c */
