from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext
ext_modules = [
    Extension("mc_promo", ["mc_promo.py"], extra_compile_args=["-g0"]),
    Extension("db", ["db.py"], extra_compile_args=["-g0"]),
    Extension("exception_log", ["exception_log.py"], extra_compile_args=["-g0"]),
    Extension("instance_data", ["instance_data.py"], extra_compile_args=["-g0"]),
    Extension("order_cycles", ["order_cycles.py"], extra_compile_args=["-g0"]),
    Extension("offers", ["offers.py"], extra_compile_args=["-g0"]),
    Extension("offer_globals", ["offer_globals.py"], extra_compile_args=["-g0"]),
    Extension("logga", ["logga.py"], extra_compile_args=["-g0"]),
    Extension("campaigns", ["campaigns.py"], extra_compile_args=["-g0"]),
    Extension("gateways", ["gateways.py"], extra_compile_args=["-g0"]),
    Extension("orders", ["orders.py"], extra_compile_args=["-g0"]),
    Extension("processor_settings", ["processor_settings.py"], extra_compile_args=["-g0"]),
    Extension("order_processing", ["order_processing.py"], extra_compile_args=["-g0"]),
    Extension("clients", ["clients.py"], extra_compile_args=["-g0"]),
    Extension("corps", ["corps.py"], extra_compile_args=["-g0"]),
    Extension("mids", ["mids.py"], extra_compile_args=["-g0"]),
    Extension("invoices", ["invoices.py"], extra_compile_args=["-g0"]),
    Extension("iso", ["iso.py"], extra_compile_args=["-g0"]),
    Extension("processors", ["processors.py"], extra_compile_args=["-g0"]),

    Extension("transactions", ["transactions.py"], extra_compile_args=["-g0"]),
    Extension("banks", ["banks.py"], extra_compile_args=["-g0"]),
    Extension("gateway_providers", ["gateway_providers.py"], extra_compile_args=["-g0"]),
    Extension("instance_data", ["instance_data.py"], extra_compile_args=["-g0"]),
    Extension("users", ["users.py"], extra_compile_args=["-g0"]),
    Extension("billing_models", ["billing_models.py"], extra_compile_args=["-g0"]),
    Extension("pixels", ["pixels.py"], extra_compile_args=["-g0"]),
    Extension("filter_index", ["filter_index.py"], extra_compile_args=["-g0"]),
    Extension("processor", ["processor.py"], extra_compile_args=["-g0"]),
    Extension("providers", ["providers.py"], extra_compile_args=["-g0"]),
    Extension("alert_providers", ["alert_providers.py"], extra_compile_args=["-g0"]),
    Extension("color_index", ["color_index.py"], extra_compile_args=["-g0"]),
    Extension("corp_cascade", ["corp_cascade.py"], extra_compile_args=["-g0"]),
    Extension("hard_declines", ["hard_declines.py"], extra_compile_args=["-g0"]),
    Extension("approval_rate", ["approval_rate.py"], extra_compile_args=["-g0"]),
    Extension("processing_error_log", ["processing_error_log.py"], extra_compile_args=["-g0"]),
    Extension("crm_errors", ["crm_errors.py"], extra_compile_args=["-g0"]),
    Extension("revenue", ["revenue.py"], extra_compile_args=["-g0"]),
    Extension("initials", ["initials.py"], extra_compile_args=["-g0"]),
    Extension("test_customers", ["test_customers.py"], extra_compile_args=["-g0"]),
    Extension("master_campaigns", ["master_campaigns.py"], extra_compile_args=["-g0"]),
    Extension("campaign_balancer", ["campaign_balancer.py"], extra_compile_args=["-g0"]),
    #Extension("internal_orders", ["internal_orders.py"], extra_compile_args=["-g0"]),
    Extension("discount_stats", ["discount_stats.py"], extra_compile_args=["-g0"]),
    Extension("bins", ["bins.py"], extra_compile_args=["-g0"]),
    Extension("products", ["products.py"], extra_compile_args=["-g0"]),
    Extension("corps", ["corps.py"], extra_compile_args=["-g0"]),
    Extension("email_reconfs", ["email_reconfs.py"], extra_compile_args=["-g0"]),
    Extension("prospects", ["prospects.py"], extra_compile_args=["-g0"]),
    Extension("order_actions", ["order_actions.py"], extra_compile_args=["-g0"]),
    Extension("prices", ["prices.py"], extra_compile_args=["-g0"]),
    Extension("rb_set", ["rb_set.py"], extra_compile_args=["-g0"]),
    Extension("discounter", ["discounter.py"], extra_compile_args=["-g0"]),
    Extension("capfill", ["capfill.py"], extra_compile_args=["-g0"]),
    Extension("partitioner", ["partitioner.py"], extra_compile_args=["-g0"]),
    Extension("custom_shipping", ["custom_shipping.py"], extra_compile_args=["-g0"]),

    #Extension("decline_resets", ["decline_resets.py"], extra_compile_args=["-g0"]),

]
setup(
    name='models',
    cmdclass={'build_ext': build_ext},
    ext_modules=ext_modules
)