
#                     !!! WARNING !!!
#             This is an auto-generated file!
#                 Generated by [Builder].
# Any manual modifications will be lost upon regeneration.
#             DO NOT EDIT THIS FILE DIRECTLY.

from typing import List
from ....gadgets.tlobject import TLRequest
from ...types.secure_value import TypeSecureValue


class GetAllSecureValues(TLRequest[List[TypeSecureValue]]):
    """
    Get all saved [Telegram Passport](https://core.telegram.org/passport) documents, [for more info see the passport docs](https://core.telegram.org/passport/encryption#encryption)
    """

    _id = 0XB288BC7D


    def to_bytes(self, boxed: bool=True):
        return b'}\xbc\x88\xb2' if boxed else b''