from typing import Any

class Prompt:
    template: str
    def __init__(self, template: str) -> None: ...
    def format(self, **data: Any) -> str: ...
    @property
    def input_variables(self) -> list[str]: ...
    def __str__(self) -> str: ...

class PromptManager:
    prompt_module: Any
    def __init__(self, model_module: str) -> None: ...
    @property
    def system_prompt(self) -> Prompt: ...
    def user_prompt(self, i: int | None = None) -> Prompt: ...
