/*
 * Generated by asn1c-v0.9.27-1413-ge0c0052e-dirty for Python bindings (https://github.com/MatrixEditor/asn1c-bindings)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AlterEventConditionMonitoring_Response_H_
#define	_AlterEventConditionMonitoring_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AlterEventConditionMonitoring-Response */
typedef NULL_t  AlterEventConditionMonitoring_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlterEventConditionMonitoring_Response;
asn_struct_free_f AlterEventConditionMonitoring_Response_free;
asn_struct_print_f AlterEventConditionMonitoring_Response_print;
asn_constr_check_f AlterEventConditionMonitoring_Response_constraint;
ber_type_decoder_f AlterEventConditionMonitoring_Response_decode_ber;
der_type_encoder_f AlterEventConditionMonitoring_Response_encode_der;
xer_type_decoder_f AlterEventConditionMonitoring_Response_decode_xer;
xer_type_encoder_f AlterEventConditionMonitoring_Response_encode_xer;
jer_type_encoder_f AlterEventConditionMonitoring_Response_encode_jer;

#ifdef __cplusplus
}
#endif

#endif	/* _AlterEventConditionMonitoring_Response_H_ */
#include <asn_internal.h>
