
#                     !!! WARNING !!!
#             This is an auto-generated file!
#                 Generated by [Builder].
# Any manual modifications will be lost upon regeneration.
#             DO NOT EDIT THIS FILE DIRECTLY.

from typing import TYPE_CHECKING
from ...gadgets.tlobject import TLObject
from ...gadgets.byteutils import Writer


if TYPE_CHECKING:
    from .dialog_filter import TypeDialogFilter
    from ...gadgets.byteutils import Reader


class DialogFilterSuggested(TLObject, family='TypeDialogFilterSuggested'):
    """
    Suggested [folders](https://core.telegram.org/api/folders)
    """

    _id = 0X77744D4A
    _group_id = 0X7AED2AA5

    def __init__(
        self,
        filter: 'TypeDialogFilter',
        description: str
    ):

        """
        Suggested [folders](https://core.telegram.org/api/folders)

        Args:
            filter ('TypeDialogFilter'): [Folder info](https://core.telegram.org/api/folders)
            description (str): [Folder](https://core.telegram.org/api/folders) description
        """

        self.filter = filter
        self.description = description

    def to_bytes(self, boxed: bool=True):
        with Writer(b'JMtw' if boxed else b'') as writer:
            writer.object(
                self.filter,
                group_id=0X6BB0DA45
            )
            writer.string(self.description)

            return writer.getvalue()

    @classmethod
    def from_reader(cls, reader: 'Reader'):
        filter_ = reader.object(
            group_id=0X6BB0DA45
        )

        description_ = reader.string()

        return cls(
            filter=filter_,
            description=description_
        )

TypeDialogFilterSuggested = DialogFilterSuggested