
#                     !!! WARNING !!!
#             This is an auto-generated file!
#                 Generated by [Builder].
# Any manual modifications will be lost upon regeneration.
#             DO NOT EDIT THIS FILE DIRECTLY.

from typing import TYPE_CHECKING
from ...gadgets.tlobject import TLObject
from ...gadgets.byteutils import Writer


if TYPE_CHECKING:
    from ...gadgets.byteutils import Reader


class StatsPercentValue(TLObject, family='TypeStatsPercentValue'):
    """
    [Channel statistics percentage](https://core.telegram.org/api/stats). 
    Compute the percentage simply by doing part * total / 100
    """

    _id = 0XCBCE2FE0
    _group_id = 0XFE9414C3

    def __init__(
        self,
        part: float,
        total: float
    ):

        """
        [Channel statistics percentage](https://core.telegram.org/api/stats). 
        Compute the percentage simply by doing part * total / 100

        Args:
            part (float): Partial value
            total (float): Total value
        """

        self.part = part
        self.total = total

    def to_bytes(self, boxed: bool=True):
        with Writer(b'\xe0/\xce\xcb' if boxed else b'') as writer:
            writer.double(self.part)
            writer.double(self.total)

            return writer.getvalue()

    @classmethod
    def from_reader(cls, reader: 'Reader'):
        part_ = reader.double()
        total_ = reader.double()

        return cls(
            part=part_,
            total=total_
        )

TypeStatsPercentValue = StatsPercentValue