#include "py_module.h"

/* Module Cleanup */
PY_IMPL_MODULE_CLEAR(_iso8823,
	PyAsnCP_type_ModClear(m);
	PyAsnCPC_type_ModClear(m);
	PyAsnCPA_PPDU_ModClear(m);
	PyAsnCPR_PPDU_ModClear(m);
	PyAsnAbort_type_ModClear(m);
	PyAsnARU_PPDU_ModClear(m);
	PyAsnARP_PPDU_ModClear(m);
	PyAsnTyped_data_type_ModClear(m);
	PyAsnAC_PPDU_ModClear(m);
	PyAsnACA_PPDU_ModClear(m);
	PyAsnRS_PPDU_ModClear(m);
	PyAsnRSA_PPDU_ModClear(m);
	PyAsnAbort_reason_ModClear(m);
	PyAsnAbstract_syntax_name_ModClear(m);
	PyAsnCalled_presentation_selector_ModClear(m);
	PyAsnCalling_presentation_selector_ModClear(m);
	PyAsnContext_list_ModClear(m);
	PyAsnDefault_context_name_ModClear(m);
	PyAsnDefault_context_result_ModClear(m);
	PyAsnEvent_identifier_ModClear(m);
	PyAsnMode_selector_ModClear(m);
	PyAsnPresentation_context_addition_list_ModClear(m);
	PyAsnPresentation_context_addition_result_list_ModClear(m);
	PyAsnPresentation_context_definition_list_ModClear(m);
	PyAsnPresentation_context_definition_result_list_ModClear(m);
	PyAsnPresentation_context_deletion_list_ModClear(m);
	PyAsnPresentation_context_deletion_result_list_ModClear(m);
	PyAsnPresentation_context_identifier_ModClear(m);
	PyAsnPresentation_context_identifier_list_ModClear(m);
	PyAsnPresentation_requirements_ModClear(m);
	PyAsnPresentation_selector_ModClear(m);
	PyAsnProtocol_options_ModClear(m);
	PyAsnProtocol_version_ModClear(m);
	PyAsnProvider_reason_ModClear(m);
	PyAsnResponding_presentation_selector_ModClear(m);
	PyAsnResult_ModClear(m);
	PyAsnResult_list_ModClear(m);
	PyAsnTransfer_syntax_name_ModClear(m);
	PyAsnUser_data_ModClear(m);
	PyAsnSimply_encoded_data_ModClear(m);
	PyAsnFully_encoded_data_ModClear(m);
	PyAsnPDV_list_ModClear(m);
	PyAsnUser_session_requirements_ModClear(m);
	PyAsnEXTERNAL_ModClear(m);
	PyCompat_Clear();
);

/* Module Type */
PY_IMPL_MODULE_DEF(_iso8823);

/* Module Init */
PY_IMPL_MODULE_INIT_BEGIN(_iso8823)
	if (PyAsnCP_type_ModSetupTypes() < 0) return NULL;
	if (PyAsnCPC_type_ModSetupTypes() < 0) return NULL;
	if (PyAsnCPA_PPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnCPR_PPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnAbort_type_ModSetupTypes() < 0) return NULL;
	if (PyAsnARU_PPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnARP_PPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnTyped_data_type_ModSetupTypes() < 0) return NULL;
	if (PyAsnAC_PPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnACA_PPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnRS_PPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnRSA_PPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnAbort_reason_ModSetupTypes() < 0) return NULL;
	if (PyAsnAbstract_syntax_name_ModSetupTypes() < 0) return NULL;
	if (PyAsnCalled_presentation_selector_ModSetupTypes() < 0) return NULL;
	if (PyAsnCalling_presentation_selector_ModSetupTypes() < 0) return NULL;
	if (PyAsnContext_list_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefault_context_name_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefault_context_result_ModSetupTypes() < 0) return NULL;
	if (PyAsnEvent_identifier_ModSetupTypes() < 0) return NULL;
	if (PyAsnMode_selector_ModSetupTypes() < 0) return NULL;
	if (PyAsnPresentation_context_addition_list_ModSetupTypes() < 0) return NULL;
	if (PyAsnPresentation_context_addition_result_list_ModSetupTypes() < 0) return NULL;
	if (PyAsnPresentation_context_definition_list_ModSetupTypes() < 0) return NULL;
	if (PyAsnPresentation_context_definition_result_list_ModSetupTypes() < 0) return NULL;
	if (PyAsnPresentation_context_deletion_list_ModSetupTypes() < 0) return NULL;
	if (PyAsnPresentation_context_deletion_result_list_ModSetupTypes() < 0) return NULL;
	if (PyAsnPresentation_context_identifier_ModSetupTypes() < 0) return NULL;
	if (PyAsnPresentation_context_identifier_list_ModSetupTypes() < 0) return NULL;
	if (PyAsnPresentation_requirements_ModSetupTypes() < 0) return NULL;
	if (PyAsnPresentation_selector_ModSetupTypes() < 0) return NULL;
	if (PyAsnProtocol_options_ModSetupTypes() < 0) return NULL;
	if (PyAsnProtocol_version_ModSetupTypes() < 0) return NULL;
	if (PyAsnProvider_reason_ModSetupTypes() < 0) return NULL;
	if (PyAsnResponding_presentation_selector_ModSetupTypes() < 0) return NULL;
	if (PyAsnResult_ModSetupTypes() < 0) return NULL;
	if (PyAsnResult_list_ModSetupTypes() < 0) return NULL;
	if (PyAsnTransfer_syntax_name_ModSetupTypes() < 0) return NULL;
	if (PyAsnUser_data_ModSetupTypes() < 0) return NULL;
	if (PyAsnSimply_encoded_data_ModSetupTypes() < 0) return NULL;
	if (PyAsnFully_encoded_data_ModSetupTypes() < 0) return NULL;
	if (PyAsnPDV_list_ModSetupTypes() < 0) return NULL;
	if (PyAsnUser_session_requirements_ModSetupTypes() < 0) return NULL;
	if (PyAsnEXTERNAL_ModSetupTypes() < 0) return NULL;

	if((nModule = PyModule_Create(&PyAsnModule__iso8823)) == NULL) { return NULL; }

	if (PyCompat_Init() < 0) return NULL;
	if (PyAsnCP_type_ModInit(nModule) < 0) return NULL;
	if (PyAsnCPC_type_ModInit(nModule) < 0) return NULL;
	if (PyAsnCPA_PPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnCPR_PPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnAbort_type_ModInit(nModule) < 0) return NULL;
	if (PyAsnARU_PPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnARP_PPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnTyped_data_type_ModInit(nModule) < 0) return NULL;
	if (PyAsnAC_PPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnACA_PPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnRS_PPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnRSA_PPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnAbort_reason_ModInit(nModule) < 0) return NULL;
	if (PyAsnAbstract_syntax_name_ModInit(nModule) < 0) return NULL;
	if (PyAsnCalled_presentation_selector_ModInit(nModule) < 0) return NULL;
	if (PyAsnCalling_presentation_selector_ModInit(nModule) < 0) return NULL;
	if (PyAsnContext_list_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefault_context_name_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefault_context_result_ModInit(nModule) < 0) return NULL;
	if (PyAsnEvent_identifier_ModInit(nModule) < 0) return NULL;
	if (PyAsnMode_selector_ModInit(nModule) < 0) return NULL;
	if (PyAsnPresentation_context_addition_list_ModInit(nModule) < 0) return NULL;
	if (PyAsnPresentation_context_addition_result_list_ModInit(nModule) < 0) return NULL;
	if (PyAsnPresentation_context_definition_list_ModInit(nModule) < 0) return NULL;
	if (PyAsnPresentation_context_definition_result_list_ModInit(nModule) < 0) return NULL;
	if (PyAsnPresentation_context_deletion_list_ModInit(nModule) < 0) return NULL;
	if (PyAsnPresentation_context_deletion_result_list_ModInit(nModule) < 0) return NULL;
	if (PyAsnPresentation_context_identifier_ModInit(nModule) < 0) return NULL;
	if (PyAsnPresentation_context_identifier_list_ModInit(nModule) < 0) return NULL;
	if (PyAsnPresentation_requirements_ModInit(nModule) < 0) return NULL;
	if (PyAsnPresentation_selector_ModInit(nModule) < 0) return NULL;
	if (PyAsnProtocol_options_ModInit(nModule) < 0) return NULL;
	if (PyAsnProtocol_version_ModInit(nModule) < 0) return NULL;
	if (PyAsnProvider_reason_ModInit(nModule) < 0) return NULL;
	if (PyAsnResponding_presentation_selector_ModInit(nModule) < 0) return NULL;
	if (PyAsnResult_ModInit(nModule) < 0) return NULL;
	if (PyAsnResult_list_ModInit(nModule) < 0) return NULL;
	if (PyAsnTransfer_syntax_name_ModInit(nModule) < 0) return NULL;
	if (PyAsnUser_data_ModInit(nModule) < 0) return NULL;
	if (PyAsnSimply_encoded_data_ModInit(nModule) < 0) return NULL;
	if (PyAsnFully_encoded_data_ModInit(nModule) < 0) return NULL;
	if (PyAsnPDV_list_ModInit(nModule) < 0) return NULL;
	if (PyAsnUser_session_requirements_ModInit(nModule) < 0) return NULL;
	if (PyAsnEXTERNAL_ModInit(nModule) < 0) return NULL;
PY_IMPL_MODULE_INIT_END;
