{
    "name": "HR Assistance - SomConnexio",
    "version": "16.0.1.0.1",
    "summary": "Manage human resources processes in Som Connexió.",
    "author": "Som Connexió SCCL, Coopdevs Treball SCCL",
    "website": "https://git.coopdevs.org/coopdevs/som-connexio/odoo/odoo-somconnexio",
    "license": "AGPL-3",
    "category": "Cooperative Management",
    "depends": [
        "hr_contract",
        "hr_holidays",
        "hr_holidays_leave_auto_approve",
        "hr_holidays_public",
        "hr_timesheet",
        "hr_attendance_report_theoretical_time",
        "somconnexio",
        "calendar",
    ],
    "data": [
        "views/hr_attendance.xml",
        "views/menus.xml",
        "views/calendar_view.xml",
        "data/hr_attendance_place.xml",
        "data/ir_config_parameter.xml",
        "security/ir.model.access.csv",
    ],
    "demo": [],
    "external_dependencies": {},
    "application": False,
    "installable": True,
}
