from minjiang_client.qc.hamiltonian import Hamiltonian as Hamiltonian
from minjiang_client.waveform import WavePackage as WavePackage

def solve(ham: Hamiltonian, wave_cache: dict, wave_package: WavePackage, state0=None, shots=None, evolution: bool = False, output_energy_level: int = 2): ...
def solve_unitary(ham: Hamiltonian, wave_cache: dict, wave_package: WavePackage, state0=None, shots=None, evolution: bool = False, output_energy_level: int = 2): ...
