from com.terraquantum.role.v2.role import check_permissions_request_pb2 as _check_permissions_request_pb2
from com.terraquantum.role.v2.role import check_permissions_response_pb2 as _check_permissions_response_pb2
from com.terraquantum.role.v2.role import get_organization_member_role_request_pb2 as _get_organization_member_role_request_pb2
from com.terraquantum.role.v1.role import organization_member_role_pb2 as _organization_member_role_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
