from .utils import is_window_resizable as is_window_resizable, start_system_move as start_system_move
from _typeshed import Incomplete
from qtpy.QtGui import QMouseEvent as QMouseEvent
from qtpy.QtWidgets import QFrame, QWidget as QWidget

class QuteTitleBar(QFrame):
    label: Incomplete
    def __init__(self, parent: QWidget | None = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self): ...
    def mouseMoveEvent(self, event: QMouseEvent) -> None: ...
    def mouseDoubleClickEvent(self, event: QMouseEvent) -> None: ...
