from AppKit import NSWindow as NSWindow
from qtpy.QtCore import QPoint
from qtpy.QtWidgets import QWidget as QWidget

def merge_content_area_and_title_bar(win_id: int) -> None: ...
def hide_traffic_lights(win_id: int) -> None: ...
def set_traffic_lights_position(win_id: int, pos=...) -> None: ...
def set_window_non_resizable(win_id: int) -> None: ...
def start_system_move(widget: QWidget, pos: QPoint): ...
def is_window_resizable(hwnd): ...
