from robot.api.deco import keyword
from robot.libraries.BuiltIn import BuiltIn
from SikuliLibrary import SikuliLibrary


class MouseMixin:
    def __init__(self) -> None:
        self.robot: BuiltIn
        self.sikuli: SikuliLibrary

    def click(self, image: str, xOffset: int = 0, yOffset: int = 0): ...
    def double_click(self, image: str, xOffset: int = 0, yOffset: int = 0): ...
    def right_click(self, image: str, xOffset: int = 0, yOffset: int = 0): ...
    def middle_click(self, image: str, xOffset: int = 0, yOffset: int = 0): ...

    def scroll_down(self, steps: int): ...
    def scroll_up(self, steps: int): ...

    def move_mouse(self, image: str, xOffset: int = 0, yOffset: int = 0): ...
    def hold_mouse_button(self, *buttons: str): ...
    def release_mouse_button(self, *buttons: str): ...  # Verificar sem nenhum botão

    def drag_and_drop_to_image(self, image: str, destiny_image: str): ...
    def drag_and_drop(self, image: str, xOffset: int = 0, yOffset: int = 0): ...
