from com.terraquantum.role.v2.policy import list_organization_user_policies_request_pb2 as _list_organization_user_policies_request_pb2
from com.terraquantum.role.v2.policy import list_organization_user_policies_response_pb2 as _list_organization_user_policies_response_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
