from io import BytesIO
import tg_secret.raw

# # # # # # # # # # # # # # # # # # # # # # # #
#               !!! WARNING !!!               #
#          This is a generated file!          #
# All changes made in this file will be lost! #
# # # # # # # # # # # # # # # # # # # # # # # #

layer = 144

objects = {
    0x1f814f1f: tg_secret.raw.types.DecryptedMessage_8,
    0xaa48327d: tg_secret.raw.types.DecryptedMessageService_8,
    0x89f5c4a: tg_secret.raw.types.DecryptedMessageMediaEmpty,
    0x32798a8c: tg_secret.raw.types.DecryptedMessageMediaPhoto_8,
    0x4cee6ef3: tg_secret.raw.types.DecryptedMessageMediaVideo_8,
    0x35480a59: tg_secret.raw.types.DecryptedMessageMediaGeoPoint,
    0x588a0a97: tg_secret.raw.types.DecryptedMessageMediaContact,
    0xa1733aec: tg_secret.raw.types.DecryptedMessageActionSetMessageTTL,
    0xb095434b: tg_secret.raw.types.DecryptedMessageMediaDocument_8,
    0x6080758f: tg_secret.raw.types.DecryptedMessageMediaAudio_8,
    0xc4f40be: tg_secret.raw.types.DecryptedMessageActionReadMessages,
    0x65614304: tg_secret.raw.types.DecryptedMessageActionDeleteMessages,
    0x8ac1f475: tg_secret.raw.types.DecryptedMessageActionScreenshotMessages,
    0x6719e45c: tg_secret.raw.types.DecryptedMessageActionFlushHistory,
    0x204d3878: tg_secret.raw.types.DecryptedMessage_17,
    0x73164160: tg_secret.raw.types.DecryptedMessageService_17,
    0x524a415d: tg_secret.raw.types.DecryptedMessageMediaVideo_17,
    0x57e0a9cb: tg_secret.raw.types.DecryptedMessageMediaAudio_17,
    0x1be31789: tg_secret.raw.types.DecryptedMessageLayer,
    0x16bf744e: tg_secret.raw.types.SendMessageTypingAction,
    0xfd5ec8f5: tg_secret.raw.types.SendMessageCancelAction,
    0xa187d66f: tg_secret.raw.types.SendMessageRecordVideoAction,
    0x92042ff7: tg_secret.raw.types.SendMessageUploadVideoAction,
    0xd52f73f7: tg_secret.raw.types.SendMessageRecordAudioAction,
    0xe6ac8a6f: tg_secret.raw.types.SendMessageUploadAudioAction,
    0x990a3c1a: tg_secret.raw.types.SendMessageUploadPhotoAction,
    0x8faee98e: tg_secret.raw.types.SendMessageUploadDocumentAction,
    0x176f8ba1: tg_secret.raw.types.SendMessageGeoLocationAction,
    0x628cbc6f: tg_secret.raw.types.SendMessageChooseContactAction,
    0x511110b0: tg_secret.raw.types.DecryptedMessageActionResend,
    0xf3048883: tg_secret.raw.types.DecryptedMessageActionNotifyLayer,
    0xccb27641: tg_secret.raw.types.DecryptedMessageActionTyping,
    0xf3c9611b: tg_secret.raw.types.DecryptedMessageActionRequestKey,
    0x6fe1735b: tg_secret.raw.types.DecryptedMessageActionAcceptKey,
    0xdd05ec6b: tg_secret.raw.types.DecryptedMessageActionAbortKey,
    0xec2e0b9b: tg_secret.raw.types.DecryptedMessageActionCommitKey,
    0xa82fdd63: tg_secret.raw.types.DecryptedMessageActionNoop,
    0x6c37c15c: tg_secret.raw.types.DocumentAttributeImageSize,
    0x11b58939: tg_secret.raw.types.DocumentAttributeAnimated,
    0xfb0a5727: tg_secret.raw.types.DocumentAttributeSticker_23,
    0x5910cccb: tg_secret.raw.types.DocumentAttributeVideo_23,
    0x51448e5: tg_secret.raw.types.DocumentAttributeAudio_23,
    0x15590068: tg_secret.raw.types.DocumentAttributeFilename,
    0xe17e23c: tg_secret.raw.types.PhotoSizeEmpty,
    0x77bfb61b: tg_secret.raw.types.PhotoSize,
    0xe9a734fa: tg_secret.raw.types.PhotoCachedSize,
    0x7c596b46: tg_secret.raw.types.FileLocationUnavailable,
    0x53d69076: tg_secret.raw.types.FileLocation,
    0xfa95b0dd: tg_secret.raw.types.DecryptedMessageMediaExternalDocument,
    0x36b091de: tg_secret.raw.types.DecryptedMessage_45,
    0xf1fa8d78: tg_secret.raw.types.DecryptedMessageMediaPhoto_45,
    0x970c8c0e: tg_secret.raw.types.DecryptedMessageMediaVideo_45,
    0x7afe8ae2: tg_secret.raw.types.DecryptedMessageMediaDocument_45,
    0x3a556302: tg_secret.raw.types.DocumentAttributeSticker_45,
    0xded218e0: tg_secret.raw.types.DocumentAttributeAudio_45,
    0xbb92ba95: tg_secret.raw.types.MessageEntityUnknown,
    0xfa04579d: tg_secret.raw.types.MessageEntityMention,
    0x6f635b0d: tg_secret.raw.types.MessageEntityHashtag,
    0x6cef8ac7: tg_secret.raw.types.MessageEntityBotCommand,
    0x6ed02538: tg_secret.raw.types.MessageEntityUrl,
    0x64e475c2: tg_secret.raw.types.MessageEntityEmail,
    0xbd610bc9: tg_secret.raw.types.MessageEntityBold,
    0x826f8b60: tg_secret.raw.types.MessageEntityItalic,
    0x28a20571: tg_secret.raw.types.MessageEntityCode,
    0x73924be0: tg_secret.raw.types.MessageEntityPre,
    0x76a6d327: tg_secret.raw.types.MessageEntityTextUrl,
    0x861cc8a0: tg_secret.raw.types.InputStickerSetShortName,
    0xffb62b95: tg_secret.raw.types.InputStickerSetEmpty,
    0x8a0df56f: tg_secret.raw.types.DecryptedMessageMediaVenue,
    0xe50511d8: tg_secret.raw.types.DecryptedMessageMediaWebPage,
    0x9852f9c6: tg_secret.raw.types.DocumentAttributeAudio_46,
    0xef02ce6: tg_secret.raw.types.DocumentAttributeVideo_66,
    0x88f27fbc: tg_secret.raw.types.SendMessageRecordRoundAction,
    0xbb718624: tg_secret.raw.types.SendMessageUploadRoundAction,
    0x91cc4674: tg_secret.raw.types.DecryptedMessage_73,
    0x9c4e7e8b: tg_secret.raw.types.MessageEntityUnderline,
    0xbf0693d4: tg_secret.raw.types.MessageEntityStrike,
    0x20df5d0: tg_secret.raw.types.MessageEntityBlockquote,
    0x6abd9782: tg_secret.raw.types.DecryptedMessageMediaDocument_143,
    0x32ca960f: tg_secret.raw.types.MessageEntitySpoiler,
    0xc8cf05f8: tg_secret.raw.types.MessageEntityCustomEmoji,
    0xbc799737: tg_secret.raw.primitives.BoolFalse,
    0x997275b5: tg_secret.raw.primitives.BoolTrue,
    0x1cb5c415: tg_secret.raw.vector.Vector,
}
