# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/terraquantum/plan/v1/plan/plan.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'com/terraquantum/plan/v1/plan/plan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(com/terraquantum/plan/v1/plan/plan.proto\x12\x1d\x63om.terraquantum.plan.v1.plan\"q\n\tPlanProto\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12@\n\x04type\x18\x02 \x01(\x0e\x32,.com.terraquantum.plan.v1.plan.PlanTypeProtoR\x04type\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name*S\n\rPlanTypeProto\x12\x19\n\x15PLAN_TYPE_UNSPECIFIED\x10\x00\x12\t\n\x05\x42\x41SIC\x10\x01\x12\x0e\n\nENTERPRISE\x10\x02\x12\x0c\n\x08\x41\x43\x41\x44\x45MIC\x10\x03\x42\x8b\x02\n!com.com.terraquantum.plan.v1.planB\tPlanProtoP\x01ZAterraquantum.swiss/tq42_grpc_client/com/terraquantum/plan/v1/plan\xa2\x02\x05\x43TPVP\xaa\x02\x1d\x43om.Terraquantum.Plan.V1.Plan\xca\x02\x1d\x43om\\Terraquantum\\Plan\\V1\\Plan\xe2\x02)Com\\Terraquantum\\Plan\\V1\\Plan\\GPBMetadata\xea\x02!Com::Terraquantum::Plan::V1::Planb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.terraquantum.plan.v1.plan.plan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.com.terraquantum.plan.v1.planB\tPlanProtoP\001ZAterraquantum.swiss/tq42_grpc_client/com/terraquantum/plan/v1/plan\242\002\005CTPVP\252\002\035Com.Terraquantum.Plan.V1.Plan\312\002\035Com\\Terraquantum\\Plan\\V1\\Plan\342\002)Com\\Terraquantum\\Plan\\V1\\Plan\\GPBMetadata\352\002!Com::Terraquantum::Plan::V1::Plan'
  _globals['_PLANTYPEPROTO']._serialized_start=190
  _globals['_PLANTYPEPROTO']._serialized_end=273
  _globals['_PLANPROTO']._serialized_start=75
  _globals['_PLANPROTO']._serialized_end=188
# @@protoc_insertion_point(module_scope)
