
#                     !!! WARNING !!!
#             This is an auto-generated file!
#                 Generated by [Builder].
# Any manual modifications will be lost upon regeneration.
#             DO NOT EDIT THIS FILE DIRECTLY.

from typing import TYPE_CHECKING, List
from ....gadgets.tlobject import TLRequest
from ....gadgets.byteutils import Writer


if TYPE_CHECKING:
    from ...types.input_user import TypeInputUser


class ReorderUsernames(TLRequest[bool]):
    """
    Reorder usernames associated to a bot we own.

    Raises:
        `400`BotInvalidError: This is not a valid bot.
        `400`UsernameNotModifiedError: The username was not modified.

    """

    _id = 0X9709B1C2
    _result_id = 0X43B904E1

    def __init__(
        self,
        bot: 'TypeInputUser',
        order: List[str]
    ):

        """
        Reorder usernames associated to a bot we own.

        Args:
            bot ('TypeInputUser'): The bot
            order (List[str]): The new order for active usernames. All active usernames must be specified.
        """

        self.bot = bot
        self.order = order

    def to_bytes(self, boxed: bool=True):
        with Writer(b'\xc2\xb1\t\x97' if boxed else b'') as writer:
            writer.object(
                self.bot,
                group_id=0XB628962F
            )
            writer.vector(
                self.order,
                writer.string
            )

            return writer.getvalue()