from .. import get_engine_name as get_engine_name, get_schema_name as get_schema_name
from ....auth.auth_router import AuthRouter as AuthRouter
from ....schemas.query_request import QueryRequest as QueryRequest
from ....services.data_service import DataService as DataService
from ....utils.response_utils import ResponseUtil as ResponseUtil
from ..entity_table.t_enum_field import TEnumField as TEnumField, TEnumFieldCreate as TEnumFieldCreate, TEnumFieldResponse as TEnumFieldResponse, TEnumFieldUpdate as TEnumFieldUpdate
from _typeshed import Incomplete
from sqlmodel.ext.asyncio.session import AsyncSession as AsyncSession

TEnumField_Router: Incomplete

async def t_enum_field_query(*, query: QueryRequest, db: AsyncSession = ...): ...
async def t_enum_field_create(*, create_model: TEnumFieldCreate, db: AsyncSession = ...): ...
async def t_enum_field_read(*, primary_id: int, db: AsyncSession = ...): ...
async def t_enum_field_update(*, primary_id: int, update_model: TEnumFieldUpdate, db: AsyncSession = ...): ...
async def t_enum_field_delete(*, primary_id: int, db: AsyncSession = ...): ...
