/*
 * Generated by asn1c-v0.9.27-1413-ge0c0052e-dirty for Python bindings (https://github.com/MatrixEditor/asn1c-bindings)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_AP_invocation_identifier_PY_H_
#define	_AP_invocation_identifier_PY_H_


#include <AP-invocation-identifier.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AP-invocation-identifier */
PyCompat_DEF_STRUCT(AP_invocation_identifier);
PyCompat_DEF_TYPE(AP_invocation_identifier);

/* Type Converters */
static inline PyObject *PyAsnAP_invocation_identifier_ToPython(AP_invocation_identifier_t *pSrc, PyObject *parent)
{
	return PyCompatLong_FromSsize_t(*pSrc);
}
static inline int PyAsnAP_invocation_identifier_FromPython(PyObject *pObj, AP_invocation_identifier_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(AP_invocation_identifier, pObj, pDst);
	PyCompatLong_Check(pObj, -1);
	*pDst = (AP_invocation_identifier_t)PyCompatLong_AsSsize_t(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnAP_invocation_identifier_ModSetupTypes(void);
void PyAsnAP_invocation_identifier_ModClear(PyObject *);
int PyAsnAP_invocation_identifier_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _AP_invocation_identifier_PY_H_ */
