
#                     !!! WARNING !!!
#             This is an auto-generated file!
#                 Generated by [Builder].
# Any manual modifications will be lost upon regeneration.
#             DO NOT EDIT THIS FILE DIRECTLY.

from ...types.updates import TypeUpdates
from ....gadgets.tlobject import TLRequest
from ....gadgets.byteutils import Writer


class ActivateStealthMode(TLRequest[TypeUpdates]):
    """
    Activates [stories stealth mode](https://core.telegram.org/api/stories#stealth-mode), see [here](https://core.telegram.org/api/stories#stealth-mode) for more info.

    Raises:
        `400`PremiumAccountRequiredError: A premium account is required to execute this action.

    """

    _id = 0X57BBD166
    _result_id = 0XD68D29C0

    def __init__(
        self,
        past: bool = False,
        future: bool = False
    ):

        """
        Activates [stories stealth mode](https://core.telegram.org/api/stories#stealth-mode), see [here](https://core.telegram.org/api/stories#stealth-mode) for more info.

        Args:
            past (bool, optional): Whether to erase views from any stories opened in the past [stories_stealth_past_period seconds](https://core.telegram.org/api/config#stories-stealth-past-period), as specified by the [client configuration](https://core.telegram.org/api/config#client-configuration).
            future (bool, optional): Whether to hide future story views for the next [stories_stealth_future_period seconds](https://core.telegram.org/api/config#stories-stealth-future-period), as specified by the [client configuration](https://core.telegram.org/api/config#client-configuration).
        """

        self.past = past
        self.future = future

    def to_bytes(self, boxed: bool=True):
        with Writer(b'f\xd1\xbbW' if boxed else b'') as writer:
            with writer.flag() as flags:
                flags(self.past, 0)
                flags(self.future, 1)

            return writer.getvalue()