from typing import ClassVar, Collection

from invenio_records_permissions.generators import Generator
from invenio_records_permissions.policies.records import RecordPermissionPolicy
from invenio_requests.services.permissions import (
    PermissionPolicy as RequestPermissionPolicy,
)

class RDMRecordPermissionPolicy(RecordPermissionPolicy):
    NEED_LABEL_TO_ACTION: dict[str, str]
    can_manage_internal: ClassVar[Collection[Generator]]
    can_manage: ClassVar[Collection[Generator]]
    can_curate: ClassVar[Collection[Generator]]
    can_review: ClassVar[Collection[Generator]]
    can_preview: ClassVar[Collection[Generator]]
    can_view: ClassVar[Collection[Generator]]
    can_authenticated: ClassVar[Collection[Generator]]
    can_all: ClassVar[Collection[Generator]]
    can_query_stats: ClassVar[Collection[Generator]]
    can_search: ClassVar[Collection[Generator]]
    can_read: ClassVar[Collection[Generator]]
    can_read_deleted: ClassVar[Collection[Generator]]
    can_read_deleted_files: ClassVar[Collection[Generator]]
    can_media_read_deleted_files: ClassVar[Collection[Generator]]
    can_read_files: ClassVar[Collection[Generator]]
    can_get_content_files: ClassVar[Collection[Generator]]
    can_create: ClassVar[Collection[Generator]]
    can_search_revisions: ClassVar[Collection[Generator]]
    can_search_drafts: ClassVar[Collection[Generator]]
    can_read_draft: ClassVar[Collection[Generator]]
    can_draft_read_files: ClassVar[Collection[Generator]]
    can_update_draft: ClassVar[Collection[Generator]]
    can_draft_create_files: ClassVar[Collection[Generator]]
    can_draft_set_content_files: ClassVar[Collection[Generator]]
    can_draft_get_content_files: ClassVar[Collection[Generator]]
    can_draft_commit_files: ClassVar[Collection[Generator]]
    can_draft_update_files: ClassVar[Collection[Generator]]
    can_draft_delete_files: ClassVar[Collection[Generator]]
    can_draft_get_file_transfer_metadata: ClassVar[Collection[Generator]]
    can_draft_update_file_transfer_metadata: ClassVar[Collection[Generator]]
    can_manage_files: ClassVar[Collection[Generator]]
    can_manage_record_access: ClassVar[Collection[Generator]]
    can_pid_create: ClassVar[Collection[Generator]]
    can_pid_register: ClassVar[Collection[Generator]]
    can_pid_update: ClassVar[Collection[Generator]]
    can_pid_discard: ClassVar[Collection[Generator]]
    can_pid_delete: ClassVar[Collection[Generator]]
    can_pid_manage: ClassVar[Collection[Generator]]
    can_edit: ClassVar[Collection[Generator]]
    can_delete_draft: ClassVar[Collection[Generator]]
    can_new_version: ClassVar[Collection[Generator]]
    can_publish: ClassVar[Collection[Generator]]
    can_lift_embargo: ClassVar[Collection[Generator]]
    can_add_community: ClassVar[Collection[Generator]]
    can_remove_community_: ClassVar[Collection[Generator]]
    can_remove_community: ClassVar[Collection[Generator]]
    can_remove_record: ClassVar[Collection[Generator]]
    can_bulk_add: ClassVar[Collection[Generator]]
    can_draft_media_create_files: ClassVar[Collection[Generator]]
    can_draft_media_read_files: ClassVar[Collection[Generator]]
    can_draft_media_set_content_files: ClassVar[Collection[Generator]]
    can_draft_media_get_content_files: ClassVar[Collection[Generator]]
    can_draft_media_commit_files: ClassVar[Collection[Generator]]
    can_draft_media_update_files: ClassVar[Collection[Generator]]
    can_draft_media_delete_files: ClassVar[Collection[Generator]]
    can_media_read_files: ClassVar[Collection[Generator]]
    can_media_get_content_files: ClassVar[Collection[Generator]]
    can_media_create_files: ClassVar[Collection[Generator]]
    can_media_set_content_files: ClassVar[Collection[Generator]]
    can_media_commit_files: ClassVar[Collection[Generator]]
    can_media_update_files: ClassVar[Collection[Generator]]
    can_media_delete_files: ClassVar[Collection[Generator]]
    can_delete: ClassVar[Collection[Generator]]
    can_delete_files: ClassVar[Collection[Generator]]
    can_purge: ClassVar[Collection[Generator]]
    can_manage_quota: ClassVar[Collection[Generator]]
    can_update: ClassVar[Collection[Generator]]
    can_create_files: ClassVar[Collection[Generator]]
    can_set_content_files: ClassVar[Collection[Generator]]
    can_commit_files: ClassVar[Collection[Generator]]
    can_update_files: ClassVar[Collection[Generator]]
    can_get_file_transfer_metadata: ClassVar[Collection[Generator]]
    can_update_file_transfer_metadata: ClassVar[Collection[Generator]]
    can_moderate: ClassVar[Collection[Generator]]

guest_token: Any

class RDMRequestsPermissionPolicy(RequestPermissionPolicy):
    can_read: ClassVar[Collection[Generator]]
    can_update: ClassVar[Collection[Generator]]
    can_action_submit: ClassVar[Collection[Generator]]
    can_action_cancel: ClassVar[Collection[Generator]]
    can_create_comment: ClassVar[Collection[Generator]]
    can_update_comment: ClassVar[Collection[Generator]]
    can_delete_comment: ClassVar[Collection[Generator]]
    can_manage_access_options: ClassVar[Collection[Generator]]
