from invenio_records_resources.resources.records.resource import RecordResource, request_extra_args, request_search_args, request_view_args

class AuditLogResource(RecordResource):
    def create_blueprint(self, **options): ...
    def create_url_rules(self): ...
    @request_extra_args
    @request_search_args
    @request_view_args
    def search(self): ...
    @request_extra_args
    @request_view_args
    def read(self): ...
