#!/usr/bin/env python

from enum import Enum

MARKER_TRANSMISSION_START: str = "<TRANSMISSION_START>"
MARKER_TRANSMISSION_END: str = "<TRANSMISSION_END>"
MARKER_FILE_START: bytes = b"<FILE_START>"
MARKER_FILE_END: bytes = b"<FILE_END>"


class TransmissionType(str, Enum):
    UNKNOWN = "UNKNOWN"
    CLERK_READY = "CLERK_READY"
    APPLICANT_READY = "APPLICANT_READY"
    AUTH_REQUEST = "AUTH_REQUEST"
    AUTH_RESPONSE = "AUTH_RESPONSE"
    PROCEDURE_REQUEST = "PROCEDURE_REQUEST"
    PROCEDURE_RESPONSE = "PROCEDURE_RESPONSE"
    FILE_RECEIVING_RECEIPT = "FILE_RECEIVING_RECEIPT"
    PROCEDURE_RECEIPT = "PROCEDURE_RECEIPT"


class FileType(str, Enum):
    NONE = "NONE"
    SINGLE = "SINGLE"
    ARCHIVE = "ARCHIVE"
