from _typeshed import Incomplete
from minio import Minio
from minjiang_client.com.organization import is_org_user as is_org_user
from minjiang_client.com.oss import get_global as get_global, get_oss_config as get_oss_config
from minjiang_client.com.user import get_user_info as get_user_info
from typing import Any

MINIO_MAP: Incomplete

def get_minio_client(is_global: bool = False, organization_id: int = None): ...

class MinIOAPI:
    config: dict
    client: Minio | None
    def __init__(self, is_global: bool = False, organization_id: int = None) -> None: ...
    @staticmethod
    def get_config(is_global: bool, organization_id: int = None): ...
    def open_client(self) -> None: ...
    def upload(self, indicator: Any, data: Any, file_cate: str, file_format: str) -> dict: ...
    def upload_normal(self, obj_key: str, file_name: str) -> dict: ...
    def download(self, uri: dict | str) -> Any: ...
    def download_to_file(self, uri: dict | str, path: str): ...
    def presign(self, uri: dict | str, expiry_hour: int = 2): ...
