/*
 * Generated by asn1c-v0.9.27-1413-ge0c0052e-dirty for Python bindings (https://github.com/MatrixEditor/asn1c-bindings)
 * From ASN.1 module "ISO8823-PRESENTATION"
 */

#include <Fully-encoded-data_Py.h>

/* class implementation */
PY_IMPL_SEQ_OF_ITEM_TOPY(Fully_encoded_data, PDV_list_t, PyAsnPDV_list_ToPython((PDV_list_t *)src, parent));
PY_IMPL_SEQ_OF_ITEM_FROMPY(Fully_encoded_data, PDV_list_t, PyAsnPDV_list_FromPython(value, (PDV_list_t *)target));
PY_IMPL_SEQ_OF_FROMPY(Fully_encoded_data, PDV_list_t);
PY_IMPL_SEQ_OF_SETITEM(Fully_encoded_data, PDV_list_t);
PY_IMPL_SEQ_OF_ADD(Fully_encoded_data, PDV_list_t);
PY_IMPL_SEQ_OF_NEW(Fully_encoded_data);
PY_IMPL_SEQ_OF_DEALLOC(Fully_encoded_data, asn_set_empty);
PY_IMPL_SEQ_OF_INIT(Fully_encoded_data);
PY_IMPL_SEQ_OF_REPR(Fully_encoded_data);
PY_IMPL_GENERIC_CHECK_CONSTRAINTS(Fully_encoded_data);
PY_IMPL_GENERIC_ENCODE(Fully_encoded_data);
PY_IMPL_GENERIC_DECODE(Fully_encoded_data);
PY_IMPL_SEQ_GENERIC_TOPY(Fully_encoded_data);
PY_IMPL_DECODE_BER(Fully_encoded_data);
PY_IMPL_ENCODE_SPECIFIC(Fully_encoded_data, ber, ATS_BER);
PY_IMPL_DECODE_DER(Fully_encoded_data);
PY_IMPL_ENCODE_SPECIFIC(Fully_encoded_data, der, ATS_DER);
PY_IMPL_DECODE_CER(Fully_encoded_data);
PY_IMPL_ENCODE_SPECIFIC(Fully_encoded_data, cer, ATS_BER);
PY_IMPL_DECODE_XER(Fully_encoded_data);
PY_IMPL_ENCODE_XER(Fully_encoded_data);
PY_IMPL_ENCODE_SPECIFIC(Fully_encoded_data, plain, ATS_NONSTANDARD_PLAINTEXT);
PY_IMPL_DECODE_JER(Fully_encoded_data);
PY_IMPL_ENCODE_JER(Fully_encoded_data);
PY_IMPL_GENERIC_IS_VALID(Fully_encoded_data);
PY_IMPL_SEQ_OF_LEN(Fully_encoded_data);
PY_IMPL_SEQ_OF_GETITEM(Fully_encoded_data);
PY_IMPL_SEQ_OF_CLEAR(Fully_encoded_data);
PY_IMPL_SEQ_OF_EXTEND(Fully_encoded_data);

/* class attributes definition */
static PyGetSetDef PyAsnFully_encoded_data_getset[] = {
	{NULL, NULL, NULL, NULL, NULL} /* sentinel */
};
static PySequenceMethods PyAsnFully_encoded_data_seq_methods = {
	.sq_item = (ssizeargfunc)PyAsnFully_encoded_data__getitem,
	.sq_length = (lenfunc)PyAsnFully_encoded_data__len,
	.sq_ass_item = (ssizeobjargproc)PyAsnFully_encoded_data__setitem,
};

/* class methods definition */
static PyMethodDef PyAsnFully_encoded_data_methods[] = {
	PY_IMPL_METHODDEF_ITEM(Fully_encoded_data, is_valid, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Fully_encoded_data, check_constraints, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Fully_encoded_data, ber_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Fully_encoded_data, ber_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(Fully_encoded_data, der_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Fully_encoded_data, der_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(Fully_encoded_data, cer_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Fully_encoded_data, cer_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(Fully_encoded_data, xer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(Fully_encoded_data, xer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{"to_text", (PyCFunction)PyAsnFully_encoded_data__plain_encode, (METH_NOARGS), NULL},
	PY_IMPL_METHODDEF_ITEM(Fully_encoded_data, jer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(Fully_encoded_data, jer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(Fully_encoded_data, clear, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Fully_encoded_data, extend, METH_VARARGS),
	PY_IMPL_METHODDEF_ITEM(Fully_encoded_data, add, METH_VARARGS | METH_KEYWORDS),
	{NULL, NULL, 0, NULL} /* sentinel */
};

/* type definition */
PyTypeObject PyAsnFully_encoded_data_Type = {
	PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "_iso8823.Fully_encoded_data",
	.tp_basicsize = sizeof(PyAsnFully_encoded_dataObject),
	.tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
	.tp_new = (newfunc)PyAsnFully_encoded_data__new,
	.tp_repr = (reprfunc)PyAsnFully_encoded_data__repr,
	.tp_dealloc = (destructor)PyAsnFully_encoded_data__dealloc,
	.tp_init = (initproc)PyAsnFully_encoded_data__init,
	.tp_getset = PyAsnFully_encoded_data_getset,
	.tp_methods = PyAsnFully_encoded_data_methods,
	.tp_doc = "ASN.1 Fully_encoded_data type",
	.tp_as_sequence = &PyAsnFully_encoded_data_seq_methods,
};

/* module initializer */
int PyAsnFully_encoded_data_ModSetupTypes(void) {
	if (PyType_Ready(&PyAsnFully_encoded_data_Type) < 0) return -1;
    return 0;
}

void PyAsnFully_encoded_data_ModClear(PyObject *mod) {
}

int PyAsnFully_encoded_data_ModInit(PyObject *mod) {
	PY_IMPL_MOD_ADD_OBJECT(mod, Fully_encoded_data);
    return 0;
}

/* end of Fully-encoded-data_Py.c */
