"""
LingHu 包主类型提示文件
"""

from typing import Optional, Dict, Any
import logging

# 重新导出所有类型
from ..utils.base import Base
from ..utils.logger import Logger, LoggerManager
from ..modules.login import Login, 登录模块

# 版本信息
__version__: str
__author__: str = "LingHu Team"

# 快捷函数类型提示
def get_logger(name: Optional[str] = ...) -> logging.Logger: ...
def setup_logging(**kwargs) -> None: ...
def configure_logging(**kwargs) -> None: ...
def get_logging_config() -> Dict[str, Any]: ...
def get_log_file_path() -> Optional[str]: ...

# 日志快捷函数
def debug(msg: str, *args, **kwargs) -> None: ...
def info(msg: str, *args, **kwargs) -> None: ...
def warning(msg: str, *args, **kwargs) -> None: ...
def error(msg: str, *args, **kwargs) -> None: ...
def critical(msg: str, *args, **kwargs) -> None: ...
def exception(msg: str, *args, **kwargs) -> None: ...

# 版本管理函数
def get_version() -> str: ...
def increment_version(level: str = ...) -> str: ...
def get_version_info() -> Dict[str, Any]: ...