from pathlib import PurePath

CHUB_BUILD_DIR = PurePath("chub-build")
CHUB_LIBS_DIR = "libs"
CHUB_SCRIPTS_DIR = "scripts"
CHUB_PRE_INSTALL_SCRIPTS_DIR = "pre"
CHUB_POST_INSTALL_SCRIPTS_DIR = "post"
CHUB_INCLUDES_DIR = "includes"
RUNTIME_DIR = "runtime"
CHUBCONFIG_FILENAME = ".chubconfig"

CHUB_BUILD_DIR_STRUCTURE = [
    CHUB_BUILD_DIR / CHUB_LIBS_DIR,
    CHUB_BUILD_DIR / CHUB_SCRIPTS_DIR,
    CHUB_BUILD_DIR / CHUB_SCRIPTS_DIR / CHUB_PRE_INSTALL_SCRIPTS_DIR,
    CHUB_BUILD_DIR / CHUB_SCRIPTS_DIR / CHUB_POST_INSTALL_SCRIPTS_DIR,
    CHUB_BUILD_DIR / CHUB_INCLUDES_DIR,
    CHUB_BUILD_DIR / RUNTIME_DIR
]
