from fastmcp.tools import FunctionTool
from pydantic import BaseModel

class CythonModelMeta(type(BaseModel)):
    def __new__(cls, name, bases, namespace) -> type(BaseModel): ...

class CythonBaseModel(BaseModel, metaclass=CythonModelMeta): ...

class CythonFunctionTool(CythonBaseModel, FunctionTool): ...
