from .titlebbar import QuteTitleBar as QuteTitleBar
from .utils import is_window_resizable as is_window_resizable, merge_content_area_and_title_bar as merge_content_area_and_title_bar, set_window_non_resizable as set_window_non_resizable
from qtpy.QtGui import QResizeEvent as QResizeEvent, QShowEvent as QShowEvent
from qtpy.QtWidgets import QDialog, QWidget as QWidget

class QuteDialog(QDialog):
    def __init__(self, parent: QWidget | None = None) -> None: ...
    def titleBar(self) -> QWidget: ...
    def setTitleBar(self, titleBar: QWidget) -> None: ...
    def setNonResizable(self) -> None: ...
    def isResizable(self) -> None: ...
    def showEvent(self, event: QShowEvent) -> None: ...
    def resizeEvent(self, e: QResizeEvent) -> None: ...
    def setWindowTitle(self, title: str) -> None: ...
    def windowTitle(self) -> str: ...
