from cusrl.environment import make_gym_env, make_gym_vec
from cusrl.preset import ppo
from cusrl.zoo.registry import register_experiment

__all__ = []

register_experiment(
    environment_name="Acrobot-v1",
    algorithm_name="ppo",
    agent_factory_cls=ppo.AgentFactory,
    agent_factory_kwargs=dict(
        num_steps_per_update=16,
        actor_hidden_dims=(64, 64),
        critic_hidden_dims=(64, 64),
        activation_fn="Tanh",
        action_space_type="discrete",
        lr=3e-4,
        sampler_epochs=4,
        sampler_mini_batches=64,
        orthogonal_init=False,
        normalize_observation=True,
        gae_gamma=0.99,
        gae_lamda=0.94,
        entropy_loss_weight=0.0,
        max_grad_norm=0.5,
    ),
    training_env_factory=make_gym_vec,
    training_env_kwargs={"num_envs": 16},
    playing_env_factory=make_gym_env,
    playing_env_kwargs={"render_mode": "human"},
    num_iterations=500,
    save_interval=50,
)

register_experiment(
    environment_name="CartPole-v1",
    algorithm_name="ppo",
    agent_factory_cls=ppo.AgentFactory,
    agent_factory_kwargs=dict(
        num_steps_per_update=32,
        actor_hidden_dims=(64, 64),
        critic_hidden_dims=(64, 64),
        activation_fn="Tanh",
        action_space_type="discrete",
        lr=1e-3,
        sampler_epochs=20,
        sampler_mini_batches=1,
        gae_gamma=0.8,
        gae_lamda=0.98,
        entropy_loss_weight=0.0,
        max_grad_norm=0.5,
    ),
    training_env_factory=make_gym_vec,
    training_env_kwargs={"num_envs": 8, "vectorization_mode": "sync"},
    playing_env_factory=make_gym_env,
    playing_env_kwargs={"render_mode": "human"},
    num_iterations=400,
    save_interval=50,
)

register_experiment(
    environment_name="MountainCar-v0",
    algorithm_name="ppo",
    agent_factory_cls=ppo.AgentFactory,
    agent_factory_kwargs=dict(
        num_steps_per_update=16,
        actor_hidden_dims=(64, 64),
        critic_hidden_dims=(64, 64),
        activation_fn="Tanh",
        action_space_type="discrete",
        lr=3e-4,
        sampler_epochs=4,
        sampler_mini_batches=4,
        orthogonal_init=False,
        normalize_observation=True,
        gae_gamma=0.99,
        gae_lamda=0.98,
        entropy_loss_weight=0.0,
        max_grad_norm=0.5,
    ),
    training_env_factory=make_gym_vec,
    training_env_kwargs={"num_envs": 16},
    playing_env_factory=make_gym_env,
    playing_env_kwargs={"render_mode": "human"},
    num_iterations=2000,
    save_interval=500,
)

register_experiment(
    environment_name="MountainCarContinuous-v0",
    algorithm_name="ppo",
    agent_factory_cls=ppo.AgentFactory,
    agent_factory_kwargs=dict(
        num_steps_per_update=8,
        actor_hidden_dims=(64, 64),
        critic_hidden_dims=(64, 64),
        activation_fn="Tanh",
        value_loss_weight=0.19,
        lr=7.77e-5,
        sampler_epochs=10,
        sampler_mini_batches=1,
        orthogonal_init=False,
        init_distribution_std=0.04,
        normalize_observation=True,
        gae_gamma=0.9999,
        gae_lamda=0.9,
        surrogate_clip_ratio=0.1,
        entropy_loss_weight=0.00429,
        max_grad_norm=5.0,
    ),
    training_env_factory=make_gym_vec,
    training_env_kwargs={"num_envs": 1},
    playing_env_factory=make_gym_env,
    playing_env_kwargs={"render_mode": "human"},
    num_iterations=2500,
    save_interval=500,
)

register_experiment(
    environment_name="Pendulum-v1",
    algorithm_name="ppo",
    agent_factory_cls=ppo.AgentFactory,
    agent_factory_kwargs=dict(
        actor_hidden_dims=(64, 64),
        critic_hidden_dims=(64, 64),
        activation_fn="Tanh",
        sampler_epochs=10,
        sampler_mini_batches=64,
        num_steps_per_update=1024,
        normalize_observation=True,
        gae_gamma=0.9,
        lr=1e-3,
        entropy_loss_weight=0.0,
        max_grad_norm=0.5,
    ),
    training_env_factory=make_gym_vec,
    training_env_kwargs={"num_envs": 4},
    playing_env_factory=make_gym_env,
    playing_env_kwargs={"render_mode": "human"},
    num_iterations=50,
    save_interval=25,
)
