# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/terraquantum/organization/v2/organization/organization.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'com/terraquantum/organization/v2/organization/organization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@com/terraquantum/organization/v2/organization/organization.proto\x12-com.terraquantum.organization.v2.organization\x1a\x1b\x62uf/validate/validate.proto\"\x94\x01\n\x11OrganizationProto\x12\x18\n\x02id\x18\x01 \x01(\tB\x08\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1b\n\x04name\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x04name\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\x12&\n\x0fis_personal_org\x18\x04 \x01(\x08R\risPersonalOrgB\xf3\x02\n1com.com.terraquantum.organization.v2.organizationB\x11OrganizationProtoP\x01ZQterraquantum.swiss/tq42_grpc_client/com/terraquantum/organization/v2/organization\xa2\x02\x05\x43TOVO\xaa\x02-Com.Terraquantum.Organization.V2.Organization\xca\x02-Com\\Terraquantum\\Organization\\V2\\Organization\xe2\x02\x39\x43om\\Terraquantum\\Organization\\V2\\Organization\\GPBMetadata\xea\x02\x31\x43om::Terraquantum::Organization::V2::Organizationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.terraquantum.organization.v2.organization.organization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1com.com.terraquantum.organization.v2.organizationB\021OrganizationProtoP\001ZQterraquantum.swiss/tq42_grpc_client/com/terraquantum/organization/v2/organization\242\002\005CTOVO\252\002-Com.Terraquantum.Organization.V2.Organization\312\002-Com\\Terraquantum\\Organization\\V2\\Organization\342\0029Com\\Terraquantum\\Organization\\V2\\Organization\\GPBMetadata\352\0021Com::Terraquantum::Organization::V2::Organization'
  _globals['_ORGANIZATIONPROTO'].fields_by_name['id']._loaded_options = None
  _globals['_ORGANIZATIONPROTO'].fields_by_name['id']._serialized_options = b'\272H\005r\003\260\001\001'
  _globals['_ORGANIZATIONPROTO'].fields_by_name['name']._loaded_options = None
  _globals['_ORGANIZATIONPROTO'].fields_by_name['name']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_ORGANIZATIONPROTO']._serialized_start=145
  _globals['_ORGANIZATIONPROTO']._serialized_end=293
# @@protoc_insertion_point(module_scope)
