
#                     !!! WARNING !!!
#             This is an auto-generated file!
#                 Generated by [Builder].
# Any manual modifications will be lost upon regeneration.
#             DO NOT EDIT THIS FILE DIRECTLY.

from typing import TYPE_CHECKING
from ....gadgets.tlobject import TLRequest
from ....gadgets.byteutils import Writer


if TYPE_CHECKING:
    from ...types.input_chatlist import TypeInputChatlist


class HideChatlistUpdates(TLRequest[bool]):
    """
    Dismiss new pending peers recently added to a [chat folder deep link](https://core.telegram.org/api/links#chat-folder-links).

    Raises:
        `400`FilterIdInvalidError: The specified filter ID is invalid.
        `400`FilterNotSupportedError: The specified filter cannot be used in this context.

    """

    _id = 0X66E486FB
    _result_id = 0X43B904E1

    def __init__(
        self,
        chatlist: 'TypeInputChatlist'
    ):

        """
        Dismiss new pending peers recently added to a [chat folder deep link](https://core.telegram.org/api/links#chat-folder-links).

        Args:
            chatlist ('TypeInputChatlist'): The folder
        """

        self.chatlist = chatlist

    def to_bytes(self, boxed: bool=True):
        with Writer(b'\xfb\x86\xe4f' if boxed else b'') as writer:
            writer.object(
                self.chatlist,
                group_id=0XF1847C0F
            )

            return writer.getvalue()