from com.terraquantum.organization.v1.organization import organization_member_pb2 as _organization_member_pb2
from com.terraquantum.organization.v1.organization import create_organization_member_request_pb2 as _create_organization_member_request_pb2
from com.terraquantum.organization.v1.organization import reactivate_organization_member_request_pb2 as _reactivate_organization_member_request_pb2
from com.terraquantum.organization.v1.organization import inactivate_organization_member_request_pb2 as _inactivate_organization_member_request_pb2
from com.terraquantum.organization.v1.organization import update_organization_member_request_pb2 as _update_organization_member_request_pb2
from com.terraquantum.organization.v1.organization import get_organization_member_by_id_request_pb2 as _get_organization_member_by_id_request_pb2
from com.terraquantum.organization.v1.organization import get_organization_member_by_organization_id_and_user_id_without_permissions_request_pb2 as _get_organization_member_by_organization_id_and_user_id_without_permissions_request_pb2
from com.terraquantum.organization.v1.organization import list_organization_members_by_organization_id_request_pb2 as _list_organization_members_by_organization_id_request_pb2
from com.terraquantum.organization.v1.organization import list_organization_members_by_organization_id_and_organization_members_ids_request_pb2 as _list_organization_members_by_organization_id_and_organization_members_ids_request_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
