from ._const import *


class TRTBuilderFlag(Enum):
    FP16 = 0
    BF16 = 17
    INT8 = 1
    DEBUG = 2
    GPU_FALLBACK = 3
    REFIT = 4
    DISABLE_TIMING_CACHE = 5
    TF32 = 6
    SPARSE_WEIGHTS = 7
    SAFETY_SCOPE = 8
    OBEY_PRECISION_CONSTRAINTS = 9
    PREFER_PRECISION_CONSTRAINTS = 10
    DIRECT_IO = 11
    REJECT_EMPTY_ALGORITHMS = 12
    VERSION_COMPATIBLE = 13
    EXCLUDE_LEAN_RUNTIME = 14
    FP8 = 15
    ERROR_ON_TIMING_CACHE_MISS = 16
    DISABLE_COMPILATION_CACHE = 18
    WEIGHTLESS = 19
    REFIT_IDENTICAL = 20
    WEIGHT_STREAMING = 21
    INT4 = 22
    REFIT_INDIVIDUAL = 23
