"""Purple-themed CLI styling for T3 API utilities."""

from t3api_utils.style.console import console
from t3api_utils.style.styles import (
    error_style,
    info_style,
    success_style,
    warning_style,
    progress_style,
    header_style,
    subheader_style,
    menu_style,
    file_path_style,
    technical_style,
    data_style,
    primary_style,
    accent_style,
    muted_style,
)
from t3api_utils.style.messages import (
    print_success,
    print_error,
    print_warning,
    print_info,
    print_progress,
    print_header,
    print_subheader,
    print_menu_item,
    print_file_path,
    print_technical,
    print_data,
    print_labeled_info,
    print_state_info,
)

__all__ = [
    "console",
    # Styles
    "error_style",
    "info_style",
    "success_style",
    "warning_style",
    "progress_style",
    "header_style",
    "subheader_style",
    "menu_style",
    "file_path_style",
    "technical_style",
    "data_style",
    "primary_style",
    "accent_style",
    "muted_style",
    # Message functions
    "print_success",
    "print_error",
    "print_warning",
    "print_info",
    "print_progress",
    "print_header",
    "print_subheader",
    "print_menu_item",
    "print_file_path",
    "print_technical",
    "print_data",
    "print_labeled_info",
    "print_state_info",
]