
#                     !!! WARNING !!!
#             This is an auto-generated file!
#                 Generated by [Builder].
# Any manual modifications will be lost upon regeneration.
#             DO NOT EDIT THIS FILE DIRECTLY.

from ....gadgets.tlobject import TLRequest
from ....gadgets.byteutils import Writer


class ResetAuthorization(TLRequest[bool]):
    """
    Log out an active [authorized session](https://core.telegram.org/api/auth) by its hash

    Raises:
        `406`FreshResetAuthorisationForbiddenError: You can't logout other sessions if less than 24 hours have passed since you logged on the current session.
        `400`HashInvalidError: The provided hash is invalid.

    """

    _id = 0XDF77F3BC
    _result_id = 0X43B904E1

    def __init__(
        self,
        hash: int
    ):

        """
        Log out an active [authorized session](https://core.telegram.org/api/auth) by its hash

        Args:
            hash (int): Session hash
        """

        self.hash = hash

    def to_bytes(self, boxed: bool=True):
        with Writer(b'\xbc\xf3w\xdf' if boxed else b'') as writer:
            writer.long(self.hash)

            return writer.getvalue()