# Contains all the necessary ordering and linkages between
# the CP tools that have to run.

g_metadata_names_no_overlap = {
    "jet_collection": [
        "sys_error_tool",
        "pileup_tool",
        "corrections_jet",
        "add_calibration_to_job",
    ],
    "electron_collection": [
        "sys_error_tool",
        "pileup_tool",
        "corrections_electron",
        "add_calibration_to_job",
    ],
    "muon_collection": [
        "sys_error_tool",
        "pileup_tool",
        "corrections_muon",
        "add_calibration_to_job",
    ],
    "photon_collection": [
        "sys_error_tool",
        "pileup_tool",
        "corrections_photon",
        "add_calibration_to_job",
    ],
    "tau_collection": [
        "sys_error_tool",
        "pileup_tool",
        "corrections_tau",
        "add_calibration_to_job",
    ],
    "met_collection": [
        "sys_error_tool",
        "pileup_tool",
        "corrections_jet",
        "corrections_muon",
        "corrections_electron",
        "corrections_met",
        "add_calibration_to_job",
    ],
}

g_metadata_names_overlap = {
    "jet_collection": [
        "sys_error_tool",
        "pileup_tool",
        "corrections_jet",
        "corrections_muon",
        "corrections_electron",
        "corrections_photon",
        "corrections_tau",
        "corrections_overlap",
        "add_calibration_to_job",
    ],
    "electron_collection": [
        "sys_error_tool",
        "pileup_tool",
        "corrections_jet",
        "corrections_muon",
        "corrections_electron",
        "corrections_photon",
        "corrections_tau",
        "corrections_overlap",
        "add_calibration_to_job",
    ],
    "muon_collection": [
        "sys_error_tool",
        "pileup_tool",
        "corrections_jet",
        "corrections_muon",
        "corrections_electron",
        "corrections_photon",
        "corrections_tau",
        "corrections_overlap",
        "add_calibration_to_job",
    ],
    "photon_collection": [
        "sys_error_tool",
        "pileup_tool",
        "corrections_jet",
        "corrections_muon",
        "corrections_electron",
        "corrections_photon",
        "corrections_tau",
        "corrections_overlap",
        "add_calibration_to_job",
    ],
    "tau_collection": [
        "sys_error_tool",
        "pileup_tool",
        "corrections_jet",
        "corrections_muon",
        "corrections_electron",
        "corrections_photon",
        "corrections_tau",
        "corrections_overlap",
        "add_calibration_to_job",
    ],
    "met_collection": [
        "sys_error_tool",
        "pileup_tool",
        "corrections_jet",
        "corrections_muon",
        "corrections_electron",
        "corrections_met",
        "add_calibration_to_job",
    ],
}
