/*
 * Generated by asn1c-v0.9.27-1413-ge0c0052e-dirty for Python bindings (https://github.com/MatrixEditor/asn1c-bindings)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <Cancel-RequestPDU_Py.h>

/* class implementation */
PY_IMPL_GENERIC_NEW(Cancel_RequestPDU, NULL);
PY_IMPL_GENERIC_INIT(Cancel_RequestPDU);
PY_IMPL_GENERIC_DEALLOC(Cancel_RequestPDU);
PY_IMPL_REPR(Cancel_RequestPDU);
PY_IMPL_GENERIC_STR(Cancel_RequestPDU);
PY_IMPL_GENERIC_CHECK_CONSTRAINTS(Cancel_RequestPDU);
PY_IMPL_GENERIC_IS_VALID(Cancel_RequestPDU);
PY_IMPL_GENERIC_ENCODE(Cancel_RequestPDU);
PY_IMPL_GENERIC_DECODE(Cancel_RequestPDU);
PY_IMPL_DECODE_BER(Cancel_RequestPDU);
PY_IMPL_ENCODE_SPECIFIC(Cancel_RequestPDU, ber, ATS_BER);
PY_IMPL_DECODE_DER(Cancel_RequestPDU);
PY_IMPL_ENCODE_SPECIFIC(Cancel_RequestPDU, der, ATS_DER);
PY_IMPL_DECODE_CER(Cancel_RequestPDU);
PY_IMPL_ENCODE_SPECIFIC(Cancel_RequestPDU, cer, ATS_BER);
PY_IMPL_DECODE_XER(Cancel_RequestPDU);
PY_IMPL_ENCODE_XER(Cancel_RequestPDU);
PY_IMPL_ENCODE_SPECIFIC(Cancel_RequestPDU, plain, ATS_NONSTANDARD_PLAINTEXT);
PY_IMPL_DECODE_JER(Cancel_RequestPDU);
PY_IMPL_ENCODE_JER(Cancel_RequestPDU);
PY_IMPL_MEMBER_GETSET(Cancel_RequestPDU, value, Cancel_RequestPDU, self->ob_value);

/* class attributes definition */
static PyGetSetDef PyAsnCancel_RequestPDU_getset[] = {
	PY_IMPL_GETSET_ITEM(Cancel_RequestPDU, value),
	{NULL, NULL, NULL, NULL, NULL} /* sentinel */
};

/* class methods definition */
static PyMethodDef PyAsnCancel_RequestPDU_methods[] = {
	PY_IMPL_METHODDEF_ITEM(Cancel_RequestPDU, is_valid, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Cancel_RequestPDU, check_constraints, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Cancel_RequestPDU, ber_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Cancel_RequestPDU, ber_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(Cancel_RequestPDU, der_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Cancel_RequestPDU, der_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(Cancel_RequestPDU, cer_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(Cancel_RequestPDU, cer_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(Cancel_RequestPDU, xer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(Cancel_RequestPDU, xer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{"to_text", (PyCFunction)PyAsnCancel_RequestPDU__plain_encode, (METH_NOARGS), NULL},
	PY_IMPL_METHODDEF_ITEM(Cancel_RequestPDU, jer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(Cancel_RequestPDU, jer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{NULL, NULL, 0, NULL} /* sentinel */
};

/* type definition */
PyTypeObject PyAsnCancel_RequestPDU_Type = {
	PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "_mms.Cancel_RequestPDU",
	.tp_basicsize = sizeof(PyAsnCancel_RequestPDUObject),
	.tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
	.tp_new = (newfunc)PyAsnCancel_RequestPDU__new,
	.tp_repr = (reprfunc)PyAsnCancel_RequestPDU__repr,
	.tp_dealloc = (destructor)PyAsnCancel_RequestPDU__dealloc,
	.tp_init = (initproc)PyAsnCancel_RequestPDU__init,
	.tp_getset = PyAsnCancel_RequestPDU_getset,
	.tp_methods = PyAsnCancel_RequestPDU_methods,
	.tp_doc = "ASN.1 Cancel_RequestPDU type",
	.tp_str = (reprfunc)PyAsnCancel_RequestPDU__str,
};

/* module initializer */
int PyAsnCancel_RequestPDU_ModSetupTypes(void) {
	if (PyType_Ready(&PyAsnCancel_RequestPDU_Type) < 0) return -1;
    return 0;
}

void PyAsnCancel_RequestPDU_ModClear(PyObject *mod) {
}

int PyAsnCancel_RequestPDU_ModInit(PyObject *mod) {
	PY_IMPL_MOD_ADD_OBJECT(mod, Cancel_RequestPDU);
    return 0;
}

/* end of Cancel-RequestPDU_Py.c */
