/*
 * Generated by asn1c-v0.9.27-1413-ge0c0052e-dirty for Python bindings (https://github.com/MatrixEditor/asn1c-bindings)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <EEAttributes_Py.h>

/* class implementation */
PY_IMPL_CHOICE_ATTR_FROMPY(EEAttributes_eventConditionName_ANON_3, EEAttributes__eventConditionName, eventCondition, eventCondition,PyAsnObjectName_FromPython(value, &dst->choice.eventCondition));
PY_IMPL_CHOICE_ATTR_TOPY(EEAttributes_eventConditionName_ANON_3, eventCondition, PyCompatAsnType_FromParent(&PyAsnObjectName_Type, parent,  (void *)&src->choice.eventCondition));
PY_IMPL_CHOICE_GETATTR(EEAttributes_eventConditionName_ANON_3, EEAttributes__eventConditionName, eventCondition, eventCondition);
PY_IMPL_CHOICE_GENERIC_SETATTR(EEAttributes_eventConditionName_ANON_3, EEAttributes__eventConditionName, eventCondition, eventCondition, *asn_DEF_EEAttributes.elements[1].type);
PY_IMPL_CHOICE_ATTR_FROMPY(EEAttributes_eventConditionName_ANON_3, EEAttributes__eventConditionName, undefined, undefined, PyCompatNull_FromObject(value, &dst->choice.undefined));
PY_IMPL_CHOICE_ATTR_TOPY(EEAttributes_eventConditionName_ANON_3, undefined, Py_None);
PY_IMPL_CHOICE_GETATTR(EEAttributes_eventConditionName_ANON_3, EEAttributes__eventConditionName, undefined, undefined);
PY_IMPL_CHOICE_GENERIC_SETATTR(EEAttributes_eventConditionName_ANON_3, EEAttributes__eventConditionName, undefined, undefined, *asn_DEF_EEAttributes.elements[1].type);
PY_IMPL_CHECK_CONSTRAINTS(EEAttributes_eventConditionName_ANON_3, asn_DEF_EEAttributes.elements[1].type);
PY_IMPL_ENCODE(EEAttributes_eventConditionName_ANON_3, asn_DEF_EEAttributes.elements[1].type);
PY_IMPL_DECODE(EEAttributes_eventConditionName_ANON_3, asn_DEF_EEAttributes.elements[1].type);
PY_IMPL_DEALLOC(EEAttributes_eventConditionName_ANON_3, *(asn_DEF_EEAttributes.elements[1].type));
PY_IMPL_SEQ_TOPY(EEAttributes_eventConditionName_ANON_3, asn_DEF_EEAttributes.elements[1].type);
PY_IMPL_GENERIC_REPR(EEAttributes_eventConditionName_ANON_3, EEAttributes__eventConditionName);
PY_IMPL_DECODE_BER(EEAttributes_eventConditionName_ANON_3);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes_eventConditionName_ANON_3, ber, ATS_BER);
PY_IMPL_DECODE_DER(EEAttributes_eventConditionName_ANON_3);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes_eventConditionName_ANON_3, der, ATS_DER);
PY_IMPL_DECODE_CER(EEAttributes_eventConditionName_ANON_3);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes_eventConditionName_ANON_3, cer, ATS_BER);
PY_IMPL_DECODE_XER(EEAttributes_eventConditionName_ANON_3);
PY_IMPL_ENCODE_XER(EEAttributes_eventConditionName_ANON_3);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes_eventConditionName_ANON_3, plain, ATS_NONSTANDARD_PLAINTEXT);
PY_IMPL_DECODE_JER(EEAttributes_eventConditionName_ANON_3);
PY_IMPL_ENCODE_JER(EEAttributes_eventConditionName_ANON_3);
PyObject *PyAsnEnumEEAttributes_eventConditionName_ANON_3_PRESENT_Type = NULL;
PY_IMPL_CHOICE_PRESENT_ATTR(EEAttributes_eventConditionName_ANON_3);
PY_IMPL_GENERIC_NEW(EEAttributes_eventConditionName_ANON_3, NULL);
PY_IMPL_GENERIC_IS_VALID(EEAttributes_eventConditionName_ANON_3);
PY_IMPL_CHOICE_FROMPY(EEAttributes_eventConditionName_ANON_3, asn_DEF_EEAttributes.elements[1].type,
	PY_IMPL_CHOICE_INIT_ATTR(EEAttributes_eventConditionName_ANON_3, EEAttributes__eventConditionName, eventCondition, eventCondition, eventCondition);
	PY_IMPL_CHOICE_INIT_ATTR(EEAttributes_eventConditionName_ANON_3, EEAttributes__eventConditionName, undefined, undefined, undefined);
);
PY_IMPL_CHOICE_INIT_GENERIC(EEAttributes_eventConditionName_ANON_3, EEAttributes__eventConditionName);
PY_IMPL_SEQ_ANON_ATTR_FROMPY(EEAttributes, eventConditionName, &src->eventConditionName, EEAttributes_eventConditionName_ANON_3);
PY_IMPL_SEQ_ANON_ATTR_TOPY(EEAttributes, eventConditionName, &src->eventConditionName, EEAttributes_eventConditionName_ANON_3);
PY_IMPL_SEQ_INNER_SETATTR(EEAttributes, eventConditionName, eventConditionName, EEAttributes_eventConditionName_ANON_3);
PY_IMPL_SEQ_INNER_GETATTR(EEAttributes, eventConditionName, &self->ob_value->eventConditionName, EEAttributes_eventConditionName_ANON_3);
PY_IMPL_CHOICE_ATTR_FROMPY(EEAttributes_eventActionName_ANON_6, EEAttributes__eventActionName, eventAction, eventAction,PyAsnObjectName_FromPython(value, &dst->choice.eventAction));
PY_IMPL_CHOICE_ATTR_TOPY(EEAttributes_eventActionName_ANON_6, eventAction, PyCompatAsnType_FromParent(&PyAsnObjectName_Type, parent,  (void *)&src->choice.eventAction));
PY_IMPL_CHOICE_GETATTR(EEAttributes_eventActionName_ANON_6, EEAttributes__eventActionName, eventAction, eventAction);
PY_IMPL_CHOICE_GENERIC_SETATTR(EEAttributes_eventActionName_ANON_6, EEAttributes__eventActionName, eventAction, eventAction, *asn_DEF_EEAttributes.elements[2].type);
PY_IMPL_CHOICE_ATTR_FROMPY(EEAttributes_eventActionName_ANON_6, EEAttributes__eventActionName, undefined, undefined, PyCompatNull_FromObject(value, &dst->choice.undefined));
PY_IMPL_CHOICE_ATTR_TOPY(EEAttributes_eventActionName_ANON_6, undefined, Py_None);
PY_IMPL_CHOICE_GETATTR(EEAttributes_eventActionName_ANON_6, EEAttributes__eventActionName, undefined, undefined);
PY_IMPL_CHOICE_GENERIC_SETATTR(EEAttributes_eventActionName_ANON_6, EEAttributes__eventActionName, undefined, undefined, *asn_DEF_EEAttributes.elements[2].type);
PY_IMPL_CHECK_CONSTRAINTS(EEAttributes_eventActionName_ANON_6, asn_DEF_EEAttributes.elements[2].type);
PY_IMPL_ENCODE(EEAttributes_eventActionName_ANON_6, asn_DEF_EEAttributes.elements[2].type);
PY_IMPL_DECODE(EEAttributes_eventActionName_ANON_6, asn_DEF_EEAttributes.elements[2].type);
PY_IMPL_DEALLOC(EEAttributes_eventActionName_ANON_6, *(asn_DEF_EEAttributes.elements[2].type));
PY_IMPL_SEQ_TOPY(EEAttributes_eventActionName_ANON_6, asn_DEF_EEAttributes.elements[2].type);
PY_IMPL_GENERIC_REPR(EEAttributes_eventActionName_ANON_6, EEAttributes__eventActionName);
PY_IMPL_DECODE_BER(EEAttributes_eventActionName_ANON_6);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes_eventActionName_ANON_6, ber, ATS_BER);
PY_IMPL_DECODE_DER(EEAttributes_eventActionName_ANON_6);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes_eventActionName_ANON_6, der, ATS_DER);
PY_IMPL_DECODE_CER(EEAttributes_eventActionName_ANON_6);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes_eventActionName_ANON_6, cer, ATS_BER);
PY_IMPL_DECODE_XER(EEAttributes_eventActionName_ANON_6);
PY_IMPL_ENCODE_XER(EEAttributes_eventActionName_ANON_6);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes_eventActionName_ANON_6, plain, ATS_NONSTANDARD_PLAINTEXT);
PY_IMPL_DECODE_JER(EEAttributes_eventActionName_ANON_6);
PY_IMPL_ENCODE_JER(EEAttributes_eventActionName_ANON_6);
PyObject *PyAsnEnumEEAttributes_eventActionName_ANON_6_PRESENT_Type = NULL;
PY_IMPL_CHOICE_PRESENT_ATTR(EEAttributes_eventActionName_ANON_6);
PY_IMPL_GENERIC_NEW(EEAttributes_eventActionName_ANON_6, NULL);
PY_IMPL_GENERIC_IS_VALID(EEAttributes_eventActionName_ANON_6);
PY_IMPL_CHOICE_FROMPY(EEAttributes_eventActionName_ANON_6, asn_DEF_EEAttributes.elements[2].type,
	PY_IMPL_CHOICE_INIT_ATTR(EEAttributes_eventActionName_ANON_6, EEAttributes__eventActionName, eventAction, eventAction, eventAction);
	PY_IMPL_CHOICE_INIT_ATTR(EEAttributes_eventActionName_ANON_6, EEAttributes__eventActionName, undefined, undefined, undefined);
);
PY_IMPL_CHOICE_INIT_GENERIC(EEAttributes_eventActionName_ANON_6, EEAttributes__eventActionName);
PY_IMPL_SEQ_ANON_ATTR_FROMPY(EEAttributes, eventActionName, src->eventActionName, EEAttributes_eventActionName_ANON_6);
PY_IMPL_SEQ_ANON_ATTR_TOPY(EEAttributes, eventActionName, src->eventActionName, EEAttributes_eventActionName_ANON_6);
PY_IMPL_SEQ_INNER_OPT_SETATTR(EEAttributes, eventActionName, eventActionName, EEAttributes_eventActionName_ANON_6, *asn_DEF_EEAttributes.elements[2].type);
PY_IMPL_SEQ_INNER_GETATTR(EEAttributes, eventActionName, self->ob_value->eventActionName, EEAttributes_eventActionName_ANON_6);
PY_IMPL_CHOICE_ATTR_FROMPY(EEAttributes_displayEnhancement_ANON_15, EEAttributes__displayEnhancement, string, string,PyCompatUnicode_AsUTF8(value, &dst->choice.string.buf, &dst->choice.string.size));
PY_IMPL_CHOICE_ATTR_TOPY(EEAttributes_displayEnhancement_ANON_15, string, PyCompatUnicode_FromStringAndSize(src->choice.string.buf, src->choice.string.size));
PY_IMPL_CHOICE_GETATTR(EEAttributes_displayEnhancement_ANON_15, EEAttributes__displayEnhancement, string, string);
PY_IMPL_CHOICE_GENERIC_SETATTR(EEAttributes_displayEnhancement_ANON_15, EEAttributes__displayEnhancement, string, string, *asn_DEF_EEAttributes.elements[9].type);
PY_IMPL_CHOICE_ATTR_FROMPY(EEAttributes_displayEnhancement_ANON_15, EEAttributes__displayEnhancement, index, index, PyCompatLong_FromObject(value, (void *)&dst->choice.index, 1));
PY_IMPL_CHOICE_ATTR_TOPY(EEAttributes_displayEnhancement_ANON_15, index, PyCompatLong_AsObject((void *)&src->choice.index, 1));
PY_IMPL_CHOICE_GETATTR(EEAttributes_displayEnhancement_ANON_15, EEAttributes__displayEnhancement, index, index);
PY_IMPL_CHOICE_GENERIC_SETATTR(EEAttributes_displayEnhancement_ANON_15, EEAttributes__displayEnhancement, index, index, *asn_DEF_EEAttributes.elements[9].type);
PY_IMPL_CHOICE_ATTR_FROMPY(EEAttributes_displayEnhancement_ANON_15, EEAttributes__displayEnhancement, noEnhancement, noEnhancement, PyCompatNull_FromObject(value, &dst->choice.noEnhancement));
PY_IMPL_CHOICE_ATTR_TOPY(EEAttributes_displayEnhancement_ANON_15, noEnhancement, Py_None);
PY_IMPL_CHOICE_GETATTR(EEAttributes_displayEnhancement_ANON_15, EEAttributes__displayEnhancement, noEnhancement, noEnhancement);
PY_IMPL_CHOICE_GENERIC_SETATTR(EEAttributes_displayEnhancement_ANON_15, EEAttributes__displayEnhancement, noEnhancement, noEnhancement, *asn_DEF_EEAttributes.elements[9].type);
PY_IMPL_CHECK_CONSTRAINTS(EEAttributes_displayEnhancement_ANON_15, asn_DEF_EEAttributes.elements[9].type);
PY_IMPL_ENCODE(EEAttributes_displayEnhancement_ANON_15, asn_DEF_EEAttributes.elements[9].type);
PY_IMPL_DECODE(EEAttributes_displayEnhancement_ANON_15, asn_DEF_EEAttributes.elements[9].type);
PY_IMPL_DEALLOC(EEAttributes_displayEnhancement_ANON_15, *(asn_DEF_EEAttributes.elements[9].type));
PY_IMPL_SEQ_TOPY(EEAttributes_displayEnhancement_ANON_15, asn_DEF_EEAttributes.elements[9].type);
PY_IMPL_GENERIC_REPR(EEAttributes_displayEnhancement_ANON_15, EEAttributes__displayEnhancement);
PY_IMPL_DECODE_BER(EEAttributes_displayEnhancement_ANON_15);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes_displayEnhancement_ANON_15, ber, ATS_BER);
PY_IMPL_DECODE_DER(EEAttributes_displayEnhancement_ANON_15);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes_displayEnhancement_ANON_15, der, ATS_DER);
PY_IMPL_DECODE_CER(EEAttributes_displayEnhancement_ANON_15);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes_displayEnhancement_ANON_15, cer, ATS_BER);
PY_IMPL_DECODE_XER(EEAttributes_displayEnhancement_ANON_15);
PY_IMPL_ENCODE_XER(EEAttributes_displayEnhancement_ANON_15);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes_displayEnhancement_ANON_15, plain, ATS_NONSTANDARD_PLAINTEXT);
PY_IMPL_DECODE_JER(EEAttributes_displayEnhancement_ANON_15);
PY_IMPL_ENCODE_JER(EEAttributes_displayEnhancement_ANON_15);
PyObject *PyAsnEnumEEAttributes_displayEnhancement_ANON_15_PRESENT_Type = NULL;
PY_IMPL_CHOICE_PRESENT_ATTR(EEAttributes_displayEnhancement_ANON_15);
PY_IMPL_GENERIC_NEW(EEAttributes_displayEnhancement_ANON_15, NULL);
PY_IMPL_GENERIC_IS_VALID(EEAttributes_displayEnhancement_ANON_15);
PY_IMPL_CHOICE_FROMPY(EEAttributes_displayEnhancement_ANON_15, asn_DEF_EEAttributes.elements[9].type,
	PY_IMPL_CHOICE_INIT_ATTR(EEAttributes_displayEnhancement_ANON_15, EEAttributes__displayEnhancement, string, string, string);
	PY_IMPL_CHOICE_INIT_ATTR(EEAttributes_displayEnhancement_ANON_15, EEAttributes__displayEnhancement, index, index, index);
	PY_IMPL_CHOICE_INIT_ATTR(EEAttributes_displayEnhancement_ANON_15, EEAttributes__displayEnhancement, noEnhancement, noEnhancement, noEnhancement);
);
PY_IMPL_CHOICE_INIT_GENERIC(EEAttributes_displayEnhancement_ANON_15, EEAttributes__displayEnhancement);
PY_IMPL_SEQ_ANON_ATTR_FROMPY(EEAttributes, displayEnhancement, &src->displayEnhancement, EEAttributes_displayEnhancement_ANON_15);
PY_IMPL_SEQ_ANON_ATTR_TOPY(EEAttributes, displayEnhancement, &src->displayEnhancement, EEAttributes_displayEnhancement_ANON_15);
PY_IMPL_SEQ_INNER_SETATTR(EEAttributes, displayEnhancement, displayEnhancement, EEAttributes_displayEnhancement_ANON_15);
PY_IMPL_SEQ_INNER_GETATTR(EEAttributes, displayEnhancement, &self->ob_value->displayEnhancement, EEAttributes_displayEnhancement_ANON_15);
PY_IMPL_SEQ_ATTR_FROMPY(EEAttributes, eventEnrollmentName, PyAsnObjectName_FromPython(value, (ObjectName_t *)target));
PY_IMPL_SEQ_REF_ATTR_TOPY(EEAttributes, eventEnrollmentName, ObjectName);
PY_IMPL_SEQ_GETATTR(EEAttributes, eventEnrollmentName);
PY_IMPL_SEQ_SETATTR(EEAttributes, eventEnrollmentName);
PY_IMPL_SEQ_ATTR_GENERIC_FREE(EEAttributes, clientApplication);
PY_IMPL_SEQ_ATTR_GENERIC_NEW(EEAttributes, clientApplication, ApplicationReference_t);
PY_IMPL_SEQ_ATTR_INDIRECT_FROMPY(EEAttributes, clientApplication, PyAsnApplicationReference_FromPython(value, (ApplicationReference_t *)target));
PY_IMPL_SEQ_REF_ATTR_INDIRECT_TOPY(EEAttributes, clientApplication, ApplicationReference);
PY_IMPL_SEQ_OPT_GETATTR(EEAttributes, clientApplication);
PY_IMPL_SEQ_OPT_SETATTR(EEAttributes, clientApplication);
PY_IMPL_SEQ_ATTR_FROMPY(EEAttributes, mmsDeletable, PyCompatBool_FromObject(value, (unsigned int *)target));
PY_IMPL_SEQ_ATTR_TOPY(EEAttributes, mmsDeletable, PyCompatBool_FromLong(*(BOOLEAN_t *)target));
PY_IMPL_SEQ_GETATTR(EEAttributes, mmsDeletable);
PY_IMPL_SEQ_SETATTR(EEAttributes, mmsDeletable);
PY_IMPL_SEQ_ATTR_FROMPY(EEAttributes, enrollmentClass, PyAsnEE_Class_FromPython(value, (EE_Class_t *)target));
PY_IMPL_SEQ_REF_ATTR_TOPY(EEAttributes, enrollmentClass, EE_Class);
PY_IMPL_SEQ_GETATTR(EEAttributes, enrollmentClass);
PY_IMPL_SEQ_SETATTR(EEAttributes, enrollmentClass);
PY_IMPL_SEQ_ATTR_FROMPY(EEAttributes, duration, PyAsnEE_Duration_FromPython(value, (EE_Duration_t *)target));
PY_IMPL_SEQ_REF_ATTR_TOPY(EEAttributes, duration, EE_Duration);
PY_IMPL_SEQ_GETATTR(EEAttributes, duration);
PY_IMPL_SEQ_SETATTR(EEAttributes, duration);
PY_IMPL_SEQ_ATTR_GENERIC_FREE(EEAttributes, invokeID);
PY_IMPL_SEQ_ATTR_GENERIC_NEW(EEAttributes, invokeID, Unsigned32_t);
PY_IMPL_SEQ_ATTR_INDIRECT_FROMPY(EEAttributes, invokeID, PyAsnUnsigned32_FromPython(value, (Unsigned32_t *)target));
PY_IMPL_SEQ_REF_ATTR_INDIRECT_TOPY(EEAttributes, invokeID, Unsigned32);
PY_IMPL_SEQ_OPT_GETATTR(EEAttributes, invokeID);
PY_IMPL_SEQ_OPT_SETATTR(EEAttributes, invokeID);
PY_IMPL_SEQ_ATTR_GENERIC_FREE(EEAttributes, remainingAcceptableDelay);
PY_IMPL_SEQ_ATTR_GENERIC_NEW(EEAttributes, remainingAcceptableDelay, Unsigned32_t);
PY_IMPL_SEQ_ATTR_INDIRECT_FROMPY(EEAttributes, remainingAcceptableDelay, PyAsnUnsigned32_FromPython(value, (Unsigned32_t *)target));
PY_IMPL_SEQ_REF_ATTR_INDIRECT_TOPY(EEAttributes, remainingAcceptableDelay, Unsigned32);
PY_IMPL_SEQ_OPT_GETATTR(EEAttributes, remainingAcceptableDelay);
PY_IMPL_SEQ_OPT_SETATTR(EEAttributes, remainingAcceptableDelay);
PY_IMPL_SEQ_ATTR_GENERIC_FREE(EEAttributes, accessControlList);
PY_IMPL_SEQ_ATTR_GENERIC_NEW(EEAttributes, accessControlList, Identifier_t);
PY_IMPL_SEQ_ATTR_INDIRECT_FROMPY(EEAttributes, accessControlList, PyAsnIdentifier_FromPython(value, (Identifier_t *)target));
PY_IMPL_SEQ_REF_ATTR_INDIRECT_TOPY(EEAttributes, accessControlList, Identifier);
PY_IMPL_SEQ_OPT_GETATTR(EEAttributes, accessControlList);
PY_IMPL_SEQ_OPT_SETATTR(EEAttributes, accessControlList);
PY_IMPL_GENERIC_DEALLOC(EEAttributes);
PY_IMPL_GENERIC_CHECK_CONSTRAINTS(EEAttributes);
PY_IMPL_GENERIC_ENCODE(EEAttributes);
PY_IMPL_GENERIC_DECODE(EEAttributes);
PY_IMPL_SEQ_GENERIC_TOPY(EEAttributes);
PY_IMPL_DECODE_BER(EEAttributes);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes, ber, ATS_BER);
PY_IMPL_DECODE_DER(EEAttributes);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes, der, ATS_DER);
PY_IMPL_DECODE_CER(EEAttributes);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes, cer, ATS_BER);
PY_IMPL_DECODE_XER(EEAttributes);
PY_IMPL_ENCODE_XER(EEAttributes);
PY_IMPL_ENCODE_SPECIFIC(EEAttributes, plain, ATS_NONSTANDARD_PLAINTEXT);
PY_IMPL_DECODE_JER(EEAttributes);
PY_IMPL_ENCODE_JER(EEAttributes);
PY_IMPL_GENERIC_NEW(EEAttributes, &asn_DEF_EEAttributes);
PY_IMPL_REPR(EEAttributes);
PY_IMPL_GENERIC_IS_VALID(EEAttributes);
PY_IMPL_SEQ_FROMPY(EEAttributes, &asn_DEF_EEAttributes,
	PY_IMPL_SEQ_INIT_ATTR(EEAttributes, eventEnrollmentName, eventEnrollmentName);
	PY_IMPL_SEQ_INIT_ATTR(EEAttributes, eventConditionName, eventConditionName);
	PY_IMPL_SEQ_INIT_ATTR(EEAttributes, eventActionName, eventActionName);
	PY_IMPL_SEQ_INIT_ATTR(EEAttributes, clientApplication, clientApplication);
	PY_IMPL_SEQ_INIT_ATTR(EEAttributes, mmsDeletable, mmsDeletable);
	PY_IMPL_SEQ_INIT_ATTR(EEAttributes, enrollmentClass, enrollmentClass);
	PY_IMPL_SEQ_INIT_ATTR(EEAttributes, duration, duration);
	PY_IMPL_SEQ_INIT_ATTR(EEAttributes, invokeID, invokeID);
	PY_IMPL_SEQ_INIT_ATTR(EEAttributes, remainingAcceptableDelay, remainingAcceptableDelay);
	PY_IMPL_SEQ_INIT_ATTR(EEAttributes, displayEnhancement, displayEnhancement);
	PY_IMPL_SEQ_INIT_ATTR(EEAttributes, accessControlList, accessControlList);
);
PY_IMPL_SEQ_INIT(EEAttributes);

/* class attributes definition */
static PyGetSetDef PyAsnEEAttributes_eventConditionName_ANON_3_getset[] = {
	{"present",  (getter)PyAsnEEAttributes_eventConditionName_ANON_3__get_present, NULL, NULL, NULL},
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes_eventConditionName_ANON_3, eventCondition, eventCondition),
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes_eventConditionName_ANON_3, undefined, undefined),
	{NULL, NULL, NULL, NULL, NULL} /* sentinel */
};
static PyGetSetDef PyAsnEEAttributes_eventActionName_ANON_6_getset[] = {
	{"present",  (getter)PyAsnEEAttributes_eventActionName_ANON_6__get_present, NULL, NULL, NULL},
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes_eventActionName_ANON_6, eventAction, eventAction),
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes_eventActionName_ANON_6, undefined, undefined),
	{NULL, NULL, NULL, NULL, NULL} /* sentinel */
};
static PyGetSetDef PyAsnEEAttributes_displayEnhancement_ANON_15_getset[] = {
	{"present",  (getter)PyAsnEEAttributes_displayEnhancement_ANON_15__get_present, NULL, NULL, NULL},
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes_displayEnhancement_ANON_15, string, string),
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes_displayEnhancement_ANON_15, index, index),
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes_displayEnhancement_ANON_15, noEnhancement, noEnhancement),
	{NULL, NULL, NULL, NULL, NULL} /* sentinel */
};
static PyGetSetDef PyAsnEEAttributes_getset[] = {
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes, eventEnrollmentName, eventEnrollmentName),
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes, eventConditionName, eventConditionName),
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes, eventActionName, eventActionName),
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes, clientApplication, clientApplication),
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes, mmsDeletable, mmsDeletable),
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes, enrollmentClass, enrollmentClass),
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes, duration, duration),
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes, invokeID, invokeID),
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes, remainingAcceptableDelay, remainingAcceptableDelay),
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes, displayEnhancement, displayEnhancement),
	PY_IMPL_GETSET_ITEM_INTERNAL(EEAttributes, accessControlList, accessControlList),
	{NULL, NULL, NULL, NULL, NULL} /* sentinel */
};

/* class methods definition */
static PyMethodDef PyAsnEEAttributes_eventConditionName_ANON_3_methods[] = {
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventConditionName_ANON_3, is_valid, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventConditionName_ANON_3, check_constraints, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventConditionName_ANON_3, ber_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventConditionName_ANON_3, ber_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventConditionName_ANON_3, der_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventConditionName_ANON_3, der_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventConditionName_ANON_3, cer_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventConditionName_ANON_3, cer_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventConditionName_ANON_3, xer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventConditionName_ANON_3, xer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{"to_text", (PyCFunction)PyAsnEEAttributes_eventConditionName_ANON_3__plain_encode, (METH_NOARGS), NULL},
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventConditionName_ANON_3, jer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventConditionName_ANON_3, jer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{NULL, NULL, 0, NULL} /* sentinel */
};
static PyMethodDef PyAsnEEAttributes_eventActionName_ANON_6_methods[] = {
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventActionName_ANON_6, is_valid, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventActionName_ANON_6, check_constraints, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventActionName_ANON_6, ber_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventActionName_ANON_6, ber_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventActionName_ANON_6, der_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventActionName_ANON_6, der_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventActionName_ANON_6, cer_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventActionName_ANON_6, cer_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventActionName_ANON_6, xer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventActionName_ANON_6, xer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{"to_text", (PyCFunction)PyAsnEEAttributes_eventActionName_ANON_6__plain_encode, (METH_NOARGS), NULL},
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventActionName_ANON_6, jer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_eventActionName_ANON_6, jer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{NULL, NULL, 0, NULL} /* sentinel */
};
static PyMethodDef PyAsnEEAttributes_displayEnhancement_ANON_15_methods[] = {
	PY_IMPL_METHODDEF_ITEM(EEAttributes_displayEnhancement_ANON_15, is_valid, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_displayEnhancement_ANON_15, check_constraints, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_displayEnhancement_ANON_15, ber_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_displayEnhancement_ANON_15, ber_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_displayEnhancement_ANON_15, der_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_displayEnhancement_ANON_15, der_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_displayEnhancement_ANON_15, cer_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_displayEnhancement_ANON_15, cer_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_displayEnhancement_ANON_15, xer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_displayEnhancement_ANON_15, xer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{"to_text", (PyCFunction)PyAsnEEAttributes_displayEnhancement_ANON_15__plain_encode, (METH_NOARGS), NULL},
	PY_IMPL_METHODDEF_ITEM(EEAttributes_displayEnhancement_ANON_15, jer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes_displayEnhancement_ANON_15, jer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{NULL, NULL, 0, NULL} /* sentinel */
};
static PyMethodDef PyAsnEEAttributes_methods[] = {
	PY_IMPL_METHODDEF_ITEM(EEAttributes, is_valid, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes, check_constraints, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes, ber_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes, ber_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(EEAttributes, der_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes, der_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(EEAttributes, cer_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes, cer_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(EEAttributes, xer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes, xer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{"to_text", (PyCFunction)PyAsnEEAttributes__plain_encode, (METH_NOARGS), NULL},
	PY_IMPL_METHODDEF_ITEM(EEAttributes, jer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(EEAttributes, jer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{NULL, NULL, 0, NULL} /* sentinel */
};

/* type definition */
PyTypeObject PyAsnEEAttributes_eventConditionName_ANON_3_Type = {
	PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "_mms.EEAttributes.eventConditionName_TYPE",
	.tp_basicsize = sizeof(PyAsnEEAttributes_eventConditionName_ANON_3Object),
	.tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
	.tp_new = (newfunc)PyAsnEEAttributes_eventConditionName_ANON_3__new,
	.tp_repr = (reprfunc)PyAsnEEAttributes_eventConditionName_ANON_3__repr,
	.tp_dealloc = (destructor)PyAsnEEAttributes_eventConditionName_ANON_3__dealloc,
	.tp_init = (initproc)PyAsnEEAttributes_eventConditionName_ANON_3__init,
	.tp_getset = PyAsnEEAttributes_eventConditionName_ANON_3_getset,
	.tp_methods = PyAsnEEAttributes_eventConditionName_ANON_3_methods,
	.tp_doc = "ASN.1 anonymous type EEAttributes__eventConditionName_TYPE part of EEAttributes",
};
PyTypeObject PyAsnEEAttributes_eventActionName_ANON_6_Type = {
	PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "_mms.EEAttributes.eventActionName_TYPE",
	.tp_basicsize = sizeof(PyAsnEEAttributes_eventActionName_ANON_6Object),
	.tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
	.tp_new = (newfunc)PyAsnEEAttributes_eventActionName_ANON_6__new,
	.tp_repr = (reprfunc)PyAsnEEAttributes_eventActionName_ANON_6__repr,
	.tp_dealloc = (destructor)PyAsnEEAttributes_eventActionName_ANON_6__dealloc,
	.tp_init = (initproc)PyAsnEEAttributes_eventActionName_ANON_6__init,
	.tp_getset = PyAsnEEAttributes_eventActionName_ANON_6_getset,
	.tp_methods = PyAsnEEAttributes_eventActionName_ANON_6_methods,
	.tp_doc = "ASN.1 anonymous type EEAttributes__eventActionName_TYPE part of EEAttributes",
};
PyTypeObject PyAsnEEAttributes_displayEnhancement_ANON_15_Type = {
	PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "_mms.EEAttributes.displayEnhancement_TYPE",
	.tp_basicsize = sizeof(PyAsnEEAttributes_displayEnhancement_ANON_15Object),
	.tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
	.tp_new = (newfunc)PyAsnEEAttributes_displayEnhancement_ANON_15__new,
	.tp_repr = (reprfunc)PyAsnEEAttributes_displayEnhancement_ANON_15__repr,
	.tp_dealloc = (destructor)PyAsnEEAttributes_displayEnhancement_ANON_15__dealloc,
	.tp_init = (initproc)PyAsnEEAttributes_displayEnhancement_ANON_15__init,
	.tp_getset = PyAsnEEAttributes_displayEnhancement_ANON_15_getset,
	.tp_methods = PyAsnEEAttributes_displayEnhancement_ANON_15_methods,
	.tp_doc = "ASN.1 anonymous type EEAttributes__displayEnhancement_TYPE part of EEAttributes",
};
PyTypeObject PyAsnEEAttributes_Type = {
	PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "_mms.EEAttributes",
	.tp_basicsize = sizeof(PyAsnEEAttributesObject),
	.tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
	.tp_new = (newfunc)PyAsnEEAttributes__new,
	.tp_repr = (reprfunc)PyAsnEEAttributes__repr,
	.tp_dealloc = (destructor)PyAsnEEAttributes__dealloc,
	.tp_init = (initproc)PyAsnEEAttributes__init,
	.tp_getset = PyAsnEEAttributes_getset,
	.tp_methods = PyAsnEEAttributes_methods,
	.tp_doc = "ASN.1 EEAttributes type",
};

/* module initializer */
int PyAsnEEAttributes_ModSetupTypes(void) {
	if (PyType_Ready(&PyAsnEEAttributes_eventConditionName_ANON_3_Type) < 0) return -1;
	if (PyType_Ready(&PyAsnEEAttributes_eventActionName_ANON_6_Type) < 0) return -1;
	if (PyType_Ready(&PyAsnEEAttributes_displayEnhancement_ANON_15_Type) < 0) return -1;
	if (PyType_Ready(&PyAsnEEAttributes_Type) < 0) return -1;
    return 0;
}

void PyAsnEEAttributes_ModClear(PyObject *mod) {
	Py_CLEAR(PyAsnEnumEEAttributes_eventConditionName_ANON_3_PRESENT_Type);
	Py_CLEAR(PyAsnEnumEEAttributes_eventActionName_ANON_6_PRESENT_Type);
	Py_CLEAR(PyAsnEnumEEAttributes_displayEnhancement_ANON_15_PRESENT_Type);
}

int PyAsnEEAttributes_ModInit(PyObject *mod) {
	PY_IMPL_NEW_ENUM(EEAttributes.eventConditionName_TYPE.PRESENT, PyAsnEnumEEAttributes_eventConditionName_ANON_3_PRESENT_Type, -1, 
		PY_IMPL_ENUM_VALUE(PR_NOTHING, EEAttributes__eventConditionName_PR_NOTHING, 0);
		PY_IMPL_ENUM_VALUE(PR_eventCondition, EEAttributes__eventConditionName_PR_eventCondition, 1);
		PY_IMPL_ENUM_VALUE(PR_undefined, EEAttributes__eventConditionName_PR_undefined, 2);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(EEAttributes_eventConditionName_ANON_3, EEAttributes_eventConditionName_ANON_3_PRESENT, PRESENT);
	PY_IMPL_MOD_ASSIGN_OBJECT(EEAttributes, eventConditionName_TYPE, &PyAsnEEAttributes_eventConditionName_ANON_3_Type);
	PY_IMPL_MOD_ADD_OBJECT(mod, EEAttributes_eventConditionName_ANON_3);
	PY_IMPL_NEW_ENUM(EEAttributes.eventActionName_TYPE.PRESENT, PyAsnEnumEEAttributes_eventActionName_ANON_6_PRESENT_Type, -1, 
		PY_IMPL_ENUM_VALUE(PR_NOTHING, EEAttributes__eventActionName_PR_NOTHING, 0);
		PY_IMPL_ENUM_VALUE(PR_eventAction, EEAttributes__eventActionName_PR_eventAction, 1);
		PY_IMPL_ENUM_VALUE(PR_undefined, EEAttributes__eventActionName_PR_undefined, 2);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(EEAttributes_eventActionName_ANON_6, EEAttributes_eventActionName_ANON_6_PRESENT, PRESENT);
	PY_IMPL_MOD_ASSIGN_OBJECT(EEAttributes, eventActionName_TYPE, &PyAsnEEAttributes_eventActionName_ANON_6_Type);
	PY_IMPL_MOD_ADD_OBJECT(mod, EEAttributes_eventActionName_ANON_6);
	PY_IMPL_NEW_ENUM(EEAttributes.displayEnhancement_TYPE.PRESENT, PyAsnEnumEEAttributes_displayEnhancement_ANON_15_PRESENT_Type, -1, 
		PY_IMPL_ENUM_VALUE(PR_NOTHING, EEAttributes__displayEnhancement_PR_NOTHING, 0);
		PY_IMPL_ENUM_VALUE(PR_string, EEAttributes__displayEnhancement_PR_string, 1);
		PY_IMPL_ENUM_VALUE(PR_index, EEAttributes__displayEnhancement_PR_index, 2);
		PY_IMPL_ENUM_VALUE(PR_noEnhancement, EEAttributes__displayEnhancement_PR_noEnhancement, 3);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(EEAttributes_displayEnhancement_ANON_15, EEAttributes_displayEnhancement_ANON_15_PRESENT, PRESENT);
	PY_IMPL_MOD_ASSIGN_OBJECT(EEAttributes, displayEnhancement_TYPE, &PyAsnEEAttributes_displayEnhancement_ANON_15_Type);
	PY_IMPL_MOD_ADD_OBJECT(mod, EEAttributes_displayEnhancement_ANON_15);
	PY_IMPL_MOD_ADD_OBJECT(mod, EEAttributes);
    return 0;
}

/* end of EEAttributes_Py.c */
