#include "py_module.h"

/* Module Cleanup */
PY_IMPL_MODULE_CLEAR(_mms,
	PyAsnEMBEDDED_PDV_ModClear(m);
	PyAsnTimeOfDay_ModClear(m);
	PyAsnIdentifier_ModClear(m);
	PyAsnInteger8_ModClear(m);
	PyAsnInteger16_ModClear(m);
	PyAsnInteger32_ModClear(m);
	PyAsnUnsigned8_ModClear(m);
	PyAsnUnsigned16_ModClear(m);
	PyAsnUnsigned32_ModClear(m);
	PyAsnObjectName_ModClear(m);
	PyAsnObjectClass_ModClear(m);
	PyAsnMMSString_ModClear(m);
	PyAsnMMS255String_ModClear(m);
	PyAsnFileName_ModClear(m);
	PyAsnMMSpdu_ModClear(m);
	PyAsnConfirmed_RequestPDU_ModClear(m);
	PyAsnConfirmed_ErrorPDU_ModClear(m);
	PyAsnConfirmedServiceRequest_ModClear(m);
	PyAsnAdditionalService_Request_ModClear(m);
	PyAsnRequest_Detail_ModClear(m);
	PyAsnUnconfirmed_PDU_ModClear(m);
	PyAsnUnconfirmedService_ModClear(m);
	PyAsnUnconfirmed_Detail_ModClear(m);
	PyAsnConfirmed_ResponsePDU_ModClear(m);
	PyAsnConfirmedServiceResponse_ModClear(m);
	PyAsnAdditionalService_Response_ModClear(m);
	PyAsnResponse_Detail_ModClear(m);
	PyAsnServiceError_ModClear(m);
	PyAsnAdditionalService_Error_ModClear(m);
	PyAsnInitiate_RequestPDU_ModClear(m);
	PyAsnInitiate_ResponsePDU_ModClear(m);
	PyAsnInitiate_ErrorPDU_ModClear(m);
	PyAsnConclude_RequestPDU_ModClear(m);
	PyAsnConclude_ResponsePDU_ModClear(m);
	PyAsnConclude_ErrorPDU_ModClear(m);
	PyAsnCancel_RequestPDU_ModClear(m);
	PyAsnCancel_ResponsePDU_ModClear(m);
	PyAsnCancel_ErrorPDU_ModClear(m);
	PyAsnRejectPDU_ModClear(m);
	PyAsnDefineAccessControlList_Request_ModClear(m);
	PyAsnDefineAccessControlList_Response_ModClear(m);
	PyAsnGetAccessControlListAttributes_Request_ModClear(m);
	PyAsnGetAccessControlListAttributes_Response_ModClear(m);
	PyAsnReportAccessControlledObjects_Request_ModClear(m);
	PyAsnReportAccessControlledObjects_Response_ModClear(m);
	PyAsnDeleteAccessControlList_Request_ModClear(m);
	PyAsnDeleteAccessControlList_Response_ModClear(m);
	PyAsnChangeAccessControl_Request_ModClear(m);
	PyAsnChangeAccessControl_Response_ModClear(m);
	PyAsnChangeAccessControl_Error_ModClear(m);
	PyAsnStatusResponse_ModClear(m);
	PyAsnCS_Status_Response_ModClear(m);
	PyAsnOperationState_ModClear(m);
	PyAsnExtendedStatus_ModClear(m);
	PyAsnStatus_Request_ModClear(m);
	PyAsnStatus_Response_ModClear(m);
	PyAsnUnsolicitedStatus_ModClear(m);
	PyAsnGetNameList_Request_ModClear(m);
	PyAsnGetNameList_Response_ModClear(m);
	PyAsnIdentify_Request_ModClear(m);
	PyAsnIdentify_Response_ModClear(m);
	PyAsnRename_Request_ModClear(m);
	PyAsnRename_Response_ModClear(m);
	PyAsnGetCapabilityList_Request_ModClear(m);
	PyAsnGetCapabilityList_Response_ModClear(m);
	PyAsnVMDStop_Request_ModClear(m);
	PyAsnVMDStop_Response_ModClear(m);
	PyAsnVMDReset_Request_ModClear(m);
	PyAsnVMDReset_Response_ModClear(m);
	PyAsnInitiateDownloadSequence_Request_ModClear(m);
	PyAsnInitiateDownloadSequence_Response_ModClear(m);
	PyAsnDownloadSegment_Request_ModClear(m);
	PyAsnDownloadSegment_Response_ModClear(m);
	PyAsnLoadData_ModClear(m);
	PyAsnTerminateDownloadSequence_Request_ModClear(m);
	PyAsnTerminateDownloadSequence_Response_ModClear(m);
	PyAsnInitiateUploadSequence_Request_ModClear(m);
	PyAsnInitiateUploadSequence_Response_ModClear(m);
	PyAsnUploadSegment_Request_ModClear(m);
	PyAsnUploadSegment_Response_ModClear(m);
	PyAsnTerminateUploadSequence_Request_ModClear(m);
	PyAsnTerminateUploadSequence_Response_ModClear(m);
	PyAsnRequestDomainDownload_Request_ModClear(m);
	PyAsnRequestDomainDownload_Response_ModClear(m);
	PyAsnRequestDomainUpload_Request_ModClear(m);
	PyAsnRequestDomainUpload_Response_ModClear(m);
	PyAsnLoadDomainContent_Request_ModClear(m);
	PyAsnLoadDomainContent_Response_ModClear(m);
	PyAsnStoreDomainContent_Request_ModClear(m);
	PyAsnStoreDomainContent_Response_ModClear(m);
	PyAsnDeleteDomain_Request_ModClear(m);
	PyAsnDeleteDomain_Response_ModClear(m);
	PyAsnGetDomainAttributes_Request_ModClear(m);
	PyAsnGetDomainAttributes_Response_ModClear(m);
	PyAsnCreateProgramInvocation_Request_ModClear(m);
	PyAsnCreateProgramInvocation_Response_ModClear(m);
	PyAsnCS_CreateProgramInvocation_Request_ModClear(m);
	PyAsnDeleteProgramInvocation_Request_ModClear(m);
	PyAsnDeleteProgramInvocation_Response_ModClear(m);
	PyAsnStart_Request_ModClear(m);
	PyAsnStart_Response_ModClear(m);
	PyAsnStart_Error_ModClear(m);
	PyAsnCS_Start_Request_ModClear(m);
	PyAsnStartCount_ModClear(m);
	PyAsnStop_Request_ModClear(m);
	PyAsnStop_Response_ModClear(m);
	PyAsnStop_Error_ModClear(m);
	PyAsnResume_Request_ModClear(m);
	PyAsnResume_Response_ModClear(m);
	PyAsnResume_Error_ModClear(m);
	PyAsnCS_Resume_Request_ModClear(m);
	PyAsnReset_Request_ModClear(m);
	PyAsnReset_Response_ModClear(m);
	PyAsnReset_Error_ModClear(m);
	PyAsnKill_Request_ModClear(m);
	PyAsnKill_Response_ModClear(m);
	PyAsnGetProgramInvocationAttributes_Request_ModClear(m);
	PyAsnGetProgramInvocationAttributes_Response_ModClear(m);
	PyAsnCS_GetProgramInvocationAttributes_Response_ModClear(m);
	PyAsnSelect_Request_ModClear(m);
	PyAsnSelect_Response_ModClear(m);
	PyAsnAlterProgramInvocationAttributes_Request_ModClear(m);
	PyAsnAlterProgramInvocationAttributes_Response_ModClear(m);
	PyAsnControlElement_ModClear(m);
	PyAsnInitiateUnitControlLoad_Request_ModClear(m);
	PyAsnInitiateUnitControlLoad_Response_ModClear(m);
	PyAsnInitiateUnitControl_Error_ModClear(m);
	PyAsnUnitControlLoadSegment_Request_ModClear(m);
	PyAsnUnitControlLoadSegment_Response_ModClear(m);
	PyAsnUnitControlUpload_Request_ModClear(m);
	PyAsnUnitControlUpload_Response_ModClear(m);
	PyAsnStartUnitControl_Request_ModClear(m);
	PyAsnStartUnitControl_Response_ModClear(m);
	PyAsnStartUnitControl_Error_ModClear(m);
	PyAsnStopUnitControl_Request_ModClear(m);
	PyAsnStopUnitControl_Response_ModClear(m);
	PyAsnStopUnitControl_Error_ModClear(m);
	PyAsnCreateUnitControl_Request_ModClear(m);
	PyAsnCreateUnitControl_Response_ModClear(m);
	PyAsnAddToUnitControl_Request_ModClear(m);
	PyAsnAddToUnitControl_Response_ModClear(m);
	PyAsnRemoveFromUnitControl_Request_ModClear(m);
	PyAsnRemoveFromUnitControl_Response_ModClear(m);
	PyAsnGetUnitControlAttributes_Request_ModClear(m);
	PyAsnGetUnitControlAttributes_Response_ModClear(m);
	PyAsnLoadUnitControlFromFile_Request_ModClear(m);
	PyAsnLoadUnitControlFromFile_Response_ModClear(m);
	PyAsnLoadUnitControlFromFile_Error_ModClear(m);
	PyAsnStoreUnitControlToFile_Request_ModClear(m);
	PyAsnStoreUnitControlToFile_Response_ModClear(m);
	PyAsnDeleteUnitControl_Request_ModClear(m);
	PyAsnDeleteUnitControl_Response_ModClear(m);
	PyAsnDeleteUnitControl_Error_ModClear(m);
	PyAsnTypeSpecification_ModClear(m);
	PyAsnAlternateAccess_ModClear(m);
	PyAsnAlternateAccessSelection_ModClear(m);
	PyAsnAccessResult_ModClear(m);
	PyAsnData_ModClear(m);
	PyAsnUtcTime_ModClear(m);
	PyAsnFloatingPoint_ModClear(m);
	PyAsnDataAccessError_ModClear(m);
	PyAsnVariableAccessSpecification_ModClear(m);
	PyAsnVariableSpecification_ModClear(m);
	PyAsnRead_Request_ModClear(m);
	PyAsnRead_Response_ModClear(m);
	PyAsnWrite_Response_ModClear(m);
	PyAsnWrite_Request_ModClear(m);
	PyAsnInformationReport_ModClear(m);
	PyAsnGetVariableAccessAttributes_Request_ModClear(m);
	PyAsnGetVariableAccessAttributes_Response_ModClear(m);
	PyAsnDefineNamedVariable_Request_ModClear(m);
	PyAsnDefineNamedVariable_Response_ModClear(m);
	PyAsnDeleteVariableAccess_Request_ModClear(m);
	PyAsnDeleteVariableAccess_Response_ModClear(m);
	PyAsnDeleteVariableAccess_Error_ModClear(m);
	PyAsnDefineNamedVariableList_Request_ModClear(m);
	PyAsnDefineNamedVariableList_Response_ModClear(m);
	PyAsnGetNamedVariableListAttributes_Request_ModClear(m);
	PyAsnGetNamedVariableListAttributes_Response_ModClear(m);
	PyAsnDeleteNamedVariableList_Response_ModClear(m);
	PyAsnDeleteNamedVariableList_Request_ModClear(m);
	PyAsnDeleteNamedVariableList_Error_ModClear(m);
	PyAsnDefineNamedType_Request_ModClear(m);
	PyAsnDefineNamedType_Response_ModClear(m);
	PyAsnGetNamedTypeAttributes_Request_ModClear(m);
	PyAsnGetNamedTypeAttributes_Response_ModClear(m);
	PyAsnDeleteNamedType_Request_ModClear(m);
	PyAsnDeleteNamedType_Response_ModClear(m);
	PyAsnDeleteNamedType_Error_ModClear(m);
	PyAsnExchangeData_Request_ModClear(m);
	PyAsnExchangeData_Response_ModClear(m);
	PyAsnGetDataExchangeAttributes_Request_ModClear(m);
	PyAsnGetDataExchangeAttributes_Response_ModClear(m);
	PyAsnTakeControl_Request_ModClear(m);
	PyAsnTakeControl_Response_ModClear(m);
	PyAsnRelinquishControl_Request_ModClear(m);
	PyAsnRelinquishControl_Response_ModClear(m);
	PyAsnDefineSemaphore_Request_ModClear(m);
	PyAsnDefineSemaphore_Response_ModClear(m);
	PyAsnDeleteSemaphore_Request_ModClear(m);
	PyAsnDeleteSemaphore_Response_ModClear(m);
	PyAsnReportSemaphoreStatus_Request_ModClear(m);
	PyAsnReportSemaphoreStatus_Response_ModClear(m);
	PyAsnReportPoolSemaphoreStatus_Request_ModClear(m);
	PyAsnReportPoolSemaphoreStatus_Response_ModClear(m);
	PyAsnReportSemaphoreEntryStatus_Request_ModClear(m);
	PyAsnReportSemaphoreEntryStatus_Response_ModClear(m);
	PyAsnSemaphoreEntry_ModClear(m);
	PyAsnAttachToSemaphore_ModClear(m);
	PyAsnInput_Request_ModClear(m);
	PyAsnInput_Response_ModClear(m);
	PyAsnOutput_Request_ModClear(m);
	PyAsnOutput_Response_ModClear(m);
	PyAsnTriggerEvent_Request_ModClear(m);
	PyAsnTriggerEvent_Response_ModClear(m);
	PyAsnEventNotification_ModClear(m);
	PyAsnCS_EventNotification_ModClear(m);
	PyAsnAcknowledgeEventNotification_Request_ModClear(m);
	PyAsnAcknowledgeEventNotification_Response_ModClear(m);
	PyAsnGetAlarmSummary_Request_ModClear(m);
	PyAsnGetAlarmSummary_Response_ModClear(m);
	PyAsnAlarmSummary_ModClear(m);
	PyAsnEN_Additional_Detail_ModClear(m);
	PyAsnGetAlarmEnrollmentSummary_Request_ModClear(m);
	PyAsnGetAlarmEnrollmentSummary_Response_ModClear(m);
	PyAsnAlarmEnrollmentSummary_ModClear(m);
	PyAsnAttachToEventCondition_ModClear(m);
	PyAsnDefineEventCondition_Request_ModClear(m);
	PyAsnDefineEventCondition_Response_ModClear(m);
	PyAsnCS_DefineEventCondition_Request_ModClear(m);
	PyAsnDeleteEventCondition_Request_ModClear(m);
	PyAsnDeleteEventCondition_Response_ModClear(m);
	PyAsnGetEventConditionAttributes_Request_ModClear(m);
	PyAsnGetEventConditionAttributes_Response_ModClear(m);
	PyAsnCS_GetEventConditionAttributes_Response_ModClear(m);
	PyAsnReportEventConditionStatus_Request_ModClear(m);
	PyAsnReportEventConditionStatus_Response_ModClear(m);
	PyAsnAlterEventConditionMonitoring_Request_ModClear(m);
	PyAsnAlterEventConditionMonitoring_Response_ModClear(m);
	PyAsnCS_AlterEventConditionMonitoring_Request_ModClear(m);
	PyAsnDefineEventAction_Request_ModClear(m);
	PyAsnDefineEventAction_Response_ModClear(m);
	PyAsnDeleteEventAction_Request_ModClear(m);
	PyAsnDeleteEventAction_Response_ModClear(m);
	PyAsnGetEventActionAttributes_Request_ModClear(m);
	PyAsnGetEventActionAttributes_Response_ModClear(m);
	PyAsnReportEventActionStatus_Request_ModClear(m);
	PyAsnReportEventActionStatus_Response_ModClear(m);
	PyAsnDefineEventEnrollment_Request_ModClear(m);
	PyAsnDefineEventEnrollment_Response_ModClear(m);
	PyAsnDefineEventEnrollment_Error_ModClear(m);
	PyAsnCS_DefineEventEnrollment_Request_ModClear(m);
	PyAsnDeleteEventEnrollment_Request_ModClear(m);
	PyAsnDeleteEventEnrollment_Response_ModClear(m);
	PyAsnGetEventEnrollmentAttributes_Request_ModClear(m);
	PyAsnGetEventEnrollmentAttributes_Response_ModClear(m);
	PyAsnEEAttributes_ModClear(m);
	PyAsnReportEventEnrollmentStatus_Request_ModClear(m);
	PyAsnReportEventEnrollmentStatus_Response_ModClear(m);
	PyAsnAlterEventEnrollment_Request_ModClear(m);
	PyAsnAlterEventEnrollment_Response_ModClear(m);
	PyAsnCS_AlterEventEnrollment_Request_ModClear(m);
	PyAsnEE_State_ModClear(m);
	PyAsnDefineEventConditionList_Request_ModClear(m);
	PyAsnDefineEventConditionList_Response_ModClear(m);
	PyAsnDefineEventConditionList_Error_ModClear(m);
	PyAsnDeleteEventConditionList_Request_ModClear(m);
	PyAsnDeleteEventConditionList_Response_ModClear(m);
	PyAsnAddEventConditionListReference_Request_ModClear(m);
	PyAsnAddEventConditionListReference_Response_ModClear(m);
	PyAsnAddEventConditionListReference_Error_ModClear(m);
	PyAsnRemoveEventConditionListReference_Request_ModClear(m);
	PyAsnRemoveEventConditionListReference_Response_ModClear(m);
	PyAsnRemoveEventConditionListReference_Error_ModClear(m);
	PyAsnGetEventConditionListAttributes_Request_ModClear(m);
	PyAsnGetEventConditionListAttributes_Response_ModClear(m);
	PyAsnReportEventConditionListStatus_Request_ModClear(m);
	PyAsnReportEventConditionListStatus_Response_ModClear(m);
	PyAsnEventConditionStatus_ModClear(m);
	PyAsnAlterEventConditionListMonitoring_Request_ModClear(m);
	PyAsnAlterEventConditionListMonitoring_Response_ModClear(m);
	PyAsnReadJournal_Request_ModClear(m);
	PyAsnReadJournal_Response_ModClear(m);
	PyAsnJournalEntry_ModClear(m);
	PyAsnWriteJournal_Request_ModClear(m);
	PyAsnWriteJournal_Response_ModClear(m);
	PyAsnInitializeJournal_Request_ModClear(m);
	PyAsnInitializeJournal_Response_ModClear(m);
	PyAsnReportJournalStatus_Request_ModClear(m);
	PyAsnReportJournalStatus_Response_ModClear(m);
	PyAsnCreateJournal_Request_ModClear(m);
	PyAsnCreateJournal_Response_ModClear(m);
	PyAsnDeleteJournal_Request_ModClear(m);
	PyAsnDeleteJournal_Response_ModClear(m);
	PyAsnEntryContent_ModClear(m);
	PyAsnApplicationReference_ModClear(m);
	PyAsnObtainFile_Request_ModClear(m);
	PyAsnObtainFile_Response_ModClear(m);
	PyAsnObtainFile_Error_ModClear(m);
	PyAsnFileOpen_Request_ModClear(m);
	PyAsnFileOpen_Response_ModClear(m);
	PyAsnFileRead_Request_ModClear(m);
	PyAsnFileRead_Response_ModClear(m);
	PyAsnFileRename_Request_ModClear(m);
	PyAsnFileRename_Response_ModClear(m);
	PyAsnFileRename_Error_ModClear(m);
	PyAsnFileDelete_Request_ModClear(m);
	PyAsnFileDelete_Response_ModClear(m);
	PyAsnFileClose_Request_ModClear(m);
	PyAsnFileClose_Response_ModClear(m);
	PyAsnFileDirectory_Request_ModClear(m);
	PyAsnFileDirectory_Response_ModClear(m);
	PyAsnDirectoryEntry_ModClear(m);
	PyAsnFileAttributes_ModClear(m);
	PyAsnScatteredAccessDescription_ModClear(m);
	PyAsnDefineScatteredAccess_Request_ModClear(m);
	PyAsnDefineScatteredAccess_Response_ModClear(m);
	PyAsnGetScatteredAccessAttributes_Request_ModClear(m);
	PyAsnGetScatteredAccessAttributes_Response_ModClear(m);
	PyAsnModifier_ModClear(m);
	PyAsnModifierStep_ModClear(m);
	PyAsnServiceSupportOptions_ModClear(m);
	PyAsnParameterSupportOptions_ModClear(m);
	PyAsnAdditionalSupportOptions_ModClear(m);
	PyAsnAdditionalCBBOptions_ModClear(m);
	PyAsnAccessCondition_ModClear(m);
	PyAsnDomainState_ModClear(m);
	PyAsnProgramInvocationState_ModClear(m);
	PyAsnTypeDescription_ModClear(m);
	PyAsnAddress_ModClear(m);
	PyAsnPriority_ModClear(m);
	PyAsnSeverity_ModClear(m);
	PyAsnEventTime_ModClear(m);
	PyAsnEC_State_ModClear(m);
	PyAsnAlarmAckRule_ModClear(m);
	PyAsnTransitions_ModClear(m);
	PyAsnEC_Class_ModClear(m);
	PyAsnEE_Class_ModClear(m);
	PyAsnEE_Duration_ModClear(m);
	PyAsnJournal_Variable_ModClear(m);
	PyAsnName_ModClear(m);
	PyAsnDomainName_ModClear(m);
	PyAsnRDNSequence_ModClear(m);
	PyAsnRelativeDistinguishedName_ModClear(m);
	PyAsnAttributeTypeAndValue_ModClear(m);
	PyAsnACSE_apdu_ModClear(m);
	PyAsnAARQ_apdu_ModClear(m);
	PyAsnAARE_apdu_ModClear(m);
	PyAsnRLRQ_apdu_ModClear(m);
	PyAsnRLRE_apdu_ModClear(m);
	PyAsnABRT_apdu_ModClear(m);
	PyAsnABRT_diagnostic_ModClear(m);
	PyAsnABRT_source_ModClear(m);
	PyAsnACSE_requirements_ModClear(m);
	PyAsnApplication_context_name_list_ModClear(m);
	PyAsnApplication_context_name_ModClear(m);
	PyAsnAP_title_ModClear(m);
	PyAsnAE_qualifier_ModClear(m);
	PyAsnAP_title_form1_ModClear(m);
	PyAsnAE_qualifier_form1_ModClear(m);
	PyAsnAP_title_form2_ModClear(m);
	PyAsnAE_qualifier_form2_ModClear(m);
	PyAsnAE_title_ModClear(m);
	PyAsnAE_title_form1_ModClear(m);
	PyAsnAE_title_form2_ModClear(m);
	PyAsnAE_invocation_identifier_ModClear(m);
	PyAsnAP_invocation_identifier_ModClear(m);
	PyAsnAssociate_result_ModClear(m);
	PyAsnAssociate_source_diagnostic_ModClear(m);
	PyAsnAssociation_information_ModClear(m);
	PyAsnAuthentication_value_ModClear(m);
	PyAsnImplementation_data_ModClear(m);
	PyAsnMechanism_name_ModClear(m);
	PyAsnRelease_request_reason_ModClear(m);
	PyAsnRelease_response_reason_ModClear(m);
	PyAsnEXTERNAL_ModClear(m);
	PyCompat_Clear();
);

/* Module Type */
PY_IMPL_MODULE_DEF(_mms);

/* Module Init */
PY_IMPL_MODULE_INIT_BEGIN(_mms)
	if (PyAsnEMBEDDED_PDV_ModSetupTypes() < 0) return NULL;
	if (PyAsnTimeOfDay_ModSetupTypes() < 0) return NULL;
	if (PyAsnIdentifier_ModSetupTypes() < 0) return NULL;
	if (PyAsnInteger8_ModSetupTypes() < 0) return NULL;
	if (PyAsnInteger16_ModSetupTypes() < 0) return NULL;
	if (PyAsnInteger32_ModSetupTypes() < 0) return NULL;
	if (PyAsnUnsigned8_ModSetupTypes() < 0) return NULL;
	if (PyAsnUnsigned16_ModSetupTypes() < 0) return NULL;
	if (PyAsnUnsigned32_ModSetupTypes() < 0) return NULL;
	if (PyAsnObjectName_ModSetupTypes() < 0) return NULL;
	if (PyAsnObjectClass_ModSetupTypes() < 0) return NULL;
	if (PyAsnMMSString_ModSetupTypes() < 0) return NULL;
	if (PyAsnMMS255String_ModSetupTypes() < 0) return NULL;
	if (PyAsnFileName_ModSetupTypes() < 0) return NULL;
	if (PyAsnMMSpdu_ModSetupTypes() < 0) return NULL;
	if (PyAsnConfirmed_RequestPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnConfirmed_ErrorPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnConfirmedServiceRequest_ModSetupTypes() < 0) return NULL;
	if (PyAsnAdditionalService_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnRequest_Detail_ModSetupTypes() < 0) return NULL;
	if (PyAsnUnconfirmed_PDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnUnconfirmedService_ModSetupTypes() < 0) return NULL;
	if (PyAsnUnconfirmed_Detail_ModSetupTypes() < 0) return NULL;
	if (PyAsnConfirmed_ResponsePDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnConfirmedServiceResponse_ModSetupTypes() < 0) return NULL;
	if (PyAsnAdditionalService_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnResponse_Detail_ModSetupTypes() < 0) return NULL;
	if (PyAsnServiceError_ModSetupTypes() < 0) return NULL;
	if (PyAsnAdditionalService_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnInitiate_RequestPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnInitiate_ResponsePDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnInitiate_ErrorPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnConclude_RequestPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnConclude_ResponsePDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnConclude_ErrorPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnCancel_RequestPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnCancel_ResponsePDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnCancel_ErrorPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnRejectPDU_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineAccessControlList_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineAccessControlList_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetAccessControlListAttributes_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetAccessControlListAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportAccessControlledObjects_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportAccessControlledObjects_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteAccessControlList_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteAccessControlList_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnChangeAccessControl_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnChangeAccessControl_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnChangeAccessControl_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnStatusResponse_ModSetupTypes() < 0) return NULL;
	if (PyAsnCS_Status_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnOperationState_ModSetupTypes() < 0) return NULL;
	if (PyAsnExtendedStatus_ModSetupTypes() < 0) return NULL;
	if (PyAsnStatus_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnStatus_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnUnsolicitedStatus_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetNameList_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetNameList_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnIdentify_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnIdentify_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnRename_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnRename_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetCapabilityList_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetCapabilityList_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnVMDStop_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnVMDStop_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnVMDReset_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnVMDReset_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnInitiateDownloadSequence_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnInitiateDownloadSequence_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDownloadSegment_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDownloadSegment_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnLoadData_ModSetupTypes() < 0) return NULL;
	if (PyAsnTerminateDownloadSequence_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnTerminateDownloadSequence_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnInitiateUploadSequence_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnInitiateUploadSequence_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnUploadSegment_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnUploadSegment_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnTerminateUploadSequence_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnTerminateUploadSequence_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnRequestDomainDownload_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnRequestDomainDownload_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnRequestDomainUpload_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnRequestDomainUpload_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnLoadDomainContent_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnLoadDomainContent_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnStoreDomainContent_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnStoreDomainContent_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteDomain_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteDomain_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetDomainAttributes_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetDomainAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnCreateProgramInvocation_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnCreateProgramInvocation_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnCS_CreateProgramInvocation_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteProgramInvocation_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteProgramInvocation_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnStart_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnStart_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnStart_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnCS_Start_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnStartCount_ModSetupTypes() < 0) return NULL;
	if (PyAsnStop_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnStop_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnStop_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnResume_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnResume_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnResume_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnCS_Resume_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnReset_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnReset_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnReset_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnKill_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnKill_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetProgramInvocationAttributes_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetProgramInvocationAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnCS_GetProgramInvocationAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnSelect_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnSelect_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnAlterProgramInvocationAttributes_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnAlterProgramInvocationAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnControlElement_ModSetupTypes() < 0) return NULL;
	if (PyAsnInitiateUnitControlLoad_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnInitiateUnitControlLoad_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnInitiateUnitControl_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnUnitControlLoadSegment_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnUnitControlLoadSegment_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnUnitControlUpload_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnUnitControlUpload_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnStartUnitControl_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnStartUnitControl_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnStartUnitControl_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnStopUnitControl_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnStopUnitControl_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnStopUnitControl_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnCreateUnitControl_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnCreateUnitControl_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnAddToUnitControl_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnAddToUnitControl_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnRemoveFromUnitControl_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnRemoveFromUnitControl_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetUnitControlAttributes_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetUnitControlAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnLoadUnitControlFromFile_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnLoadUnitControlFromFile_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnLoadUnitControlFromFile_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnStoreUnitControlToFile_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnStoreUnitControlToFile_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteUnitControl_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteUnitControl_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteUnitControl_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnTypeSpecification_ModSetupTypes() < 0) return NULL;
	if (PyAsnAlternateAccess_ModSetupTypes() < 0) return NULL;
	if (PyAsnAlternateAccessSelection_ModSetupTypes() < 0) return NULL;
	if (PyAsnAccessResult_ModSetupTypes() < 0) return NULL;
	if (PyAsnData_ModSetupTypes() < 0) return NULL;
	if (PyAsnUtcTime_ModSetupTypes() < 0) return NULL;
	if (PyAsnFloatingPoint_ModSetupTypes() < 0) return NULL;
	if (PyAsnDataAccessError_ModSetupTypes() < 0) return NULL;
	if (PyAsnVariableAccessSpecification_ModSetupTypes() < 0) return NULL;
	if (PyAsnVariableSpecification_ModSetupTypes() < 0) return NULL;
	if (PyAsnRead_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnRead_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnWrite_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnWrite_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnInformationReport_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetVariableAccessAttributes_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetVariableAccessAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineNamedVariable_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineNamedVariable_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteVariableAccess_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteVariableAccess_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteVariableAccess_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineNamedVariableList_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineNamedVariableList_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetNamedVariableListAttributes_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetNamedVariableListAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteNamedVariableList_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteNamedVariableList_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteNamedVariableList_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineNamedType_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineNamedType_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetNamedTypeAttributes_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetNamedTypeAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteNamedType_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteNamedType_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteNamedType_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnExchangeData_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnExchangeData_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetDataExchangeAttributes_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetDataExchangeAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnTakeControl_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnTakeControl_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnRelinquishControl_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnRelinquishControl_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineSemaphore_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineSemaphore_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteSemaphore_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteSemaphore_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportSemaphoreStatus_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportSemaphoreStatus_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportPoolSemaphoreStatus_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportPoolSemaphoreStatus_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportSemaphoreEntryStatus_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportSemaphoreEntryStatus_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnSemaphoreEntry_ModSetupTypes() < 0) return NULL;
	if (PyAsnAttachToSemaphore_ModSetupTypes() < 0) return NULL;
	if (PyAsnInput_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnInput_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnOutput_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnOutput_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnTriggerEvent_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnTriggerEvent_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnEventNotification_ModSetupTypes() < 0) return NULL;
	if (PyAsnCS_EventNotification_ModSetupTypes() < 0) return NULL;
	if (PyAsnAcknowledgeEventNotification_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnAcknowledgeEventNotification_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetAlarmSummary_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetAlarmSummary_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnAlarmSummary_ModSetupTypes() < 0) return NULL;
	if (PyAsnEN_Additional_Detail_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetAlarmEnrollmentSummary_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetAlarmEnrollmentSummary_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnAlarmEnrollmentSummary_ModSetupTypes() < 0) return NULL;
	if (PyAsnAttachToEventCondition_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineEventCondition_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineEventCondition_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnCS_DefineEventCondition_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteEventCondition_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteEventCondition_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetEventConditionAttributes_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetEventConditionAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnCS_GetEventConditionAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportEventConditionStatus_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportEventConditionStatus_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnAlterEventConditionMonitoring_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnAlterEventConditionMonitoring_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnCS_AlterEventConditionMonitoring_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineEventAction_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineEventAction_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteEventAction_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteEventAction_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetEventActionAttributes_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetEventActionAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportEventActionStatus_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportEventActionStatus_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineEventEnrollment_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineEventEnrollment_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineEventEnrollment_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnCS_DefineEventEnrollment_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteEventEnrollment_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteEventEnrollment_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetEventEnrollmentAttributes_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetEventEnrollmentAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnEEAttributes_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportEventEnrollmentStatus_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportEventEnrollmentStatus_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnAlterEventEnrollment_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnAlterEventEnrollment_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnCS_AlterEventEnrollment_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnEE_State_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineEventConditionList_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineEventConditionList_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineEventConditionList_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteEventConditionList_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteEventConditionList_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnAddEventConditionListReference_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnAddEventConditionListReference_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnAddEventConditionListReference_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnRemoveEventConditionListReference_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnRemoveEventConditionListReference_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnRemoveEventConditionListReference_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetEventConditionListAttributes_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetEventConditionListAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportEventConditionListStatus_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportEventConditionListStatus_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnEventConditionStatus_ModSetupTypes() < 0) return NULL;
	if (PyAsnAlterEventConditionListMonitoring_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnAlterEventConditionListMonitoring_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnReadJournal_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnReadJournal_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnJournalEntry_ModSetupTypes() < 0) return NULL;
	if (PyAsnWriteJournal_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnWriteJournal_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnInitializeJournal_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnInitializeJournal_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportJournalStatus_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnReportJournalStatus_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnCreateJournal_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnCreateJournal_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteJournal_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDeleteJournal_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnEntryContent_ModSetupTypes() < 0) return NULL;
	if (PyAsnApplicationReference_ModSetupTypes() < 0) return NULL;
	if (PyAsnObtainFile_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnObtainFile_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnObtainFile_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnFileOpen_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnFileOpen_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnFileRead_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnFileRead_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnFileRename_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnFileRename_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnFileRename_Error_ModSetupTypes() < 0) return NULL;
	if (PyAsnFileDelete_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnFileDelete_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnFileClose_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnFileClose_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnFileDirectory_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnFileDirectory_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnDirectoryEntry_ModSetupTypes() < 0) return NULL;
	if (PyAsnFileAttributes_ModSetupTypes() < 0) return NULL;
	if (PyAsnScatteredAccessDescription_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineScatteredAccess_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnDefineScatteredAccess_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetScatteredAccessAttributes_Request_ModSetupTypes() < 0) return NULL;
	if (PyAsnGetScatteredAccessAttributes_Response_ModSetupTypes() < 0) return NULL;
	if (PyAsnModifier_ModSetupTypes() < 0) return NULL;
	if (PyAsnModifierStep_ModSetupTypes() < 0) return NULL;
	if (PyAsnServiceSupportOptions_ModSetupTypes() < 0) return NULL;
	if (PyAsnParameterSupportOptions_ModSetupTypes() < 0) return NULL;
	if (PyAsnAdditionalSupportOptions_ModSetupTypes() < 0) return NULL;
	if (PyAsnAdditionalCBBOptions_ModSetupTypes() < 0) return NULL;
	if (PyAsnAccessCondition_ModSetupTypes() < 0) return NULL;
	if (PyAsnDomainState_ModSetupTypes() < 0) return NULL;
	if (PyAsnProgramInvocationState_ModSetupTypes() < 0) return NULL;
	if (PyAsnTypeDescription_ModSetupTypes() < 0) return NULL;
	if (PyAsnAddress_ModSetupTypes() < 0) return NULL;
	if (PyAsnPriority_ModSetupTypes() < 0) return NULL;
	if (PyAsnSeverity_ModSetupTypes() < 0) return NULL;
	if (PyAsnEventTime_ModSetupTypes() < 0) return NULL;
	if (PyAsnEC_State_ModSetupTypes() < 0) return NULL;
	if (PyAsnAlarmAckRule_ModSetupTypes() < 0) return NULL;
	if (PyAsnTransitions_ModSetupTypes() < 0) return NULL;
	if (PyAsnEC_Class_ModSetupTypes() < 0) return NULL;
	if (PyAsnEE_Class_ModSetupTypes() < 0) return NULL;
	if (PyAsnEE_Duration_ModSetupTypes() < 0) return NULL;
	if (PyAsnJournal_Variable_ModSetupTypes() < 0) return NULL;
	if (PyAsnName_ModSetupTypes() < 0) return NULL;
	if (PyAsnDomainName_ModSetupTypes() < 0) return NULL;
	if (PyAsnRDNSequence_ModSetupTypes() < 0) return NULL;
	if (PyAsnRelativeDistinguishedName_ModSetupTypes() < 0) return NULL;
	if (PyAsnAttributeTypeAndValue_ModSetupTypes() < 0) return NULL;
	if (PyAsnACSE_apdu_ModSetupTypes() < 0) return NULL;
	if (PyAsnAARQ_apdu_ModSetupTypes() < 0) return NULL;
	if (PyAsnAARE_apdu_ModSetupTypes() < 0) return NULL;
	if (PyAsnRLRQ_apdu_ModSetupTypes() < 0) return NULL;
	if (PyAsnRLRE_apdu_ModSetupTypes() < 0) return NULL;
	if (PyAsnABRT_apdu_ModSetupTypes() < 0) return NULL;
	if (PyAsnABRT_diagnostic_ModSetupTypes() < 0) return NULL;
	if (PyAsnABRT_source_ModSetupTypes() < 0) return NULL;
	if (PyAsnACSE_requirements_ModSetupTypes() < 0) return NULL;
	if (PyAsnApplication_context_name_list_ModSetupTypes() < 0) return NULL;
	if (PyAsnApplication_context_name_ModSetupTypes() < 0) return NULL;
	if (PyAsnAP_title_ModSetupTypes() < 0) return NULL;
	if (PyAsnAE_qualifier_ModSetupTypes() < 0) return NULL;
	if (PyAsnAP_title_form1_ModSetupTypes() < 0) return NULL;
	if (PyAsnAE_qualifier_form1_ModSetupTypes() < 0) return NULL;
	if (PyAsnAP_title_form2_ModSetupTypes() < 0) return NULL;
	if (PyAsnAE_qualifier_form2_ModSetupTypes() < 0) return NULL;
	if (PyAsnAE_title_ModSetupTypes() < 0) return NULL;
	if (PyAsnAE_title_form1_ModSetupTypes() < 0) return NULL;
	if (PyAsnAE_title_form2_ModSetupTypes() < 0) return NULL;
	if (PyAsnAE_invocation_identifier_ModSetupTypes() < 0) return NULL;
	if (PyAsnAP_invocation_identifier_ModSetupTypes() < 0) return NULL;
	if (PyAsnAssociate_result_ModSetupTypes() < 0) return NULL;
	if (PyAsnAssociate_source_diagnostic_ModSetupTypes() < 0) return NULL;
	if (PyAsnAssociation_information_ModSetupTypes() < 0) return NULL;
	if (PyAsnAuthentication_value_ModSetupTypes() < 0) return NULL;
	if (PyAsnImplementation_data_ModSetupTypes() < 0) return NULL;
	if (PyAsnMechanism_name_ModSetupTypes() < 0) return NULL;
	if (PyAsnRelease_request_reason_ModSetupTypes() < 0) return NULL;
	if (PyAsnRelease_response_reason_ModSetupTypes() < 0) return NULL;
	if (PyAsnEXTERNAL_ModSetupTypes() < 0) return NULL;

	if((nModule = PyModule_Create(&PyAsnModule__mms)) == NULL) { return NULL; }

	if (PyCompat_Init() < 0) return NULL;
	if (PyAsnEMBEDDED_PDV_ModInit(nModule) < 0) return NULL;
	if (PyAsnTimeOfDay_ModInit(nModule) < 0) return NULL;
	if (PyAsnIdentifier_ModInit(nModule) < 0) return NULL;
	if (PyAsnInteger8_ModInit(nModule) < 0) return NULL;
	if (PyAsnInteger16_ModInit(nModule) < 0) return NULL;
	if (PyAsnInteger32_ModInit(nModule) < 0) return NULL;
	if (PyAsnUnsigned8_ModInit(nModule) < 0) return NULL;
	if (PyAsnUnsigned16_ModInit(nModule) < 0) return NULL;
	if (PyAsnUnsigned32_ModInit(nModule) < 0) return NULL;
	if (PyAsnObjectName_ModInit(nModule) < 0) return NULL;
	if (PyAsnObjectClass_ModInit(nModule) < 0) return NULL;
	if (PyAsnMMSString_ModInit(nModule) < 0) return NULL;
	if (PyAsnMMS255String_ModInit(nModule) < 0) return NULL;
	if (PyAsnFileName_ModInit(nModule) < 0) return NULL;
	if (PyAsnMMSpdu_ModInit(nModule) < 0) return NULL;
	if (PyAsnConfirmed_RequestPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnConfirmed_ErrorPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnConfirmedServiceRequest_ModInit(nModule) < 0) return NULL;
	if (PyAsnAdditionalService_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnRequest_Detail_ModInit(nModule) < 0) return NULL;
	if (PyAsnUnconfirmed_PDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnUnconfirmedService_ModInit(nModule) < 0) return NULL;
	if (PyAsnUnconfirmed_Detail_ModInit(nModule) < 0) return NULL;
	if (PyAsnConfirmed_ResponsePDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnConfirmedServiceResponse_ModInit(nModule) < 0) return NULL;
	if (PyAsnAdditionalService_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnResponse_Detail_ModInit(nModule) < 0) return NULL;
	if (PyAsnServiceError_ModInit(nModule) < 0) return NULL;
	if (PyAsnAdditionalService_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnInitiate_RequestPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnInitiate_ResponsePDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnInitiate_ErrorPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnConclude_RequestPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnConclude_ResponsePDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnConclude_ErrorPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnCancel_RequestPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnCancel_ResponsePDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnCancel_ErrorPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnRejectPDU_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineAccessControlList_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineAccessControlList_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetAccessControlListAttributes_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetAccessControlListAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportAccessControlledObjects_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportAccessControlledObjects_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteAccessControlList_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteAccessControlList_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnChangeAccessControl_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnChangeAccessControl_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnChangeAccessControl_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnStatusResponse_ModInit(nModule) < 0) return NULL;
	if (PyAsnCS_Status_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnOperationState_ModInit(nModule) < 0) return NULL;
	if (PyAsnExtendedStatus_ModInit(nModule) < 0) return NULL;
	if (PyAsnStatus_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnStatus_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnUnsolicitedStatus_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetNameList_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetNameList_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnIdentify_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnIdentify_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnRename_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnRename_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetCapabilityList_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetCapabilityList_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnVMDStop_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnVMDStop_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnVMDReset_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnVMDReset_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnInitiateDownloadSequence_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnInitiateDownloadSequence_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDownloadSegment_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDownloadSegment_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnLoadData_ModInit(nModule) < 0) return NULL;
	if (PyAsnTerminateDownloadSequence_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnTerminateDownloadSequence_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnInitiateUploadSequence_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnInitiateUploadSequence_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnUploadSegment_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnUploadSegment_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnTerminateUploadSequence_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnTerminateUploadSequence_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnRequestDomainDownload_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnRequestDomainDownload_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnRequestDomainUpload_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnRequestDomainUpload_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnLoadDomainContent_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnLoadDomainContent_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnStoreDomainContent_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnStoreDomainContent_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteDomain_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteDomain_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetDomainAttributes_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetDomainAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnCreateProgramInvocation_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnCreateProgramInvocation_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnCS_CreateProgramInvocation_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteProgramInvocation_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteProgramInvocation_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnStart_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnStart_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnStart_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnCS_Start_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnStartCount_ModInit(nModule) < 0) return NULL;
	if (PyAsnStop_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnStop_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnStop_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnResume_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnResume_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnResume_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnCS_Resume_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnReset_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnReset_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnReset_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnKill_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnKill_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetProgramInvocationAttributes_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetProgramInvocationAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnCS_GetProgramInvocationAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnSelect_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnSelect_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnAlterProgramInvocationAttributes_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnAlterProgramInvocationAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnControlElement_ModInit(nModule) < 0) return NULL;
	if (PyAsnInitiateUnitControlLoad_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnInitiateUnitControlLoad_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnInitiateUnitControl_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnUnitControlLoadSegment_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnUnitControlLoadSegment_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnUnitControlUpload_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnUnitControlUpload_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnStartUnitControl_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnStartUnitControl_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnStartUnitControl_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnStopUnitControl_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnStopUnitControl_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnStopUnitControl_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnCreateUnitControl_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnCreateUnitControl_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnAddToUnitControl_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnAddToUnitControl_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnRemoveFromUnitControl_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnRemoveFromUnitControl_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetUnitControlAttributes_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetUnitControlAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnLoadUnitControlFromFile_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnLoadUnitControlFromFile_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnLoadUnitControlFromFile_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnStoreUnitControlToFile_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnStoreUnitControlToFile_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteUnitControl_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteUnitControl_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteUnitControl_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnTypeSpecification_ModInit(nModule) < 0) return NULL;
	if (PyAsnAlternateAccess_ModInit(nModule) < 0) return NULL;
	if (PyAsnAlternateAccessSelection_ModInit(nModule) < 0) return NULL;
	if (PyAsnAccessResult_ModInit(nModule) < 0) return NULL;
	if (PyAsnData_ModInit(nModule) < 0) return NULL;
	if (PyAsnUtcTime_ModInit(nModule) < 0) return NULL;
	if (PyAsnFloatingPoint_ModInit(nModule) < 0) return NULL;
	if (PyAsnDataAccessError_ModInit(nModule) < 0) return NULL;
	if (PyAsnVariableAccessSpecification_ModInit(nModule) < 0) return NULL;
	if (PyAsnVariableSpecification_ModInit(nModule) < 0) return NULL;
	if (PyAsnRead_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnRead_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnWrite_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnWrite_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnInformationReport_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetVariableAccessAttributes_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetVariableAccessAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineNamedVariable_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineNamedVariable_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteVariableAccess_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteVariableAccess_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteVariableAccess_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineNamedVariableList_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineNamedVariableList_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetNamedVariableListAttributes_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetNamedVariableListAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteNamedVariableList_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteNamedVariableList_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteNamedVariableList_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineNamedType_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineNamedType_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetNamedTypeAttributes_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetNamedTypeAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteNamedType_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteNamedType_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteNamedType_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnExchangeData_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnExchangeData_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetDataExchangeAttributes_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetDataExchangeAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnTakeControl_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnTakeControl_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnRelinquishControl_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnRelinquishControl_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineSemaphore_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineSemaphore_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteSemaphore_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteSemaphore_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportSemaphoreStatus_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportSemaphoreStatus_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportPoolSemaphoreStatus_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportPoolSemaphoreStatus_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportSemaphoreEntryStatus_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportSemaphoreEntryStatus_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnSemaphoreEntry_ModInit(nModule) < 0) return NULL;
	if (PyAsnAttachToSemaphore_ModInit(nModule) < 0) return NULL;
	if (PyAsnInput_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnInput_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnOutput_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnOutput_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnTriggerEvent_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnTriggerEvent_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnEventNotification_ModInit(nModule) < 0) return NULL;
	if (PyAsnCS_EventNotification_ModInit(nModule) < 0) return NULL;
	if (PyAsnAcknowledgeEventNotification_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnAcknowledgeEventNotification_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetAlarmSummary_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetAlarmSummary_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnAlarmSummary_ModInit(nModule) < 0) return NULL;
	if (PyAsnEN_Additional_Detail_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetAlarmEnrollmentSummary_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetAlarmEnrollmentSummary_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnAlarmEnrollmentSummary_ModInit(nModule) < 0) return NULL;
	if (PyAsnAttachToEventCondition_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineEventCondition_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineEventCondition_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnCS_DefineEventCondition_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteEventCondition_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteEventCondition_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetEventConditionAttributes_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetEventConditionAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnCS_GetEventConditionAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportEventConditionStatus_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportEventConditionStatus_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnAlterEventConditionMonitoring_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnAlterEventConditionMonitoring_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnCS_AlterEventConditionMonitoring_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineEventAction_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineEventAction_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteEventAction_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteEventAction_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetEventActionAttributes_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetEventActionAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportEventActionStatus_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportEventActionStatus_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineEventEnrollment_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineEventEnrollment_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineEventEnrollment_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnCS_DefineEventEnrollment_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteEventEnrollment_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteEventEnrollment_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetEventEnrollmentAttributes_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetEventEnrollmentAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnEEAttributes_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportEventEnrollmentStatus_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportEventEnrollmentStatus_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnAlterEventEnrollment_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnAlterEventEnrollment_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnCS_AlterEventEnrollment_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnEE_State_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineEventConditionList_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineEventConditionList_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineEventConditionList_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteEventConditionList_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteEventConditionList_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnAddEventConditionListReference_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnAddEventConditionListReference_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnAddEventConditionListReference_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnRemoveEventConditionListReference_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnRemoveEventConditionListReference_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnRemoveEventConditionListReference_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetEventConditionListAttributes_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetEventConditionListAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportEventConditionListStatus_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportEventConditionListStatus_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnEventConditionStatus_ModInit(nModule) < 0) return NULL;
	if (PyAsnAlterEventConditionListMonitoring_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnAlterEventConditionListMonitoring_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnReadJournal_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnReadJournal_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnJournalEntry_ModInit(nModule) < 0) return NULL;
	if (PyAsnWriteJournal_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnWriteJournal_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnInitializeJournal_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnInitializeJournal_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportJournalStatus_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnReportJournalStatus_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnCreateJournal_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnCreateJournal_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteJournal_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDeleteJournal_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnEntryContent_ModInit(nModule) < 0) return NULL;
	if (PyAsnApplicationReference_ModInit(nModule) < 0) return NULL;
	if (PyAsnObtainFile_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnObtainFile_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnObtainFile_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnFileOpen_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnFileOpen_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnFileRead_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnFileRead_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnFileRename_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnFileRename_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnFileRename_Error_ModInit(nModule) < 0) return NULL;
	if (PyAsnFileDelete_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnFileDelete_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnFileClose_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnFileClose_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnFileDirectory_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnFileDirectory_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnDirectoryEntry_ModInit(nModule) < 0) return NULL;
	if (PyAsnFileAttributes_ModInit(nModule) < 0) return NULL;
	if (PyAsnScatteredAccessDescription_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineScatteredAccess_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnDefineScatteredAccess_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetScatteredAccessAttributes_Request_ModInit(nModule) < 0) return NULL;
	if (PyAsnGetScatteredAccessAttributes_Response_ModInit(nModule) < 0) return NULL;
	if (PyAsnModifier_ModInit(nModule) < 0) return NULL;
	if (PyAsnModifierStep_ModInit(nModule) < 0) return NULL;
	if (PyAsnServiceSupportOptions_ModInit(nModule) < 0) return NULL;
	if (PyAsnParameterSupportOptions_ModInit(nModule) < 0) return NULL;
	if (PyAsnAdditionalSupportOptions_ModInit(nModule) < 0) return NULL;
	if (PyAsnAdditionalCBBOptions_ModInit(nModule) < 0) return NULL;
	if (PyAsnAccessCondition_ModInit(nModule) < 0) return NULL;
	if (PyAsnDomainState_ModInit(nModule) < 0) return NULL;
	if (PyAsnProgramInvocationState_ModInit(nModule) < 0) return NULL;
	if (PyAsnTypeDescription_ModInit(nModule) < 0) return NULL;
	if (PyAsnAddress_ModInit(nModule) < 0) return NULL;
	if (PyAsnPriority_ModInit(nModule) < 0) return NULL;
	if (PyAsnSeverity_ModInit(nModule) < 0) return NULL;
	if (PyAsnEventTime_ModInit(nModule) < 0) return NULL;
	if (PyAsnEC_State_ModInit(nModule) < 0) return NULL;
	if (PyAsnAlarmAckRule_ModInit(nModule) < 0) return NULL;
	if (PyAsnTransitions_ModInit(nModule) < 0) return NULL;
	if (PyAsnEC_Class_ModInit(nModule) < 0) return NULL;
	if (PyAsnEE_Class_ModInit(nModule) < 0) return NULL;
	if (PyAsnEE_Duration_ModInit(nModule) < 0) return NULL;
	if (PyAsnJournal_Variable_ModInit(nModule) < 0) return NULL;
	if (PyAsnName_ModInit(nModule) < 0) return NULL;
	if (PyAsnDomainName_ModInit(nModule) < 0) return NULL;
	if (PyAsnRDNSequence_ModInit(nModule) < 0) return NULL;
	if (PyAsnRelativeDistinguishedName_ModInit(nModule) < 0) return NULL;
	if (PyAsnAttributeTypeAndValue_ModInit(nModule) < 0) return NULL;
	if (PyAsnACSE_apdu_ModInit(nModule) < 0) return NULL;
	if (PyAsnAARQ_apdu_ModInit(nModule) < 0) return NULL;
	if (PyAsnAARE_apdu_ModInit(nModule) < 0) return NULL;
	if (PyAsnRLRQ_apdu_ModInit(nModule) < 0) return NULL;
	if (PyAsnRLRE_apdu_ModInit(nModule) < 0) return NULL;
	if (PyAsnABRT_apdu_ModInit(nModule) < 0) return NULL;
	if (PyAsnABRT_diagnostic_ModInit(nModule) < 0) return NULL;
	if (PyAsnABRT_source_ModInit(nModule) < 0) return NULL;
	if (PyAsnACSE_requirements_ModInit(nModule) < 0) return NULL;
	if (PyAsnApplication_context_name_list_ModInit(nModule) < 0) return NULL;
	if (PyAsnApplication_context_name_ModInit(nModule) < 0) return NULL;
	if (PyAsnAP_title_ModInit(nModule) < 0) return NULL;
	if (PyAsnAE_qualifier_ModInit(nModule) < 0) return NULL;
	if (PyAsnAP_title_form1_ModInit(nModule) < 0) return NULL;
	if (PyAsnAE_qualifier_form1_ModInit(nModule) < 0) return NULL;
	if (PyAsnAP_title_form2_ModInit(nModule) < 0) return NULL;
	if (PyAsnAE_qualifier_form2_ModInit(nModule) < 0) return NULL;
	if (PyAsnAE_title_ModInit(nModule) < 0) return NULL;
	if (PyAsnAE_title_form1_ModInit(nModule) < 0) return NULL;
	if (PyAsnAE_title_form2_ModInit(nModule) < 0) return NULL;
	if (PyAsnAE_invocation_identifier_ModInit(nModule) < 0) return NULL;
	if (PyAsnAP_invocation_identifier_ModInit(nModule) < 0) return NULL;
	if (PyAsnAssociate_result_ModInit(nModule) < 0) return NULL;
	if (PyAsnAssociate_source_diagnostic_ModInit(nModule) < 0) return NULL;
	if (PyAsnAssociation_information_ModInit(nModule) < 0) return NULL;
	if (PyAsnAuthentication_value_ModInit(nModule) < 0) return NULL;
	if (PyAsnImplementation_data_ModInit(nModule) < 0) return NULL;
	if (PyAsnMechanism_name_ModInit(nModule) < 0) return NULL;
	if (PyAsnRelease_request_reason_ModInit(nModule) < 0) return NULL;
	if (PyAsnRelease_response_reason_ModInit(nModule) < 0) return NULL;
	if (PyAsnEXTERNAL_ModInit(nModule) < 0) return NULL;
PY_IMPL_MODULE_INIT_END;
