/*
 * Generated by asn1c-v0.9.27-1413-ge0c0052e-dirty for Python bindings (https://github.com/MatrixEditor/asn1c-bindings)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <ServiceError_Py.h>

/* class implementation */
PyObject *PyAsnEnumServiceError_errorClass_ANON_2_vmd_state_Type = NULL;
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_errorClass_ANON_2, ServiceError__errorClass, vmd_state, vmd_state,PyCompatEnum_FromObject(value, (void *)&dst->choice.vmd_state, 0));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_errorClass_ANON_2, vmd_state, PyCompatEnum_AsObject(PyAsnEnumServiceError_errorClass_ANON_2_vmd_state_Type, (void *)&src->choice.vmd_state, 0));
PY_IMPL_CHOICE_GETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, vmd_state, vmd_state);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, vmd_state, vmd_state, *asn_DEF_ServiceError.elements[0].type);
PyObject *PyAsnEnumServiceError_errorClass_ANON_2_application_reference_Type = NULL;
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_errorClass_ANON_2, ServiceError__errorClass, application_reference, application_reference,PyCompatEnum_FromObject(value, (void *)&dst->choice.application_reference, 0));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_errorClass_ANON_2, application_reference, PyCompatEnum_AsObject(PyAsnEnumServiceError_errorClass_ANON_2_application_reference_Type, (void *)&src->choice.application_reference, 0));
PY_IMPL_CHOICE_GETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, application_reference, application_reference);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, application_reference, application_reference, *asn_DEF_ServiceError.elements[0].type);
PyObject *PyAsnEnumServiceError_errorClass_ANON_2_definition_Type = NULL;
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_errorClass_ANON_2, ServiceError__errorClass, definition, definition,PyCompatEnum_FromObject(value, (void *)&dst->choice.definition, 0));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_errorClass_ANON_2, definition, PyCompatEnum_AsObject(PyAsnEnumServiceError_errorClass_ANON_2_definition_Type, (void *)&src->choice.definition, 0));
PY_IMPL_CHOICE_GETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, definition, definition);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, definition, definition, *asn_DEF_ServiceError.elements[0].type);
PyObject *PyAsnEnumServiceError_errorClass_ANON_2_resource_Type = NULL;
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_errorClass_ANON_2, ServiceError__errorClass, resource, resource,PyCompatEnum_FromObject(value, (void *)&dst->choice.resource, 0));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_errorClass_ANON_2, resource, PyCompatEnum_AsObject(PyAsnEnumServiceError_errorClass_ANON_2_resource_Type, (void *)&src->choice.resource, 0));
PY_IMPL_CHOICE_GETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, resource, resource);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, resource, resource, *asn_DEF_ServiceError.elements[0].type);
PyObject *PyAsnEnumServiceError_errorClass_ANON_2_service_Type = NULL;
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_errorClass_ANON_2, ServiceError__errorClass, service, service,PyCompatEnum_FromObject(value, (void *)&dst->choice.service, 0));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_errorClass_ANON_2, service, PyCompatEnum_AsObject(PyAsnEnumServiceError_errorClass_ANON_2_service_Type, (void *)&src->choice.service, 0));
PY_IMPL_CHOICE_GETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, service, service);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, service, service, *asn_DEF_ServiceError.elements[0].type);
PyObject *PyAsnEnumServiceError_errorClass_ANON_2_service_preempt_Type = NULL;
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_errorClass_ANON_2, ServiceError__errorClass, service_preempt, service_preempt,PyCompatEnum_FromObject(value, (void *)&dst->choice.service_preempt, 0));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_errorClass_ANON_2, service_preempt, PyCompatEnum_AsObject(PyAsnEnumServiceError_errorClass_ANON_2_service_preempt_Type, (void *)&src->choice.service_preempt, 0));
PY_IMPL_CHOICE_GETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, service_preempt, service_preempt);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, service_preempt, service_preempt, *asn_DEF_ServiceError.elements[0].type);
PyObject *PyAsnEnumServiceError_errorClass_ANON_2_time_resolution_Type = NULL;
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_errorClass_ANON_2, ServiceError__errorClass, time_resolution, time_resolution,PyCompatEnum_FromObject(value, (void *)&dst->choice.time_resolution, 0));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_errorClass_ANON_2, time_resolution, PyCompatEnum_AsObject(PyAsnEnumServiceError_errorClass_ANON_2_time_resolution_Type, (void *)&src->choice.time_resolution, 0));
PY_IMPL_CHOICE_GETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, time_resolution, time_resolution);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, time_resolution, time_resolution, *asn_DEF_ServiceError.elements[0].type);
PyObject *PyAsnEnumServiceError_errorClass_ANON_2_access_Type = NULL;
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_errorClass_ANON_2, ServiceError__errorClass, access, access,PyCompatEnum_FromObject(value, (void *)&dst->choice.access, 0));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_errorClass_ANON_2, access, PyCompatEnum_AsObject(PyAsnEnumServiceError_errorClass_ANON_2_access_Type, (void *)&src->choice.access, 0));
PY_IMPL_CHOICE_GETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, access, access);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, access, access, *asn_DEF_ServiceError.elements[0].type);
PyObject *PyAsnEnumServiceError_errorClass_ANON_2_initiate_Type = NULL;
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_errorClass_ANON_2, ServiceError__errorClass, initiate, initiate,PyCompatEnum_FromObject(value, (void *)&dst->choice.initiate, 0));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_errorClass_ANON_2, initiate, PyCompatEnum_AsObject(PyAsnEnumServiceError_errorClass_ANON_2_initiate_Type, (void *)&src->choice.initiate, 0));
PY_IMPL_CHOICE_GETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, initiate, initiate);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, initiate, initiate, *asn_DEF_ServiceError.elements[0].type);
PyObject *PyAsnEnumServiceError_errorClass_ANON_2_conclude_Type = NULL;
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_errorClass_ANON_2, ServiceError__errorClass, conclude, conclude,PyCompatEnum_FromObject(value, (void *)&dst->choice.conclude, 0));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_errorClass_ANON_2, conclude, PyCompatEnum_AsObject(PyAsnEnumServiceError_errorClass_ANON_2_conclude_Type, (void *)&src->choice.conclude, 0));
PY_IMPL_CHOICE_GETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, conclude, conclude);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, conclude, conclude, *asn_DEF_ServiceError.elements[0].type);
PyObject *PyAsnEnumServiceError_errorClass_ANON_2_cancel_Type = NULL;
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_errorClass_ANON_2, ServiceError__errorClass, cancel, cancel,PyCompatEnum_FromObject(value, (void *)&dst->choice.cancel, 0));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_errorClass_ANON_2, cancel, PyCompatEnum_AsObject(PyAsnEnumServiceError_errorClass_ANON_2_cancel_Type, (void *)&src->choice.cancel, 0));
PY_IMPL_CHOICE_GETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, cancel, cancel);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, cancel, cancel, *asn_DEF_ServiceError.elements[0].type);
PyObject *PyAsnEnumServiceError_errorClass_ANON_2_file_Type = NULL;
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_errorClass_ANON_2, ServiceError__errorClass, file, file,PyCompatEnum_FromObject(value, (void *)&dst->choice.file, 0));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_errorClass_ANON_2, file, PyCompatEnum_AsObject(PyAsnEnumServiceError_errorClass_ANON_2_file_Type, (void *)&src->choice.file, 0));
PY_IMPL_CHOICE_GETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, file, file);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, file, file, *asn_DEF_ServiceError.elements[0].type);
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_errorClass_ANON_2, ServiceError__errorClass, others, others, PyCompatLong_FromObject(value, (void *)&dst->choice.others, 1));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_errorClass_ANON_2, others, PyCompatLong_AsObject((void *)&src->choice.others, 1));
PY_IMPL_CHOICE_GETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, others, others);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, others, others, *asn_DEF_ServiceError.elements[0].type);
PY_IMPL_CHECK_CONSTRAINTS(ServiceError_errorClass_ANON_2, asn_DEF_ServiceError.elements[0].type);
PY_IMPL_ENCODE(ServiceError_errorClass_ANON_2, asn_DEF_ServiceError.elements[0].type);
PY_IMPL_DECODE(ServiceError_errorClass_ANON_2, asn_DEF_ServiceError.elements[0].type);
PY_IMPL_DEALLOC(ServiceError_errorClass_ANON_2, *(asn_DEF_ServiceError.elements[0].type));
PY_IMPL_SEQ_TOPY(ServiceError_errorClass_ANON_2, asn_DEF_ServiceError.elements[0].type);
PY_IMPL_GENERIC_REPR(ServiceError_errorClass_ANON_2, ServiceError__errorClass);
PY_IMPL_DECODE_BER(ServiceError_errorClass_ANON_2);
PY_IMPL_ENCODE_SPECIFIC(ServiceError_errorClass_ANON_2, ber, ATS_BER);
PY_IMPL_DECODE_DER(ServiceError_errorClass_ANON_2);
PY_IMPL_ENCODE_SPECIFIC(ServiceError_errorClass_ANON_2, der, ATS_DER);
PY_IMPL_DECODE_CER(ServiceError_errorClass_ANON_2);
PY_IMPL_ENCODE_SPECIFIC(ServiceError_errorClass_ANON_2, cer, ATS_BER);
PY_IMPL_DECODE_XER(ServiceError_errorClass_ANON_2);
PY_IMPL_ENCODE_XER(ServiceError_errorClass_ANON_2);
PY_IMPL_ENCODE_SPECIFIC(ServiceError_errorClass_ANON_2, plain, ATS_NONSTANDARD_PLAINTEXT);
PY_IMPL_DECODE_JER(ServiceError_errorClass_ANON_2);
PY_IMPL_ENCODE_JER(ServiceError_errorClass_ANON_2);
PyObject *PyAsnEnumServiceError_errorClass_ANON_2_PRESENT_Type = NULL;
PY_IMPL_CHOICE_PRESENT_ATTR(ServiceError_errorClass_ANON_2);
PY_IMPL_GENERIC_NEW(ServiceError_errorClass_ANON_2, NULL);
PY_IMPL_GENERIC_IS_VALID(ServiceError_errorClass_ANON_2);
PY_IMPL_CHOICE_FROMPY(ServiceError_errorClass_ANON_2, asn_DEF_ServiceError.elements[0].type,
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, vmd_state, vmd_state, vmd_state);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, application_reference, application_reference, application_reference);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, definition, definition, definition);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, resource, resource, resource);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, service, service, service);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, service_preempt, service_preempt, service_preempt);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, time_resolution, time_resolution, time_resolution);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, access, access, access);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, initiate, initiate, initiate);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, conclude, conclude, conclude);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, cancel, cancel, cancel);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, file, file, file);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_errorClass_ANON_2, ServiceError__errorClass, others, others, others);
);
PY_IMPL_CHOICE_INIT_GENERIC(ServiceError_errorClass_ANON_2, ServiceError__errorClass);
PY_IMPL_SEQ_ANON_ATTR_FROMPY(ServiceError, errorClass, &src->errorClass, ServiceError_errorClass_ANON_2);
PY_IMPL_SEQ_ANON_ATTR_TOPY(ServiceError, errorClass, &src->errorClass, ServiceError_errorClass_ANON_2);
PY_IMPL_SEQ_INNER_SETATTR(ServiceError, errorClass, errorClass, ServiceError_errorClass_ANON_2);
PY_IMPL_SEQ_INNER_GETATTR(ServiceError, errorClass, &self->ob_value->errorClass, ServiceError_errorClass_ANON_2);
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, obtainFile, obtainFile,PyAsnObtainFile_Error_FromPython(value, &dst->choice.obtainFile));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_serviceSpecificInfo_ANON_79, obtainFile, PyCompatAsnType_FromParent(&PyAsnObtainFile_Error_Type, parent,  (void *)&src->choice.obtainFile));
PY_IMPL_CHOICE_GETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, obtainFile, obtainFile);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, obtainFile, obtainFile, *asn_DEF_ServiceError.elements[3].type);
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, start, start,PyAsnStart_Error_FromPython(value, &dst->choice.start));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_serviceSpecificInfo_ANON_79, start, PyCompatAsnType_FromParent(&PyAsnStart_Error_Type, parent,  (void *)&src->choice.start));
PY_IMPL_CHOICE_GETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, start, start);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, start, start, *asn_DEF_ServiceError.elements[3].type);
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, stop, stop,PyAsnStop_Error_FromPython(value, &dst->choice.stop));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_serviceSpecificInfo_ANON_79, stop, PyCompatAsnType_FromParent(&PyAsnStop_Error_Type, parent,  (void *)&src->choice.stop));
PY_IMPL_CHOICE_GETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, stop, stop);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, stop, stop, *asn_DEF_ServiceError.elements[3].type);
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, resume, resume,PyAsnResume_Error_FromPython(value, &dst->choice.resume));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_serviceSpecificInfo_ANON_79, resume, PyCompatAsnType_FromParent(&PyAsnResume_Error_Type, parent,  (void *)&src->choice.resume));
PY_IMPL_CHOICE_GETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, resume, resume);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, resume, resume, *asn_DEF_ServiceError.elements[3].type);
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, reset, reset,PyAsnReset_Error_FromPython(value, &dst->choice.reset));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_serviceSpecificInfo_ANON_79, reset, PyCompatAsnType_FromParent(&PyAsnReset_Error_Type, parent,  (void *)&src->choice.reset));
PY_IMPL_CHOICE_GETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, reset, reset);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, reset, reset, *asn_DEF_ServiceError.elements[3].type);
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, deleteVariableAccess, deleteVariableAccess,PyAsnDeleteVariableAccess_Error_FromPython(value, &dst->choice.deleteVariableAccess));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_serviceSpecificInfo_ANON_79, deleteVariableAccess, PyCompatAsnType_FromParent(&PyAsnDeleteVariableAccess_Error_Type, parent,  (void *)&src->choice.deleteVariableAccess));
PY_IMPL_CHOICE_GETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, deleteVariableAccess, deleteVariableAccess);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, deleteVariableAccess, deleteVariableAccess, *asn_DEF_ServiceError.elements[3].type);
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, deleteNamedVariableList, deleteNamedVariableList,PyAsnDeleteNamedVariableList_Error_FromPython(value, &dst->choice.deleteNamedVariableList));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_serviceSpecificInfo_ANON_79, deleteNamedVariableList, PyCompatAsnType_FromParent(&PyAsnDeleteNamedVariableList_Error_Type, parent,  (void *)&src->choice.deleteNamedVariableList));
PY_IMPL_CHOICE_GETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, deleteNamedVariableList, deleteNamedVariableList);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, deleteNamedVariableList, deleteNamedVariableList, *asn_DEF_ServiceError.elements[3].type);
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, deleteNamedType, deleteNamedType,PyAsnDeleteNamedType_Error_FromPython(value, &dst->choice.deleteNamedType));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_serviceSpecificInfo_ANON_79, deleteNamedType, PyCompatAsnType_FromParent(&PyAsnDeleteNamedType_Error_Type, parent,  (void *)&src->choice.deleteNamedType));
PY_IMPL_CHOICE_GETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, deleteNamedType, deleteNamedType);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, deleteNamedType, deleteNamedType, *asn_DEF_ServiceError.elements[3].type);
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, defineEventEnrollment_Error, defineEventEnrollment_Error,PyAsnDefineEventEnrollment_Error_FromPython(value, &dst->choice.defineEventEnrollment_Error));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_serviceSpecificInfo_ANON_79, defineEventEnrollment_Error, PyCompatAsnType_FromParent(&PyAsnDefineEventEnrollment_Error_Type, parent,  (void *)&src->choice.defineEventEnrollment_Error));
PY_IMPL_CHOICE_GETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, defineEventEnrollment_Error, defineEventEnrollment_Error);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, defineEventEnrollment_Error, defineEventEnrollment_Error, *asn_DEF_ServiceError.elements[3].type);
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, fileRename, fileRename,PyAsnFileRename_Error_FromPython(value, &dst->choice.fileRename));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_serviceSpecificInfo_ANON_79, fileRename, PyCompatAsnType_FromParent(&PyAsnFileRename_Error_Type, parent,  (void *)&src->choice.fileRename));
PY_IMPL_CHOICE_GETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, fileRename, fileRename);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, fileRename, fileRename, *asn_DEF_ServiceError.elements[3].type);
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, additionalService, additionalService,PyAsnAdditionalService_Error_FromPython(value, &dst->choice.additionalService));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_serviceSpecificInfo_ANON_79, additionalService, PyCompatAsnType_FromParent(&PyAsnAdditionalService_Error_Type, parent,  (void *)&src->choice.additionalService));
PY_IMPL_CHOICE_GETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, additionalService, additionalService);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, additionalService, additionalService, *asn_DEF_ServiceError.elements[3].type);
PY_IMPL_CHOICE_ATTR_FROMPY(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, changeAccessControl, changeAccessControl,PyAsnChangeAccessControl_Error_FromPython(value, &dst->choice.changeAccessControl));
PY_IMPL_CHOICE_ATTR_TOPY(ServiceError_serviceSpecificInfo_ANON_79, changeAccessControl, PyCompatAsnType_FromParent(&PyAsnChangeAccessControl_Error_Type, parent,  (void *)&src->choice.changeAccessControl));
PY_IMPL_CHOICE_GETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, changeAccessControl, changeAccessControl);
PY_IMPL_CHOICE_GENERIC_SETATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, changeAccessControl, changeAccessControl, *asn_DEF_ServiceError.elements[3].type);
PY_IMPL_CHECK_CONSTRAINTS(ServiceError_serviceSpecificInfo_ANON_79, asn_DEF_ServiceError.elements[3].type);
PY_IMPL_ENCODE(ServiceError_serviceSpecificInfo_ANON_79, asn_DEF_ServiceError.elements[3].type);
PY_IMPL_DECODE(ServiceError_serviceSpecificInfo_ANON_79, asn_DEF_ServiceError.elements[3].type);
PY_IMPL_DEALLOC(ServiceError_serviceSpecificInfo_ANON_79, *(asn_DEF_ServiceError.elements[3].type));
PY_IMPL_SEQ_TOPY(ServiceError_serviceSpecificInfo_ANON_79, asn_DEF_ServiceError.elements[3].type);
PY_IMPL_GENERIC_REPR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo);
PY_IMPL_DECODE_BER(ServiceError_serviceSpecificInfo_ANON_79);
PY_IMPL_ENCODE_SPECIFIC(ServiceError_serviceSpecificInfo_ANON_79, ber, ATS_BER);
PY_IMPL_DECODE_DER(ServiceError_serviceSpecificInfo_ANON_79);
PY_IMPL_ENCODE_SPECIFIC(ServiceError_serviceSpecificInfo_ANON_79, der, ATS_DER);
PY_IMPL_DECODE_CER(ServiceError_serviceSpecificInfo_ANON_79);
PY_IMPL_ENCODE_SPECIFIC(ServiceError_serviceSpecificInfo_ANON_79, cer, ATS_BER);
PY_IMPL_DECODE_XER(ServiceError_serviceSpecificInfo_ANON_79);
PY_IMPL_ENCODE_XER(ServiceError_serviceSpecificInfo_ANON_79);
PY_IMPL_ENCODE_SPECIFIC(ServiceError_serviceSpecificInfo_ANON_79, plain, ATS_NONSTANDARD_PLAINTEXT);
PY_IMPL_DECODE_JER(ServiceError_serviceSpecificInfo_ANON_79);
PY_IMPL_ENCODE_JER(ServiceError_serviceSpecificInfo_ANON_79);
PyObject *PyAsnEnumServiceError_serviceSpecificInfo_ANON_79_PRESENT_Type = NULL;
PY_IMPL_CHOICE_PRESENT_ATTR(ServiceError_serviceSpecificInfo_ANON_79);
PY_IMPL_GENERIC_NEW(ServiceError_serviceSpecificInfo_ANON_79, NULL);
PY_IMPL_GENERIC_IS_VALID(ServiceError_serviceSpecificInfo_ANON_79);
PY_IMPL_CHOICE_FROMPY(ServiceError_serviceSpecificInfo_ANON_79, asn_DEF_ServiceError.elements[3].type,
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, obtainFile, obtainFile, obtainFile);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, start, start, start);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, stop, stop, stop);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, resume, resume, resume);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, reset, reset, reset);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, deleteVariableAccess, deleteVariableAccess, deleteVariableAccess);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, deleteNamedVariableList, deleteNamedVariableList, deleteNamedVariableList);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, deleteNamedType, deleteNamedType, deleteNamedType);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, defineEventEnrollment_Error, defineEventEnrollment_Error, defineEventEnrollment_Error);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, fileRename, fileRename, fileRename);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, additionalService, additionalService, additionalService);
	PY_IMPL_CHOICE_INIT_ATTR(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo, changeAccessControl, changeAccessControl, changeAccessControl);
);
PY_IMPL_CHOICE_INIT_GENERIC(ServiceError_serviceSpecificInfo_ANON_79, ServiceError__serviceSpecificInfo);
PY_IMPL_SEQ_ANON_ATTR_FROMPY(ServiceError, serviceSpecificInfo, src->serviceSpecificInfo, ServiceError_serviceSpecificInfo_ANON_79);
PY_IMPL_SEQ_ANON_ATTR_TOPY(ServiceError, serviceSpecificInfo, src->serviceSpecificInfo, ServiceError_serviceSpecificInfo_ANON_79);
PY_IMPL_SEQ_INNER_OPT_SETATTR(ServiceError, serviceSpecificInfo, serviceSpecificInfo, ServiceError_serviceSpecificInfo_ANON_79, *asn_DEF_ServiceError.elements[3].type);
PY_IMPL_SEQ_INNER_GETATTR(ServiceError, serviceSpecificInfo, self->ob_value->serviceSpecificInfo, ServiceError_serviceSpecificInfo_ANON_79);
PY_IMPL_SEQ_ATTR_GENERIC_FREE(ServiceError, additionalCode);
PY_IMPL_SEQ_ATTR_GENERIC_NEW(ServiceError, additionalCode, long);
PY_IMPL_SEQ_ATTR_INDIRECT_FROMPY(ServiceError, additionalCode, PyCompatLong_FromObject(value, target, 1));
PY_IMPL_SEQ_ATTR_INDIRECT_TOPY(ServiceError, additionalCode, PyCompatLong_AsObject(target, 1));
PY_IMPL_SEQ_OPT_GETATTR(ServiceError, additionalCode);
PY_IMPL_SEQ_OPT_SETATTR(ServiceError, additionalCode);
PY_IMPL_SEQ_ATTR_GENERIC_FREE(ServiceError, additionalDescription);
PY_IMPL_SEQ_ATTR_GENERIC_NEW(ServiceError, additionalDescription, VisibleString_t);
PY_IMPL_SEQ_ATTR_INDIRECT_FROMPY(ServiceError, additionalDescription, PyCompatUnicode_AsUTF8(value, &((OCTET_STRING_t *)(target))->buf, &((OCTET_STRING_t *)(target))->size));
PY_IMPL_SEQ_ATTR_INDIRECT_TOPY(ServiceError, additionalDescription, PyCompatUnicode_FromStringAndSize(((OCTET_STRING_t *)target)->buf, ((OCTET_STRING_t *)target)->size));
PY_IMPL_SEQ_OPT_GETATTR(ServiceError, additionalDescription);
PY_IMPL_SEQ_OPT_SETATTR(ServiceError, additionalDescription);
PY_IMPL_GENERIC_DEALLOC(ServiceError);
PY_IMPL_GENERIC_CHECK_CONSTRAINTS(ServiceError);
PY_IMPL_GENERIC_ENCODE(ServiceError);
PY_IMPL_GENERIC_DECODE(ServiceError);
PY_IMPL_SEQ_GENERIC_TOPY(ServiceError);
PY_IMPL_DECODE_BER(ServiceError);
PY_IMPL_ENCODE_SPECIFIC(ServiceError, ber, ATS_BER);
PY_IMPL_DECODE_DER(ServiceError);
PY_IMPL_ENCODE_SPECIFIC(ServiceError, der, ATS_DER);
PY_IMPL_DECODE_CER(ServiceError);
PY_IMPL_ENCODE_SPECIFIC(ServiceError, cer, ATS_BER);
PY_IMPL_DECODE_XER(ServiceError);
PY_IMPL_ENCODE_XER(ServiceError);
PY_IMPL_ENCODE_SPECIFIC(ServiceError, plain, ATS_NONSTANDARD_PLAINTEXT);
PY_IMPL_DECODE_JER(ServiceError);
PY_IMPL_ENCODE_JER(ServiceError);
PY_IMPL_GENERIC_NEW(ServiceError, &asn_DEF_ServiceError);
PY_IMPL_REPR(ServiceError);
PY_IMPL_GENERIC_IS_VALID(ServiceError);
PY_IMPL_SEQ_FROMPY(ServiceError, &asn_DEF_ServiceError,
	PY_IMPL_SEQ_INIT_ATTR(ServiceError, errorClass, errorClass);
	PY_IMPL_SEQ_INIT_ATTR(ServiceError, additionalCode, additionalCode);
	PY_IMPL_SEQ_INIT_ATTR(ServiceError, additionalDescription, additionalDescription);
	PY_IMPL_SEQ_INIT_ATTR(ServiceError, serviceSpecificInfo, serviceSpecificInfo);
);
PY_IMPL_SEQ_INIT(ServiceError);

/* class attributes definition */
static PyGetSetDef PyAsnServiceError_errorClass_ANON_2_getset[] = {
	{"present",  (getter)PyAsnServiceError_errorClass_ANON_2__get_present, NULL, NULL, NULL},
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_errorClass_ANON_2, vmd_state, vmd_state),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_errorClass_ANON_2, application_reference, application_reference),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_errorClass_ANON_2, definition, definition),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_errorClass_ANON_2, resource, resource),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_errorClass_ANON_2, service, service),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_errorClass_ANON_2, service_preempt, service_preempt),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_errorClass_ANON_2, time_resolution, time_resolution),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_errorClass_ANON_2, access, access),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_errorClass_ANON_2, initiate, initiate),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_errorClass_ANON_2, conclude, conclude),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_errorClass_ANON_2, cancel, cancel),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_errorClass_ANON_2, file, file),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_errorClass_ANON_2, others, others),
	{NULL, NULL, NULL, NULL, NULL} /* sentinel */
};
static PyGetSetDef PyAsnServiceError_serviceSpecificInfo_ANON_79_getset[] = {
	{"present",  (getter)PyAsnServiceError_serviceSpecificInfo_ANON_79__get_present, NULL, NULL, NULL},
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_serviceSpecificInfo_ANON_79, obtainFile, obtainFile),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_serviceSpecificInfo_ANON_79, start, start),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_serviceSpecificInfo_ANON_79, stop, stop),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_serviceSpecificInfo_ANON_79, resume, resume),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_serviceSpecificInfo_ANON_79, reset, reset),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_serviceSpecificInfo_ANON_79, deleteVariableAccess, deleteVariableAccess),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_serviceSpecificInfo_ANON_79, deleteNamedVariableList, deleteNamedVariableList),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_serviceSpecificInfo_ANON_79, deleteNamedType, deleteNamedType),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_serviceSpecificInfo_ANON_79, defineEventEnrollment_Error, defineEventEnrollment_Error),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_serviceSpecificInfo_ANON_79, fileRename, fileRename),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_serviceSpecificInfo_ANON_79, additionalService, additionalService),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError_serviceSpecificInfo_ANON_79, changeAccessControl, changeAccessControl),
	{NULL, NULL, NULL, NULL, NULL} /* sentinel */
};
static PyGetSetDef PyAsnServiceError_getset[] = {
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError, errorClass, errorClass),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError, additionalCode, additionalCode),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError, additionalDescription, additionalDescription),
	PY_IMPL_GETSET_ITEM_INTERNAL(ServiceError, serviceSpecificInfo, serviceSpecificInfo),
	{NULL, NULL, NULL, NULL, NULL} /* sentinel */
};

/* class methods definition */
static PyMethodDef PyAsnServiceError_errorClass_ANON_2_methods[] = {
	PY_IMPL_METHODDEF_ITEM(ServiceError_errorClass_ANON_2, is_valid, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(ServiceError_errorClass_ANON_2, check_constraints, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(ServiceError_errorClass_ANON_2, ber_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(ServiceError_errorClass_ANON_2, ber_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(ServiceError_errorClass_ANON_2, der_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(ServiceError_errorClass_ANON_2, der_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(ServiceError_errorClass_ANON_2, cer_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(ServiceError_errorClass_ANON_2, cer_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(ServiceError_errorClass_ANON_2, xer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(ServiceError_errorClass_ANON_2, xer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{"to_text", (PyCFunction)PyAsnServiceError_errorClass_ANON_2__plain_encode, (METH_NOARGS), NULL},
	PY_IMPL_METHODDEF_ITEM(ServiceError_errorClass_ANON_2, jer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(ServiceError_errorClass_ANON_2, jer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{NULL, NULL, 0, NULL} /* sentinel */
};
static PyMethodDef PyAsnServiceError_serviceSpecificInfo_ANON_79_methods[] = {
	PY_IMPL_METHODDEF_ITEM(ServiceError_serviceSpecificInfo_ANON_79, is_valid, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(ServiceError_serviceSpecificInfo_ANON_79, check_constraints, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(ServiceError_serviceSpecificInfo_ANON_79, ber_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(ServiceError_serviceSpecificInfo_ANON_79, ber_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(ServiceError_serviceSpecificInfo_ANON_79, der_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(ServiceError_serviceSpecificInfo_ANON_79, der_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(ServiceError_serviceSpecificInfo_ANON_79, cer_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(ServiceError_serviceSpecificInfo_ANON_79, cer_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(ServiceError_serviceSpecificInfo_ANON_79, xer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(ServiceError_serviceSpecificInfo_ANON_79, xer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{"to_text", (PyCFunction)PyAsnServiceError_serviceSpecificInfo_ANON_79__plain_encode, (METH_NOARGS), NULL},
	PY_IMPL_METHODDEF_ITEM(ServiceError_serviceSpecificInfo_ANON_79, jer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(ServiceError_serviceSpecificInfo_ANON_79, jer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{NULL, NULL, 0, NULL} /* sentinel */
};
static PyMethodDef PyAsnServiceError_methods[] = {
	PY_IMPL_METHODDEF_ITEM(ServiceError, is_valid, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(ServiceError, check_constraints, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(ServiceError, ber_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(ServiceError, ber_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(ServiceError, der_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(ServiceError, der_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(ServiceError, cer_encode, METH_NOARGS),
	PY_IMPL_METHODDEF_ITEM(ServiceError, cer_decode, METH_VARARGS | METH_STATIC),
	PY_IMPL_METHODDEF_ITEM(ServiceError, xer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(ServiceError, xer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{"to_text", (PyCFunction)PyAsnServiceError__plain_encode, (METH_NOARGS), NULL},
	PY_IMPL_METHODDEF_ITEM(ServiceError, jer_encode, METH_VARARGS | METH_KEYWORDS),
	PY_IMPL_METHODDEF_ITEM(ServiceError, jer_decode, METH_VARARGS | METH_KEYWORDS | METH_STATIC),
	{NULL, NULL, 0, NULL} /* sentinel */
};

/* type definition */
PyTypeObject PyAsnServiceError_errorClass_ANON_2_Type = {
	PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "_mms.ServiceError.errorClass_TYPE",
	.tp_basicsize = sizeof(PyAsnServiceError_errorClass_ANON_2Object),
	.tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
	.tp_new = (newfunc)PyAsnServiceError_errorClass_ANON_2__new,
	.tp_repr = (reprfunc)PyAsnServiceError_errorClass_ANON_2__repr,
	.tp_dealloc = (destructor)PyAsnServiceError_errorClass_ANON_2__dealloc,
	.tp_init = (initproc)PyAsnServiceError_errorClass_ANON_2__init,
	.tp_getset = PyAsnServiceError_errorClass_ANON_2_getset,
	.tp_methods = PyAsnServiceError_errorClass_ANON_2_methods,
	.tp_doc = "ASN.1 anonymous type ServiceError__errorClass_TYPE part of ServiceError",
};
PyTypeObject PyAsnServiceError_serviceSpecificInfo_ANON_79_Type = {
	PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "_mms.ServiceError.serviceSpecificInfo_TYPE",
	.tp_basicsize = sizeof(PyAsnServiceError_serviceSpecificInfo_ANON_79Object),
	.tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
	.tp_new = (newfunc)PyAsnServiceError_serviceSpecificInfo_ANON_79__new,
	.tp_repr = (reprfunc)PyAsnServiceError_serviceSpecificInfo_ANON_79__repr,
	.tp_dealloc = (destructor)PyAsnServiceError_serviceSpecificInfo_ANON_79__dealloc,
	.tp_init = (initproc)PyAsnServiceError_serviceSpecificInfo_ANON_79__init,
	.tp_getset = PyAsnServiceError_serviceSpecificInfo_ANON_79_getset,
	.tp_methods = PyAsnServiceError_serviceSpecificInfo_ANON_79_methods,
	.tp_doc = "ASN.1 anonymous type ServiceError__serviceSpecificInfo_TYPE part of ServiceError",
};
PyTypeObject PyAsnServiceError_Type = {
	PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "_mms.ServiceError",
	.tp_basicsize = sizeof(PyAsnServiceErrorObject),
	.tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
	.tp_new = (newfunc)PyAsnServiceError__new,
	.tp_repr = (reprfunc)PyAsnServiceError__repr,
	.tp_dealloc = (destructor)PyAsnServiceError__dealloc,
	.tp_init = (initproc)PyAsnServiceError__init,
	.tp_getset = PyAsnServiceError_getset,
	.tp_methods = PyAsnServiceError_methods,
	.tp_doc = "ASN.1 ServiceError type",
};

/* module initializer */
int PyAsnServiceError_ModSetupTypes(void) {
	if (PyType_Ready(&PyAsnServiceError_errorClass_ANON_2_Type) < 0) return -1;
	if (PyType_Ready(&PyAsnServiceError_serviceSpecificInfo_ANON_79_Type) < 0) return -1;
	if (PyType_Ready(&PyAsnServiceError_Type) < 0) return -1;
    return 0;
}

void PyAsnServiceError_ModClear(PyObject *mod) {
	Py_CLEAR(PyAsnEnumServiceError_errorClass_ANON_2_vmd_state_Type);
	Py_CLEAR(PyAsnEnumServiceError_errorClass_ANON_2_application_reference_Type);
	Py_CLEAR(PyAsnEnumServiceError_errorClass_ANON_2_definition_Type);
	Py_CLEAR(PyAsnEnumServiceError_errorClass_ANON_2_resource_Type);
	Py_CLEAR(PyAsnEnumServiceError_errorClass_ANON_2_service_Type);
	Py_CLEAR(PyAsnEnumServiceError_errorClass_ANON_2_service_preempt_Type);
	Py_CLEAR(PyAsnEnumServiceError_errorClass_ANON_2_time_resolution_Type);
	Py_CLEAR(PyAsnEnumServiceError_errorClass_ANON_2_access_Type);
	Py_CLEAR(PyAsnEnumServiceError_errorClass_ANON_2_initiate_Type);
	Py_CLEAR(PyAsnEnumServiceError_errorClass_ANON_2_conclude_Type);
	Py_CLEAR(PyAsnEnumServiceError_errorClass_ANON_2_cancel_Type);
	Py_CLEAR(PyAsnEnumServiceError_errorClass_ANON_2_file_Type);
	Py_CLEAR(PyAsnEnumServiceError_errorClass_ANON_2_PRESENT_Type);
	Py_CLEAR(PyAsnEnumServiceError_serviceSpecificInfo_ANON_79_PRESENT_Type);
}

int PyAsnServiceError_ModInit(PyObject *mod) {
	PY_IMPL_NEW_ENUM(ServiceError_errorClass_ANON_2.vmd_state_VALUES, PyAsnEnumServiceError_errorClass_ANON_2_vmd_state_Type, -1, 
		PY_IMPL_ENUM_VALUE(V_other, ServiceError__errorClass__vmd_state_other, 0);
		PY_IMPL_ENUM_VALUE(V_vmd_state_conflict, ServiceError__errorClass__vmd_state_vmd_state_conflict, 1);
		PY_IMPL_ENUM_VALUE(V_vmd_operational_problem, ServiceError__errorClass__vmd_state_vmd_operational_problem, 2);
		PY_IMPL_ENUM_VALUE(V_domain_transfer_problem, ServiceError__errorClass__vmd_state_domain_transfer_problem, 3);
		PY_IMPL_ENUM_VALUE(V_state_machine_id_invalid, ServiceError__errorClass__vmd_state_state_machine_id_invalid, 4);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(ServiceError_errorClass_ANON_2, ServiceError_errorClass_ANON_2_vmd_state, vmd_state_VALUES);
	PY_IMPL_NEW_ENUM(ServiceError_errorClass_ANON_2.application_reference_VALUES, PyAsnEnumServiceError_errorClass_ANON_2_application_reference_Type, -1, 
		PY_IMPL_ENUM_VALUE(V_other, ServiceError__errorClass__application_reference_other, 0);
		PY_IMPL_ENUM_VALUE(V_application_unreachable, ServiceError__errorClass__application_reference_application_unreachable, 1);
		PY_IMPL_ENUM_VALUE(V_connection_lost, ServiceError__errorClass__application_reference_connection_lost, 2);
		PY_IMPL_ENUM_VALUE(V_application_reference_invalid, ServiceError__errorClass__application_reference_application_reference_invalid, 3);
		PY_IMPL_ENUM_VALUE(V_context_unsupported, ServiceError__errorClass__application_reference_context_unsupported, 4);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(ServiceError_errorClass_ANON_2, ServiceError_errorClass_ANON_2_application_reference, application_reference_VALUES);
	PY_IMPL_NEW_ENUM(ServiceError_errorClass_ANON_2.definition_VALUES, PyAsnEnumServiceError_errorClass_ANON_2_definition_Type, -1, 
		PY_IMPL_ENUM_VALUE(V_other, ServiceError__errorClass__definition_other, 0);
		PY_IMPL_ENUM_VALUE(V_object_undefined, ServiceError__errorClass__definition_object_undefined, 1);
		PY_IMPL_ENUM_VALUE(V_invalid_address, ServiceError__errorClass__definition_invalid_address, 2);
		PY_IMPL_ENUM_VALUE(V_type_unsupported, ServiceError__errorClass__definition_type_unsupported, 3);
		PY_IMPL_ENUM_VALUE(V_type_inconsistent, ServiceError__errorClass__definition_type_inconsistent, 4);
		PY_IMPL_ENUM_VALUE(V_object_exists, ServiceError__errorClass__definition_object_exists, 5);
		PY_IMPL_ENUM_VALUE(V_object_attribute_inconsistent, ServiceError__errorClass__definition_object_attribute_inconsistent, 6);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(ServiceError_errorClass_ANON_2, ServiceError_errorClass_ANON_2_definition, definition_VALUES);
	PY_IMPL_NEW_ENUM(ServiceError_errorClass_ANON_2.resource_VALUES, PyAsnEnumServiceError_errorClass_ANON_2_resource_Type, -1, 
		PY_IMPL_ENUM_VALUE(V_other, ServiceError__errorClass__resource_other, 0);
		PY_IMPL_ENUM_VALUE(V_memory_unavailable, ServiceError__errorClass__resource_memory_unavailable, 1);
		PY_IMPL_ENUM_VALUE(V_processor_resource_unavailable, ServiceError__errorClass__resource_processor_resource_unavailable, 2);
		PY_IMPL_ENUM_VALUE(V_mass_storage_unavailable, ServiceError__errorClass__resource_mass_storage_unavailable, 3);
		PY_IMPL_ENUM_VALUE(V_capability_unavailable, ServiceError__errorClass__resource_capability_unavailable, 4);
		PY_IMPL_ENUM_VALUE(V_capability_unknown, ServiceError__errorClass__resource_capability_unknown, 5);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(ServiceError_errorClass_ANON_2, ServiceError_errorClass_ANON_2_resource, resource_VALUES);
	PY_IMPL_NEW_ENUM(ServiceError_errorClass_ANON_2.service_VALUES, PyAsnEnumServiceError_errorClass_ANON_2_service_Type, -1, 
		PY_IMPL_ENUM_VALUE(V_other, ServiceError__errorClass__service_other, 0);
		PY_IMPL_ENUM_VALUE(V_primitives_out_of_sequence, ServiceError__errorClass__service_primitives_out_of_sequence, 1);
		PY_IMPL_ENUM_VALUE(V_object_state_conflict, ServiceError__errorClass__service_object_state_conflict, 2);
		PY_IMPL_ENUM_VALUE(V_pdu_size, ServiceError__errorClass__service_pdu_size, 3);
		PY_IMPL_ENUM_VALUE(V_continuation_invalid, ServiceError__errorClass__service_continuation_invalid, 4);
		PY_IMPL_ENUM_VALUE(V_object_constraint_conflict, ServiceError__errorClass__service_object_constraint_conflict, 5);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(ServiceError_errorClass_ANON_2, ServiceError_errorClass_ANON_2_service, service_VALUES);
	PY_IMPL_NEW_ENUM(ServiceError_errorClass_ANON_2.service_preempt_VALUES, PyAsnEnumServiceError_errorClass_ANON_2_service_preempt_Type, -1, 
		PY_IMPL_ENUM_VALUE(V_other, ServiceError__errorClass__service_preempt_other, 0);
		PY_IMPL_ENUM_VALUE(V_timeout, ServiceError__errorClass__service_preempt_timeout, 1);
		PY_IMPL_ENUM_VALUE(V_deadlock, ServiceError__errorClass__service_preempt_deadlock, 2);
		PY_IMPL_ENUM_VALUE(V_cancel, ServiceError__errorClass__service_preempt_cancel, 3);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(ServiceError_errorClass_ANON_2, ServiceError_errorClass_ANON_2_service_preempt, service_preempt_VALUES);
	PY_IMPL_NEW_ENUM(ServiceError_errorClass_ANON_2.time_resolution_VALUES, PyAsnEnumServiceError_errorClass_ANON_2_time_resolution_Type, -1, 
		PY_IMPL_ENUM_VALUE(V_other, ServiceError__errorClass__time_resolution_other, 0);
		PY_IMPL_ENUM_VALUE(V_unsupportable_time_resolution, ServiceError__errorClass__time_resolution_unsupportable_time_resolution, 1);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(ServiceError_errorClass_ANON_2, ServiceError_errorClass_ANON_2_time_resolution, time_resolution_VALUES);
	PY_IMPL_NEW_ENUM(ServiceError_errorClass_ANON_2.access_VALUES, PyAsnEnumServiceError_errorClass_ANON_2_access_Type, -1, 
		PY_IMPL_ENUM_VALUE(V_other, ServiceError__errorClass__access_other, 0);
		PY_IMPL_ENUM_VALUE(V_object_access_unsupported, ServiceError__errorClass__access_object_access_unsupported, 1);
		PY_IMPL_ENUM_VALUE(V_object_non_existent, ServiceError__errorClass__access_object_non_existent, 2);
		PY_IMPL_ENUM_VALUE(V_object_access_denied, ServiceError__errorClass__access_object_access_denied, 3);
		PY_IMPL_ENUM_VALUE(V_object_invalidated, ServiceError__errorClass__access_object_invalidated, 4);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(ServiceError_errorClass_ANON_2, ServiceError_errorClass_ANON_2_access, access_VALUES);
	PY_IMPL_NEW_ENUM(ServiceError_errorClass_ANON_2.initiate_VALUES, PyAsnEnumServiceError_errorClass_ANON_2_initiate_Type, -1, 
		PY_IMPL_ENUM_VALUE(V_other, ServiceError__errorClass__initiate_other, 0);
		PY_IMPL_ENUM_VALUE(V_max_services_outstanding_calling_insufficient, ServiceError__errorClass__initiate_max_services_outstanding_calling_insufficient, 3);
		PY_IMPL_ENUM_VALUE(V_max_services_outstanding_called_insufficient, ServiceError__errorClass__initiate_max_services_outstanding_called_insufficient, 4);
		PY_IMPL_ENUM_VALUE(V_service_CBB_insufficient, ServiceError__errorClass__initiate_service_CBB_insufficient, 5);
		PY_IMPL_ENUM_VALUE(V_parameter_CBB_insufficient, ServiceError__errorClass__initiate_parameter_CBB_insufficient, 6);
		PY_IMPL_ENUM_VALUE(V_nesting_level_insufficient, ServiceError__errorClass__initiate_nesting_level_insufficient, 7);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(ServiceError_errorClass_ANON_2, ServiceError_errorClass_ANON_2_initiate, initiate_VALUES);
	PY_IMPL_NEW_ENUM(ServiceError_errorClass_ANON_2.conclude_VALUES, PyAsnEnumServiceError_errorClass_ANON_2_conclude_Type, -1, 
		PY_IMPL_ENUM_VALUE(V_other, ServiceError__errorClass__conclude_other, 0);
		PY_IMPL_ENUM_VALUE(V_further_communication_required, ServiceError__errorClass__conclude_further_communication_required, 1);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(ServiceError_errorClass_ANON_2, ServiceError_errorClass_ANON_2_conclude, conclude_VALUES);
	PY_IMPL_NEW_ENUM(ServiceError_errorClass_ANON_2.cancel_VALUES, PyAsnEnumServiceError_errorClass_ANON_2_cancel_Type, -1, 
		PY_IMPL_ENUM_VALUE(V_other, ServiceError__errorClass__cancel_other, 0);
		PY_IMPL_ENUM_VALUE(V_invoke_id_unknown, ServiceError__errorClass__cancel_invoke_id_unknown, 1);
		PY_IMPL_ENUM_VALUE(V_cancel_not_possible, ServiceError__errorClass__cancel_cancel_not_possible, 2);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(ServiceError_errorClass_ANON_2, ServiceError_errorClass_ANON_2_cancel, cancel_VALUES);
	PY_IMPL_NEW_ENUM(ServiceError_errorClass_ANON_2.file_VALUES, PyAsnEnumServiceError_errorClass_ANON_2_file_Type, -1, 
		PY_IMPL_ENUM_VALUE(V_other, ServiceError__errorClass__file_other, 0);
		PY_IMPL_ENUM_VALUE(V_filename_ambiguous, ServiceError__errorClass__file_filename_ambiguous, 1);
		PY_IMPL_ENUM_VALUE(V_file_busy, ServiceError__errorClass__file_file_busy, 2);
		PY_IMPL_ENUM_VALUE(V_filename_syntax_error, ServiceError__errorClass__file_filename_syntax_error, 3);
		PY_IMPL_ENUM_VALUE(V_content_type_invalid, ServiceError__errorClass__file_content_type_invalid, 4);
		PY_IMPL_ENUM_VALUE(V_position_invalid, ServiceError__errorClass__file_position_invalid, 5);
		PY_IMPL_ENUM_VALUE(V_file_access_denied, ServiceError__errorClass__file_file_access_denied, 6);
		PY_IMPL_ENUM_VALUE(V_file_non_existent, ServiceError__errorClass__file_file_non_existent, 7);
		PY_IMPL_ENUM_VALUE(V_duplicate_filename, ServiceError__errorClass__file_duplicate_filename, 8);
		PY_IMPL_ENUM_VALUE(V_insufficient_space_in_filestore, ServiceError__errorClass__file_insufficient_space_in_filestore, 9);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(ServiceError_errorClass_ANON_2, ServiceError_errorClass_ANON_2_file, file_VALUES);
	PY_IMPL_NEW_ENUM(ServiceError.errorClass_TYPE.PRESENT, PyAsnEnumServiceError_errorClass_ANON_2_PRESENT_Type, -1, 
		PY_IMPL_ENUM_VALUE(PR_NOTHING, ServiceError__errorClass_PR_NOTHING, 0);
		PY_IMPL_ENUM_VALUE(PR_vmd_state, ServiceError__errorClass_PR_vmd_state, 1);
		PY_IMPL_ENUM_VALUE(PR_application_reference, ServiceError__errorClass_PR_application_reference, 2);
		PY_IMPL_ENUM_VALUE(PR_definition, ServiceError__errorClass_PR_definition, 3);
		PY_IMPL_ENUM_VALUE(PR_resource, ServiceError__errorClass_PR_resource, 4);
		PY_IMPL_ENUM_VALUE(PR_service, ServiceError__errorClass_PR_service, 5);
		PY_IMPL_ENUM_VALUE(PR_service_preempt, ServiceError__errorClass_PR_service_preempt, 6);
		PY_IMPL_ENUM_VALUE(PR_time_resolution, ServiceError__errorClass_PR_time_resolution, 7);
		PY_IMPL_ENUM_VALUE(PR_access, ServiceError__errorClass_PR_access, 8);
		PY_IMPL_ENUM_VALUE(PR_initiate, ServiceError__errorClass_PR_initiate, 9);
		PY_IMPL_ENUM_VALUE(PR_conclude, ServiceError__errorClass_PR_conclude, 10);
		PY_IMPL_ENUM_VALUE(PR_cancel, ServiceError__errorClass_PR_cancel, 11);
		PY_IMPL_ENUM_VALUE(PR_file, ServiceError__errorClass_PR_file, 12);
		PY_IMPL_ENUM_VALUE(PR_others, ServiceError__errorClass_PR_others, 13);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(ServiceError_errorClass_ANON_2, ServiceError_errorClass_ANON_2_PRESENT, PRESENT);
	PY_IMPL_MOD_ASSIGN_OBJECT(ServiceError, errorClass_TYPE, &PyAsnServiceError_errorClass_ANON_2_Type);
	PY_IMPL_MOD_ADD_OBJECT(mod, ServiceError_errorClass_ANON_2);
	PY_IMPL_NEW_ENUM(ServiceError.serviceSpecificInfo_TYPE.PRESENT, PyAsnEnumServiceError_serviceSpecificInfo_ANON_79_PRESENT_Type, -1, 
		PY_IMPL_ENUM_VALUE(PR_NOTHING, ServiceError__serviceSpecificInfo_PR_NOTHING, 0);
		PY_IMPL_ENUM_VALUE(PR_obtainFile, ServiceError__serviceSpecificInfo_PR_obtainFile, 1);
		PY_IMPL_ENUM_VALUE(PR_start, ServiceError__serviceSpecificInfo_PR_start, 2);
		PY_IMPL_ENUM_VALUE(PR_stop, ServiceError__serviceSpecificInfo_PR_stop, 3);
		PY_IMPL_ENUM_VALUE(PR_resume, ServiceError__serviceSpecificInfo_PR_resume, 4);
		PY_IMPL_ENUM_VALUE(PR_reset, ServiceError__serviceSpecificInfo_PR_reset, 5);
		PY_IMPL_ENUM_VALUE(PR_deleteVariableAccess, ServiceError__serviceSpecificInfo_PR_deleteVariableAccess, 6);
		PY_IMPL_ENUM_VALUE(PR_deleteNamedVariableList, ServiceError__serviceSpecificInfo_PR_deleteNamedVariableList, 7);
		PY_IMPL_ENUM_VALUE(PR_deleteNamedType, ServiceError__serviceSpecificInfo_PR_deleteNamedType, 8);
		PY_IMPL_ENUM_VALUE(PR_defineEventEnrollment_Error, ServiceError__serviceSpecificInfo_PR_defineEventEnrollment_Error, 9);
		PY_IMPL_ENUM_VALUE(PR_fileRename, ServiceError__serviceSpecificInfo_PR_fileRename, 10);
		PY_IMPL_ENUM_VALUE(PR_additionalService, ServiceError__serviceSpecificInfo_PR_additionalService, 11);
		PY_IMPL_ENUM_VALUE(PR_changeAccessControl, ServiceError__serviceSpecificInfo_PR_changeAccessControl, 12);
	);
	PY_IMPL_ASSIGN_ENUM_DIRECT(ServiceError_serviceSpecificInfo_ANON_79, ServiceError_serviceSpecificInfo_ANON_79_PRESENT, PRESENT);
	PY_IMPL_MOD_ASSIGN_OBJECT(ServiceError, serviceSpecificInfo_TYPE, &PyAsnServiceError_serviceSpecificInfo_ANON_79_Type);
	PY_IMPL_MOD_ADD_OBJECT(mod, ServiceError_serviceSpecificInfo_ANON_79);
	PY_IMPL_MOD_ADD_OBJECT(mod, ServiceError);
    return 0;
}

/* end of ServiceError_Py.c */
