
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-10-01T18:54:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed0d3226e0f8af1ecab0ac2d2dabff1ee209680d",
 "version": "2.71.1b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
