# Copyright 2025 OpenSynergy Indonesia
# Copyright 2025 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Consulting",
    "version": "14.0.5.19.0",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "website": "https://simetri-sinergi.id",
    "license": "AGPL-3",
    "depends": [
        "ssi_master_data_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_partner_mixin",
        "ssi_res_partner_m2o_configurator_mixin",
        "ssi_m2o_configurator_mixin",
        "ssi_schema_parser_mixin",
    ],
    "external_dependencies": {
        "python": [
            "pyyaml",
            "tabulate",
            "pandas",
        ],
    },
    "data": [
        "data/schema_parser_category.xml",
        "security/ir_module_category.xml",
        "security/ir_module_category/consulting_service.xml",
        "security/ir_module_category/consulting_service_business_process.xml",
        "security/ir_module_category/consulting_service_business_process_area.xml",
        "security/ir_module_category/consulting_service_materialized_view.xml",
        "security/ir_module_category/consulting_service_issue.xml",
        "security/ir_module_category/consulting_service_entity.xml",
        "security/ir_module_category/consulting_service_document_type.xml",
        "security/ir_module_category/consulting_service_document_extraction.xml",
        "security/res_groups/consulting_chart_template.xml",
        "security/res_groups/consulting_dashboard_template.xml",
        "security/res_groups/consulting_data_structure.xml",
        "security/res_groups/consulting_materizalied_view.xml",
        "security/res_groups/consulting_report_template.xml",
        "security/res_groups/consulting_service_type.xml",
        "security/res_groups/consulting_issue_template.xml",
        "security/res_groups/consulting_service.xml",
        "security/res_groups/consulting_service_business_process.xml",
        "security/res_groups/consulting_service_business_process_area.xml",
        "security/res_groups/consulting_service_materialized_view.xml",
        "security/res_groups/consulting_service_issue.xml",
        "security/res_groups/consulting_schema_parser.xml",
        "security/res_groups/consulting_service_entity.xml",
        "security/res_groups/consulting_service_document_type.xml",
        "security/res_groups/consulting_service_document_extraction.xml",
        "security/ir_model_access/consulting_chart_template.xml",
        "security/ir_model_access/consulting_dashboard_template.xml",
        "security/ir_model_access/consulting_data_structure.xml",
        "security/ir_model_access/consulting_materialized_view.xml",
        "security/ir_model_access/consulting_report_template.xml",
        "security/ir_model_access/consulting_service_type.xml",
        "security/ir_model_access/consulting_issue_template.xml",
        "security/ir_model_access/consulting_service.xml",
        "security/ir_model_access/consulting_schema_parser.xml",
        "security/ir_model_access/consulting_service_business_process.xml",
        "security/ir_model_access/consulting_service_business_process_area.xml",
        "security/ir_model_access/consulting_service_materialized_view.xml",
        "security/ir_model_access/consulting_service_issue.xml",
        "security/ir_model_access/consulting_service_entity.xml",
        "security/ir_model_access/consulting_service_document_type.xml",
        "security/ir_model_access/consulting_service_document_extraction.xml",
        "security/ir_rule/consulting_service.xml",
        "security/ir_rule/consulting_service_business_process.xml",
        "security/ir_rule/consulting_service_business_process_area.xml",
        "security/ir_rule/consulting_service_materialized_view.xml",
        "security/ir_rule/consulting_service_issue.xml",
        "security/ir_rule/consulting_service_entity.xml",
        "security/ir_rule/consulting_service_document_type.xml",
        "security/ir_rule/consulting_service_document_extraction.xml",
        "ir_sequence/consulting_service.xml",
        "ir_sequence/consulting_service_business_process.xml",
        "ir_sequence/consulting_service_business_process_area.xml",
        "ir_sequence/consulting_service_materialized_view.xml",
        "ir_sequence/consulting_service_issue.xml",
        "ir_sequence/consulting_service_entity.xml",
        "ir_sequence/consulting_service_document_type.xml",
        "ir_sequence/consulting_service_document_extraction.xml",
        "sequence_template/consulting_service.xml",
        "sequence_template/consulting_service_business_process.xml",
        "sequence_template/consulting_service_business_process_area.xml",
        "sequence_template/consulting_service_materialized_view.xml",
        "sequence_template/consulting_service_issue.xml",
        "sequence_template/consulting_service_entity.xml",
        "sequence_template/consulting_service_document_type.xml",
        "sequence_template/consulting_service_document_extraction.xml",
        "policy_template/consulting_service.xml",
        "policy_template/consulting_service_business_process.xml",
        "policy_template/consulting_service_business_process_area.xml",
        "policy_template/consulting_service_materialized_view.xml",
        "policy_template/consulting_service_issue.xml",
        "policy_template/consulting_service_entity.xml",
        "policy_template/consulting_service_document_type.xml",
        "policy_template/consulting_service_document_extraction.xml",
        "approval_template/consulting_service.xml",
        "approval_template/consulting_service_business_process.xml",
        "approval_template/consulting_service_business_process_area.xml",
        "approval_template/consulting_service_materialized_view.xml",
        "approval_template/consulting_service_issue.xml",
        "approval_template/consulting_service_entity.xml",
        "approval_template/consulting_service_document_type.xml",
        "approval_template/consulting_service_document_extraction.xml",
        "menu.xml",
        "views/consulting_chart_template.xml",
        "views/consulting_dashboard_template.xml",
        "views/consulting_data_structure.xml",
        "views/consulting_materialized_view.xml",
        "views/consulting_report_template.xml",
        "views/consulting_schema_parser.xml",
        "views/consulting_service_type.xml",
        "views/consulting_issue_template.xml",
        "views/consulting_service.xml",
        "views/consulting_service_materialized_view.xml",
        "views/consulting_service_business_process.xml",
        "views/consulting_service_business_process_area.xml",
        "views/consulting_service_issue.xml",
        "views/consulting_service_entity.xml",
        "views/consulting_service_document_type.xml",
        "views/consulting_service_document_extraction.xml",
    ],
    "demo": [],
    "application": False,
}
