from enum import Enum
class Color():
    AQUA = "AQUA"
    BLACK = "BLACK"
    BLUE = "BLUE"
    FUCHSIA = "FUCHSIA"
    GRAY = "GRAY"
    GREEN = "GREEN"
    LIME = "LIME"
    MAROON = "MAROON"
    NAVY = "NAVY"
    OLIVE = "OLIVE"
    ORANGE = "ORANGE"
    PURPLE = "PURPLE"
    RED = "RED"
    SILVER = "SILVER"
    TEAL = "TEAL"
    WHITE = "WHITE"
    YELLOW = "YELLOW"
