class Fishstate():
    FISHING = "FISHING"
    CAUGHT_FISH = "CAUGHT_FISH"
    CAUGHT_ENTITY = "CAUGHT_ENTITY"
    IN_GROUND = "IN_GROUND"
    FAILED_ATTEMPT = "FAILED_ATTEMPT"
    REEL_IN = "REEL_IN"
    BITE = "BITE"
