random_words = [
    "apple","river","stone","cloud","light","forest","mouse","paper","train","dream",
    "book","silver","gold","iron","clock","table","chair","window","door","flower",
    "sun","moon","star","sky","ocean","tree","leaf","grass","mountain","valley",
    "city","village","street","road","bridge","tower","castle","house","garden","field",
    "bird","cat","dog","horse","sheep","cow","fish","shark","whale","dolphin",
    "ship","boat","car","truck","bus","plane","rocket","bicycle","helmet","engine","wheel",
    "song","music","dance","piano","guitar","drum","flute","voice","choir","band",
    "earth","water","fire","air","metal","sand","rock","dust","mud","rain",
    "storm","wind","snow","ice","fog","mist","heat","cold","spring","summer",
    "autumn","winter","morning","noon","evening","night","dawn","dusk","shadow","lightning",
    "king","queen","prince","princess","knight","soldier","archer","mage","throne","crown",
    "food","bread","rice","wheat","sugar","salt","spice","milk","butter","cheese",
    "fruit","banana","orange","mango","grape","peach","pear","plum","cherry","berry",
    "drink","waterfall","riverbank","pond","stream","lake","island","beach","coast","harbor",
    "computer","laptop","keyboard","mousepad","screen","monitor","printer","server","network","cable",
    "code","python","java","kotlin","swift","ruby","perl","shell","linux","kernel",
    "logic","math","number","algebra","geometry","calculus","vector","matrix","tensor","graph",
    "school","college","teacher","student","class","booklet","exam","pencil","pen","chalk",
    "energy","power","speed","force","mass","gravity","atom","molecule","cell","organ",
    "health","doctor","nurse","patient","hospital","medicine","pill","surgery","blood","heart",
    "family","father","mother","brother","sister","uncle","aunt","cousin","child","baby",
    "game","play","sport","cricket","football","tennis","hockey","golf","chess","dice",
    "art","paint","brush","color","canvas","sculpture","design","pattern","style","form",
    "idea","thought","mind","soul","spirit","body","dreamer","seeker","creator","builder",
    "travel","journey","path","map","guide","sign","compass","direction","goal","target"
]

animals = [
    "aardvark","albatross","alligator","alpaca","anaconda","angelfish","ant","anteater","antelope","armadillo",
    "baboon","badger","bandicoot","barnacle","barracuda","bat","bear","beaver","bee","beetle",
    "bison","blackbird","boar","bobcat","bongo","bonobo","buffalo","bull","butterfly","buzzard",
    "camel","canary","capybara","caracal","caribou","cassowary","cat","caterpillar","cattle","chameleon",
    "cheetah","chicken","chimpanzee","chinchilla","chipmunk","clam","cobra","cockatoo","cockroach","cod",
    "condor","cormorant","cougar","cow","coyote","crab","crane","crocodile","crow","cuckoo",
    "deer","dingo","dinosaur","dog","dolphin","donkey","dove","dragonfly","duck","dugong",
    "eagle","earthworm","eel","egret","elephant","elk","emu","ermine","falcon","ferret",
    "finch","firefly","fish","flamingo","fly","fox","frog","gazelle","gecko","gerbil",
    "gibbon","giraffe","goat","goose","gorilla","grasshopper","grouse","guanaco","guinea pig","gull",
    "hamster","hare","harrier","hawk","hedgehog","heron","herring","hippopotamus","hornet","horse",
    "hummingbird","hyena","ibex","ibis","iguana","impala","jackal","jaguar","jay","jellyfish",
    "kangaroo","kingfisher","kiwi","koala","koi","dragon","krill","kudu","ladybug","lapwing",
    "lark","lemur","leopard","lion","lizard","llama","lobster","locust","loris","lynx",
    "macaw","magpie","mallard","manatee","mandrill","manta ray","meerkat","mink","mole","mongoose",
    "monkey","moose","mosquito","moth","mouse","mule","narwhal","newt","nightingale","ocelot",
    "octopus","okapi","opossum","orangutan","orca","ostrich","otter","owl","ox","oyster",
    "panda","panther","parakeet","parrot","partridge","peacock","pelican","penguin","pheasant","pig",
    "pigeon","pika","platypus","polar bear","pony","porcupine","porpoise","possum","prairie dog","prawn",
    "puffin","puma","python","quail","quokka","rabbit","raccoon","rat","rattlesnake","raven",
    "reindeer","rhinoceros","robin","rooster","salamander","salmon","sandpiper","sardine","scorpion","seahorse",
    "seal","shark","sheep","shrew","shrimp","skunk","sloth","snail","snake","sparrow",
    "spider","squid","squirrel","starfish","stork","swallow","swan","tapir","tarantula","termite",
    "tiger","toad","tortoise","toucan","trout","turkey","turtle","viper","vole","vulture",
    "wallaby","walrus","wasp","weasel","whale","wildcat","wolf","wolverine","wombat","woodpecker",
    "worm","wren","yak","zebra","axolotl","cassowary","capuchin","markhor","dhole"
]

cities = [
    "amsterdam","athens","auckland","baghdad","bangalore","bangkok","barcelona","beijing","beirut","belgrade",
    "berlin","bern","bhopal","birmingham","bogota","boston","bratislava","bristol","brussels","bucharest",
    "budapest","buenos aires","cairo","calgary","canberra","cape town","caracas","casablanca","chandigarh","chennai",
    "chiang mai","chicago","cincinnati","cologne","colombo","copenhagen","dakar","dallas","damascus","dar es salaam",
    "delhi","denver","dhaka","doha","dubai","dublin","durban","edmonton","florence","frankfurt",
    "fukuoka","geneva","genoa","glasgow","goa","guadalajara","guangzhou","guatemala city","hamburg","hanoi",
    "harare","helsinki","hiroshima","ho chi minh city","hong kong","honolulu","houston","hyderabad","indore","istanbul",
    "jakarta","jaipur","jeddah","jerusalem","johannesburg","kabul","kampala","kanpur","kathmandu","karachi",
    "kiev","kingston","kinshasa","kolkata","kuala lumpur","kuwait city","kyoto","lagos","lahore","lausanne",
    "leeds","leipzig","lima","lisbon","liverpool","ljubljana","london","los angeles","luxembourg","lyon",
    "macao","madrid","manchester","manila","maputo","marseille","medellin","melbourne","mexico city","miami",
    "milan","minneapolis","minsk","mombasa","monaco","monrovia","montevideo","montreal","moscow","munich",
    "nairobi","nanjing","naples","nashville","new delhi","new orleans","new york","nice","nicosia","osaka",
    "oslo","ottawa","panama city","paris","perth","philadelphia","phoenix","phnom penh","podgorica","port elizabeth",
    "port louis","port moresby","port of spain","porto","portland","prague","pretoria","punjab","quito","rajkot",
    "reykjavik","riga","rio de janeiro","riyadh","rome","rotterdam","salvador","san antonio","san diego","san francisco",
    "san juan","san jose","san salvador","santiago","santo domingo","sao paulo","sarajevo","seattle","seoul","seville",
    "shanghai","shenzhen","singapore","sofia","stockholm","stuttgart","surat","sydney","taipei","tallinn",
    "tashkent","tbilisi","tehran","tel aviv","the hague","thimphu","tokyo","toronto","tunis","ulaanbaatar",
    "vadodara","valencia","vancouver","venice","vienna","vilnius","warsaw","washington","wellington","windhoek",
    "wroclaw","xian","yangon","yerevan","zagreb","zanzibar city","zaragoza","zhengzhou","zibo","zurich"
]

countries = [
    "afghanistan","albania","algeria","andorra","angola","antigua_and_barbuda","argentina","armenia","australia","austria",
    "azerbaijan","bahamas","bahrain","bangladesh","barbados","belarus","belgium","belize","benin","bhutan",
    "bolivia","bosnia_and_herzegovina","botswana","brazil","brunei","bulgaria","burkina faso","burundi","cambodia","cameroon",
    "canada","cape_verde","central_african_republic","chad","chile","china","colombia","comoros","congo","costa rica",
    "croatia","cuba","cyprus","czechia","denmark","djibouti","dominica","dominican_republic","ecuador","egypt",
    "el_salvador","equatorial_guinea","eritrea","estonia","eswatini","ethiopia","fiji","finland","france","gabon",
    "gambia","georgia","germany","ghana","greece","grenada","guatemala","guinea","guinea_bissau","guyana",
    "haiti","honduras","hungary","iceland","india","indonesia","iran","iraq","ireland","israel",
    "italy","ivory_coast","jamaica","japan","jordan","kazakhstan","kenya","kiribati","kosovo","kuwait",
    "kyrgyzstan","laos","latvia","lebanon","lesotho","liberia","libya","liechtenstein","lithuania","luxembourg",
    "madagascar","malawi","malaysia","maldives","mali","malta","marshall_islands","mauritania","mauritius","mexico",
    "micronesia","moldova","monaco","mongolia","montenegro","morocco","mozambique","myanmar","namibia","nauru",
    "nepal","netherlands","new zealand","nicaragua","niger","nigeria","north_korea","north_macedonia","norway","oman",
    "pakistan","palau","panama","papua new guinea","paraguay","peru","philippines","poland","portugal","qatar",
    "romania","russia","rwanda","saint kitts and nevis","saint_lucia","saint_vincent_and_the_grenadines","samoa","san marino","sao tome and principe","saudi arabia",
    "senegal","serbia","seychelles","sierra_leone","singapore","slovakia","slovenia","solomon_islands","somalia","south_africa",
    "south_korea","south_sudan","spain","sri_lanka","sudan","suriname","sweden","switzerland","syria","taiwan",
    "tajikistan","tanzania","thailand","timor leste","togo","tonga","trinidad_and_tobago","tunisia","turkey","turkmenistan",
    "tuvalu","uganda","ukraine","united arab emirates","united kingdom","united states","uruguay","uzbekistan","vanuatu","vatican city",
    "venezuela","vietnam","yemen","zambia","zimbabwe"
]

birds = [
    "albatross","amazon_parrot","anhinga","auk","avocet","baboon_bird","bald_eagle","barn_owl","barn_swallow","barred_owl",
    "bee_eater","bellbird","bittern","black_grouse","black_vulture","blackbird","blue_jay","blue_tit","booby","brambling",
    "brant_goose","brolga","brown_pelican","budgerigar","buffalo_weaver","bullfinch","bunting","bustard","buzzard","canary",
    "capercaillie","cardinal","carolina_wren","cassowary","catbird","chaffinch","chicken","chiffchaff","chough","coal_tit",
    "cockatoo","cockatiel","cormorant","coucal","courser","crane","crested_pigeon","crossbill","crow","cuckoo",
    "curlew","dark_eyed_junco","darter","dove","dowitcher","duck","dunlin","eagle","egret","emu",
    "falcon","fieldfare","finch","flamingo","flycatcher","frigatebird","fulmar","gannet","garden_warbler","garganey",
    "gila_woodpecker","glossy_ibis","goldcrest","golden_eagle","goldfinch","goose","goshawk","grackle","grasshopper_warbler","great_auk",
    "great_bustard","great_crested_grebe","great_egret","great_horned_owl","great_tit","grebe","green_heron","greenfinch","grosbeak","grouse",
    "guillemot","gull","guineafowl","harrier","hawk","heron","hoatzin","hoopoe","hornbill","house_martin",
    "house_sparrow","hummingbird","ibis","indigo_bunting","jackdaw","jacana","jay","junco","kestrel","kingbird",
    "kingfisher","kite","kiwi","kittiwake","kookaburra","lapwing","lark","linnet","little_egret","lorikeet",
    "lyrebird","macaw","magpie","mallard","marabou_stork","martin","meadowlark","merganser","mockingbird","moorhen",
    "motmot","myna","night_heron","nightingale","nighthawk","nuthatch","oriole","osprey","ostrich","owl",
    "oystercatcher","parakeet","parrot","partridge","peacock","pelican","penguin","petrel","pheasant","pigeon",
    "pintail","plover","pochard","ptarmigan","puffbird","puffin","quail","quetzal","rail","raven",
    "red_kite","red_winged_blackbird","redpoll","reed_warbler","roadrunner","robin","rock_dove","roller","rook","rosella",
    "ruff","sandgrouse","sandpiper","sapsucker","scarlet_macaw","scaup","scoter","secretary_bird","serin","shag",
    "shearwater","shrike","siskin","skimmer","skua","snipe","snow_bunting","snow_goose","snowy_owl","sparrow",
    "sparrowhawk","spoonbill","starling","stilt","stint","stork","stonechat","storm_petrel","sunbird","swallow",
    "swift","tanager","teal","tern","thrasher","thrush","titmouse","toucan","treecreeper","trumpeter_swan",
    "turaco","turkey","turnstone","vireo","vulture","wagtail","warbler","waxwing","weaver","whimbrel",
    "whip_poor_will","whistling_duck","whitethroat","wigeon","wild_turkey","willet","wood_duck","woodcock","woodpecker","wren",
    "yellow_warbler","yellowhammer","yellowthroat","zebra_finch","zenaida_dove","zonetail_hawk","lapland_bunting","saddleback","spoon_billed_sandpiper","bearded_reedling"
]


