#ifndef	_ASN_PY_MODULE_H_
#define	_ASN_PY_MODULE_H_


#include <py_application.h>

/* Includes */
#include <EMBEDDED-PDV_Py.h>
#include <TimeOfDay_Py.h>
#include <Identifier_Py.h>
#include <Integer8_Py.h>
#include <Integer16_Py.h>
#include <Integer32_Py.h>
#include <Unsigned8_Py.h>
#include <Unsigned16_Py.h>
#include <Unsigned32_Py.h>
#include <ObjectName_Py.h>
#include <ObjectClass_Py.h>
#include <MMSString_Py.h>
#include <MMS255String_Py.h>
#include <FileName_Py.h>
#include <MMSpdu_Py.h>
#include <Confirmed-RequestPDU_Py.h>
#include <Confirmed-ErrorPDU_Py.h>
#include <ConfirmedServiceRequest_Py.h>
#include <AdditionalService-Request_Py.h>
#include <Request-Detail_Py.h>
#include <Unconfirmed-PDU_Py.h>
#include <UnconfirmedService_Py.h>
#include <Unconfirmed-Detail_Py.h>
#include <Confirmed-ResponsePDU_Py.h>
#include <ConfirmedServiceResponse_Py.h>
#include <AdditionalService-Response_Py.h>
#include <Response-Detail_Py.h>
#include <ServiceError_Py.h>
#include <AdditionalService-Error_Py.h>
#include <Initiate-RequestPDU_Py.h>
#include <Initiate-ResponsePDU_Py.h>
#include <Initiate-ErrorPDU_Py.h>
#include <Conclude-RequestPDU_Py.h>
#include <Conclude-ResponsePDU_Py.h>
#include <Conclude-ErrorPDU_Py.h>
#include <Cancel-RequestPDU_Py.h>
#include <Cancel-ResponsePDU_Py.h>
#include <Cancel-ErrorPDU_Py.h>
#include <RejectPDU_Py.h>
#include <DefineAccessControlList-Request_Py.h>
#include <DefineAccessControlList-Response_Py.h>
#include <GetAccessControlListAttributes-Request_Py.h>
#include <GetAccessControlListAttributes-Response_Py.h>
#include <ReportAccessControlledObjects-Request_Py.h>
#include <ReportAccessControlledObjects-Response_Py.h>
#include <DeleteAccessControlList-Request_Py.h>
#include <DeleteAccessControlList-Response_Py.h>
#include <ChangeAccessControl-Request_Py.h>
#include <ChangeAccessControl-Response_Py.h>
#include <ChangeAccessControl-Error_Py.h>
#include <StatusResponse_Py.h>
#include <CS-Status-Response_Py.h>
#include <OperationState_Py.h>
#include <ExtendedStatus_Py.h>
#include <Status-Request_Py.h>
#include <Status-Response_Py.h>
#include <UnsolicitedStatus_Py.h>
#include <GetNameList-Request_Py.h>
#include <GetNameList-Response_Py.h>
#include <Identify-Request_Py.h>
#include <Identify-Response_Py.h>
#include <Rename-Request_Py.h>
#include <Rename-Response_Py.h>
#include <GetCapabilityList-Request_Py.h>
#include <GetCapabilityList-Response_Py.h>
#include <VMDStop-Request_Py.h>
#include <VMDStop-Response_Py.h>
#include <VMDReset-Request_Py.h>
#include <VMDReset-Response_Py.h>
#include <InitiateDownloadSequence-Request_Py.h>
#include <InitiateDownloadSequence-Response_Py.h>
#include <DownloadSegment-Request_Py.h>
#include <DownloadSegment-Response_Py.h>
#include <LoadData_Py.h>
#include <TerminateDownloadSequence-Request_Py.h>
#include <TerminateDownloadSequence-Response_Py.h>
#include <InitiateUploadSequence-Request_Py.h>
#include <InitiateUploadSequence-Response_Py.h>
#include <UploadSegment-Request_Py.h>
#include <UploadSegment-Response_Py.h>
#include <TerminateUploadSequence-Request_Py.h>
#include <TerminateUploadSequence-Response_Py.h>
#include <RequestDomainDownload-Request_Py.h>
#include <RequestDomainDownload-Response_Py.h>
#include <RequestDomainUpload-Request_Py.h>
#include <RequestDomainUpload-Response_Py.h>
#include <LoadDomainContent-Request_Py.h>
#include <LoadDomainContent-Response_Py.h>
#include <StoreDomainContent-Request_Py.h>
#include <StoreDomainContent-Response_Py.h>
#include <DeleteDomain-Request_Py.h>
#include <DeleteDomain-Response_Py.h>
#include <GetDomainAttributes-Request_Py.h>
#include <GetDomainAttributes-Response_Py.h>
#include <CreateProgramInvocation-Request_Py.h>
#include <CreateProgramInvocation-Response_Py.h>
#include <CS-CreateProgramInvocation-Request_Py.h>
#include <DeleteProgramInvocation-Request_Py.h>
#include <DeleteProgramInvocation-Response_Py.h>
#include <Start-Request_Py.h>
#include <Start-Response_Py.h>
#include <Start-Error_Py.h>
#include <CS-Start-Request_Py.h>
#include <StartCount_Py.h>
#include <Stop-Request_Py.h>
#include <Stop-Response_Py.h>
#include <Stop-Error_Py.h>
#include <Resume-Request_Py.h>
#include <Resume-Response_Py.h>
#include <Resume-Error_Py.h>
#include <CS-Resume-Request_Py.h>
#include <Reset-Request_Py.h>
#include <Reset-Response_Py.h>
#include <Reset-Error_Py.h>
#include <Kill-Request_Py.h>
#include <Kill-Response_Py.h>
#include <GetProgramInvocationAttributes-Request_Py.h>
#include <GetProgramInvocationAttributes-Response_Py.h>
#include <CS-GetProgramInvocationAttributes-Response_Py.h>
#include <Select-Request_Py.h>
#include <Select-Response_Py.h>
#include <AlterProgramInvocationAttributes-Request_Py.h>
#include <AlterProgramInvocationAttributes-Response_Py.h>
#include <ControlElement_Py.h>
#include <InitiateUnitControlLoad-Request_Py.h>
#include <InitiateUnitControlLoad-Response_Py.h>
#include <InitiateUnitControl-Error_Py.h>
#include <UnitControlLoadSegment-Request_Py.h>
#include <UnitControlLoadSegment-Response_Py.h>
#include <UnitControlUpload-Request_Py.h>
#include <UnitControlUpload-Response_Py.h>
#include <StartUnitControl-Request_Py.h>
#include <StartUnitControl-Response_Py.h>
#include <StartUnitControl-Error_Py.h>
#include <StopUnitControl-Request_Py.h>
#include <StopUnitControl-Response_Py.h>
#include <StopUnitControl-Error_Py.h>
#include <CreateUnitControl-Request_Py.h>
#include <CreateUnitControl-Response_Py.h>
#include <AddToUnitControl-Request_Py.h>
#include <AddToUnitControl-Response_Py.h>
#include <RemoveFromUnitControl-Request_Py.h>
#include <RemoveFromUnitControl-Response_Py.h>
#include <GetUnitControlAttributes-Request_Py.h>
#include <GetUnitControlAttributes-Response_Py.h>
#include <LoadUnitControlFromFile-Request_Py.h>
#include <LoadUnitControlFromFile-Response_Py.h>
#include <LoadUnitControlFromFile-Error_Py.h>
#include <StoreUnitControlToFile-Request_Py.h>
#include <StoreUnitControlToFile-Response_Py.h>
#include <DeleteUnitControl-Request_Py.h>
#include <DeleteUnitControl-Response_Py.h>
#include <DeleteUnitControl-Error_Py.h>
#include <TypeSpecification_Py.h>
#include <AlternateAccess_Py.h>
#include <AlternateAccessSelection_Py.h>
#include <AccessResult_Py.h>
#include <Data_Py.h>
#include <UtcTime_Py.h>
#include <FloatingPoint_Py.h>
#include <DataAccessError_Py.h>
#include <VariableAccessSpecification_Py.h>
#include <VariableSpecification_Py.h>
#include <Read-Request_Py.h>
#include <Read-Response_Py.h>
#include <Write-Response_Py.h>
#include <Write-Request_Py.h>
#include <InformationReport_Py.h>
#include <GetVariableAccessAttributes-Request_Py.h>
#include <GetVariableAccessAttributes-Response_Py.h>
#include <DefineNamedVariable-Request_Py.h>
#include <DefineNamedVariable-Response_Py.h>
#include <DeleteVariableAccess-Request_Py.h>
#include <DeleteVariableAccess-Response_Py.h>
#include <DeleteVariableAccess-Error_Py.h>
#include <DefineNamedVariableList-Request_Py.h>
#include <DefineNamedVariableList-Response_Py.h>
#include <GetNamedVariableListAttributes-Request_Py.h>
#include <GetNamedVariableListAttributes-Response_Py.h>
#include <DeleteNamedVariableList-Response_Py.h>
#include <DeleteNamedVariableList-Request_Py.h>
#include <DeleteNamedVariableList-Error_Py.h>
#include <DefineNamedType-Request_Py.h>
#include <DefineNamedType-Response_Py.h>
#include <GetNamedTypeAttributes-Request_Py.h>
#include <GetNamedTypeAttributes-Response_Py.h>
#include <DeleteNamedType-Request_Py.h>
#include <DeleteNamedType-Response_Py.h>
#include <DeleteNamedType-Error_Py.h>
#include <ExchangeData-Request_Py.h>
#include <ExchangeData-Response_Py.h>
#include <GetDataExchangeAttributes-Request_Py.h>
#include <GetDataExchangeAttributes-Response_Py.h>
#include <TakeControl-Request_Py.h>
#include <TakeControl-Response_Py.h>
#include <RelinquishControl-Request_Py.h>
#include <RelinquishControl-Response_Py.h>
#include <DefineSemaphore-Request_Py.h>
#include <DefineSemaphore-Response_Py.h>
#include <DeleteSemaphore-Request_Py.h>
#include <DeleteSemaphore-Response_Py.h>
#include <ReportSemaphoreStatus-Request_Py.h>
#include <ReportSemaphoreStatus-Response_Py.h>
#include <ReportPoolSemaphoreStatus-Request_Py.h>
#include <ReportPoolSemaphoreStatus-Response_Py.h>
#include <ReportSemaphoreEntryStatus-Request_Py.h>
#include <ReportSemaphoreEntryStatus-Response_Py.h>
#include <SemaphoreEntry_Py.h>
#include <AttachToSemaphore_Py.h>
#include <Input-Request_Py.h>
#include <Input-Response_Py.h>
#include <Output-Request_Py.h>
#include <Output-Response_Py.h>
#include <TriggerEvent-Request_Py.h>
#include <TriggerEvent-Response_Py.h>
#include <EventNotification_Py.h>
#include <CS-EventNotification_Py.h>
#include <AcknowledgeEventNotification-Request_Py.h>
#include <AcknowledgeEventNotification-Response_Py.h>
#include <GetAlarmSummary-Request_Py.h>
#include <GetAlarmSummary-Response_Py.h>
#include <AlarmSummary_Py.h>
#include <EN-Additional-Detail_Py.h>
#include <GetAlarmEnrollmentSummary-Request_Py.h>
#include <GetAlarmEnrollmentSummary-Response_Py.h>
#include <AlarmEnrollmentSummary_Py.h>
#include <AttachToEventCondition_Py.h>
#include <DefineEventCondition-Request_Py.h>
#include <DefineEventCondition-Response_Py.h>
#include <CS-DefineEventCondition-Request_Py.h>
#include <DeleteEventCondition-Request_Py.h>
#include <DeleteEventCondition-Response_Py.h>
#include <GetEventConditionAttributes-Request_Py.h>
#include <GetEventConditionAttributes-Response_Py.h>
#include <CS-GetEventConditionAttributes-Response_Py.h>
#include <ReportEventConditionStatus-Request_Py.h>
#include <ReportEventConditionStatus-Response_Py.h>
#include <AlterEventConditionMonitoring-Request_Py.h>
#include <AlterEventConditionMonitoring-Response_Py.h>
#include <CS-AlterEventConditionMonitoring-Request_Py.h>
#include <DefineEventAction-Request_Py.h>
#include <DefineEventAction-Response_Py.h>
#include <DeleteEventAction-Request_Py.h>
#include <DeleteEventAction-Response_Py.h>
#include <GetEventActionAttributes-Request_Py.h>
#include <GetEventActionAttributes-Response_Py.h>
#include <ReportEventActionStatus-Request_Py.h>
#include <ReportEventActionStatus-Response_Py.h>
#include <DefineEventEnrollment-Request_Py.h>
#include <DefineEventEnrollment-Response_Py.h>
#include <DefineEventEnrollment-Error_Py.h>
#include <CS-DefineEventEnrollment-Request_Py.h>
#include <DeleteEventEnrollment-Request_Py.h>
#include <DeleteEventEnrollment-Response_Py.h>
#include <GetEventEnrollmentAttributes-Request_Py.h>
#include <GetEventEnrollmentAttributes-Response_Py.h>
#include <EEAttributes_Py.h>
#include <ReportEventEnrollmentStatus-Request_Py.h>
#include <ReportEventEnrollmentStatus-Response_Py.h>
#include <AlterEventEnrollment-Request_Py.h>
#include <AlterEventEnrollment-Response_Py.h>
#include <CS-AlterEventEnrollment-Request_Py.h>
#include <EE-State_Py.h>
#include <DefineEventConditionList-Request_Py.h>
#include <DefineEventConditionList-Response_Py.h>
#include <DefineEventConditionList-Error_Py.h>
#include <DeleteEventConditionList-Request_Py.h>
#include <DeleteEventConditionList-Response_Py.h>
#include <AddEventConditionListReference-Request_Py.h>
#include <AddEventConditionListReference-Response_Py.h>
#include <AddEventConditionListReference-Error_Py.h>
#include <RemoveEventConditionListReference-Request_Py.h>
#include <RemoveEventConditionListReference-Response_Py.h>
#include <RemoveEventConditionListReference-Error_Py.h>
#include <GetEventConditionListAttributes-Request_Py.h>
#include <GetEventConditionListAttributes-Response_Py.h>
#include <ReportEventConditionListStatus-Request_Py.h>
#include <ReportEventConditionListStatus-Response_Py.h>
#include <EventConditionStatus_Py.h>
#include <AlterEventConditionListMonitoring-Request_Py.h>
#include <AlterEventConditionListMonitoring-Response_Py.h>
#include <ReadJournal-Request_Py.h>
#include <ReadJournal-Response_Py.h>
#include <JournalEntry_Py.h>
#include <WriteJournal-Request_Py.h>
#include <WriteJournal-Response_Py.h>
#include <InitializeJournal-Request_Py.h>
#include <InitializeJournal-Response_Py.h>
#include <ReportJournalStatus-Request_Py.h>
#include <ReportJournalStatus-Response_Py.h>
#include <CreateJournal-Request_Py.h>
#include <CreateJournal-Response_Py.h>
#include <DeleteJournal-Request_Py.h>
#include <DeleteJournal-Response_Py.h>
#include <EntryContent_Py.h>
#include <ApplicationReference_Py.h>
#include <ObtainFile-Request_Py.h>
#include <ObtainFile-Response_Py.h>
#include <ObtainFile-Error_Py.h>
#include <FileOpen-Request_Py.h>
#include <FileOpen-Response_Py.h>
#include <FileRead-Request_Py.h>
#include <FileRead-Response_Py.h>
#include <FileRename-Request_Py.h>
#include <FileRename-Response_Py.h>
#include <FileRename-Error_Py.h>
#include <FileDelete-Request_Py.h>
#include <FileDelete-Response_Py.h>
#include <FileClose-Request_Py.h>
#include <FileClose-Response_Py.h>
#include <FileDirectory-Request_Py.h>
#include <FileDirectory-Response_Py.h>
#include <DirectoryEntry_Py.h>
#include <FileAttributes_Py.h>
#include <ScatteredAccessDescription_Py.h>
#include <DefineScatteredAccess-Request_Py.h>
#include <DefineScatteredAccess-Response_Py.h>
#include <GetScatteredAccessAttributes-Request_Py.h>
#include <GetScatteredAccessAttributes-Response_Py.h>
#include <Modifier_Py.h>
#include <ModifierStep_Py.h>
#include <ServiceSupportOptions_Py.h>
#include <ParameterSupportOptions_Py.h>
#include <AdditionalSupportOptions_Py.h>
#include <AdditionalCBBOptions_Py.h>
#include <AccessCondition_Py.h>
#include <DomainState_Py.h>
#include <ProgramInvocationState_Py.h>
#include <TypeDescription_Py.h>
#include <Address_Py.h>
#include <Priority_Py.h>
#include <Severity_Py.h>
#include <EventTime_Py.h>
#include <EC-State_Py.h>
#include <AlarmAckRule_Py.h>
#include <Transitions_Py.h>
#include <EC-Class_Py.h>
#include <EE-Class_Py.h>
#include <EE-Duration_Py.h>
#include <Journal-Variable_Py.h>
#include <Name_Py.h>
#include <DomainName_Py.h>
#include <RDNSequence_Py.h>
#include <RelativeDistinguishedName_Py.h>
#include <AttributeTypeAndValue_Py.h>
#include <ACSE-apdu_Py.h>
#include <AARQ-apdu_Py.h>
#include <AARE-apdu_Py.h>
#include <RLRQ-apdu_Py.h>
#include <RLRE-apdu_Py.h>
#include <ABRT-apdu_Py.h>
#include <ABRT-diagnostic_Py.h>
#include <ABRT-source_Py.h>
#include <ACSE-requirements_Py.h>
#include <Application-context-name-list_Py.h>
#include <Application-context-name_Py.h>
#include <AP-title_Py.h>
#include <AE-qualifier_Py.h>
#include <AP-title-form1_Py.h>
#include <AE-qualifier-form1_Py.h>
#include <AP-title-form2_Py.h>
#include <AE-qualifier-form2_Py.h>
#include <AE-title_Py.h>
#include <AE-title-form1_Py.h>
#include <AE-title-form2_Py.h>
#include <AE-invocation-identifier_Py.h>
#include <AP-invocation-identifier_Py.h>
#include <Associate-result_Py.h>
#include <Associate-source-diagnostic_Py.h>
#include <Association-information_Py.h>
#include <Authentication-value_Py.h>
#include <Implementation-data_Py.h>
#include <Mechanism-name_Py.h>
#include <Release-request-reason_Py.h>
#include <Release-response-reason_Py.h>
#include <EXTERNAL_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Module Type */
extern PyModuleDef PyAsnModule__mms;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_PY_MODULE_H_ */
