from .layout import MARGIN_MEDIUM as MARGIN_MEDIUM, QVBox as QVBox
from .lineedit import QLineEdit as QLineEdit
from .qt import QDoubleValidator as QDoubleValidator, QIntValidator as QIntValidator, QWidget as QWidget
from .qute import QuteDialog as QuteDialog
from _typeshed import Incomplete

class BaseInputDialog(QuteDialog):
    edit: Incomplete
    def __init__(self, parent=None, text: str | None = None, validator=None) -> None: ...
    def accept(self) -> None: ...
    def exec(self): ...
    def exec_(self): ...

class QInputDialog:
    @classmethod
    def getText(cls, parent: QWidget | None, title: str | None, text: str | None = None, validator=None) -> tuple[str, bool]: ...
    @classmethod
    def getInt(cls, parent: QWidget | None, title: str | None, value: int | None = None, min_: int = -2147483648, max_: int = 2147483647) -> tuple[int, bool]: ...
    @classmethod
    def getDouble(cls, parent: QWidget | None, title: str | None, value: float | None = None, min_: float = -1e+100, max_: float = 1e+100, decimals: int = 2) -> tuple[float, bool]: ...
