"""Constants used as identifiers in timeseries widget specs."""

X_AXIS_BANDS_DEPENDENCY = "__TIMESERIES_X_AXIS_BANDS_DEPENDENCY__"
X_AXIS_LINES_DEPENDENCY = "__TIMESERIES_X_AXIS_LINES_DEPENDENCY__"

Y_LEFT_AXIS_BANDS_DEPENDENCY = "__TIMESERIES_Y_LEFT_AXIS_BANDS_DEPENDENCY__"
Y_RIGHT_AXIS_BANDS_DEPENDENCY = "__TIMESERIES_Y_RIGHT_AXIS_BANDS_DEPENDENCY__"

Y_LEFT_AXIS_LINES_DEPENDENCY = "__TIMESERIES_Y_LEFT_AXIS_LINES_DEPENDENCY__"
Y_RIGHT_AXIS_LINES_DEPENDENCY = "__TIMESERIES_Y_RIGHT_AXIS_LINES_DEPENDENCY__"
