"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .address_change_request_metadata_view import (
    AddressChangeRequestMetadataView,
    AddressChangeRequestMetadataViewTypedDict,
)
from .amount_view import AmountView, AmountViewTypedDict
from .authorization_verification_status import AuthorizationVerificationStatus
from .capture_view import CaptureView, CaptureViewTypedDict
from .chargeback_details import ChargebackDetails, ChargebackDetailsTypedDict
from .consumer_self_view import ConsumerSelfView, ConsumerSelfViewTypedDict
from .consumer_user_membership import (
    ConsumerUserMembership,
    ConsumerUserMembershipTypedDict,
)
from .credit import Credit, CreditTypedDict
from .credit_card_authorization_view import (
    CreditCardAuthorizationView,
    CreditCardAuthorizationViewTypedDict,
)
from .credit_card_user import CreditCardUser, CreditCardUserTypedDict
from .credit_card_view import CreditCardView, CreditCardViewTypedDict
from .credit_card_void_view import CreditCardVoidView, CreditCardVoidViewTypedDict
from .custom_fields import CustomFields, CustomFieldsTypedDict
from .customer_list_status import CustomerListStatus, CustomerListStatusTypedDict
from .manual_disputes import ManualDisputes, ManualDisputesTypedDict
from .merchant import Merchant, MerchantTypedDict
from .merchant_division import MerchantDivision, MerchantDivisionTypedDict
from .order_decision import OrderDecision, OrderDecisionTypedDict
from .order_view import OrderView, OrderViewTypedDict
from .review_ticket import ReviewTicket, ReviewTicketTypedDict
from .risk_insights_yml import RiskInsightsYml, RiskInsightsYmlTypedDict
from .risk_review_status import RiskReviewStatus
from .splits_view import SplitsView, SplitsViewTypedDict
from .transaction_indemnification_decision import TransactionIndemnificationDecision
from .transaction_indemnification_reason import TransactionIndemnificationReason
from .transaction_processor import TransactionProcessor
from .transaction_rejection_details_view import (
    TransactionRejectionDetailsView,
    TransactionRejectionDetailsViewTypedDict,
)
from .transaction_status import TransactionStatus
from .transaction_timeline_view import (
    TransactionTimelineView,
    TransactionTimelineViewTypedDict,
)
from .transaction_type import TransactionType
from .transaction_view import TransactionView, TransactionViewTypedDict
from bolt_api_sdk.types import BaseModel
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TransactionDetailsTypedDict(TypedDict):
    r"""Transaction Details Retrieved"""

    address_change_request_metadata: NotRequired[
        AddressChangeRequestMetadataViewTypedDict
    ]
    adjust_transactions: NotRequired[List[TransactionViewTypedDict]]
    r"""**Nullable** for Transactions Details.

    """
    amount: NotRequired[AmountViewTypedDict]
    auth_verification_status: NotRequired[AuthorizationVerificationStatus]
    r"""Used to track the status of micro-authorizations. **Nullable** for Transactions Details."""
    authorization: NotRequired[CreditCardAuthorizationViewTypedDict]
    authorization_id: NotRequired[str]
    r"""The authorization's id."""
    capture: NotRequired[CaptureViewTypedDict]
    r"""Deprecated. Use `captures`."""
    captures: NotRequired[List[CaptureViewTypedDict]]
    r"""All captures associated with the transaction. **Nullable** for Transactions Details."""
    chargeback_details: NotRequired[ChargebackDetailsTypedDict]
    credit: NotRequired[CreditTypedDict]
    custom_fields: NotRequired[CustomFieldsTypedDict]
    customer_list_status: NotRequired[CustomerListStatusTypedDict]
    date_: NotRequired[int]
    r"""Transaction date. **Nullable** for Transactions Details."""
    from_consumer: NotRequired[CreditCardUserTypedDict]
    r"""The credit card user."""
    from_consumer_membership_users: NotRequired[ConsumerUserMembershipTypedDict]
    r"""**Nullable** for Transactions Details.

    """
    from_credit_card: NotRequired[CreditCardViewTypedDict]
    r"""Contains details about the credit card transaction."""
    id: NotRequired[str]
    r"""The unique ID associated with the transaction. **Nullable** for Transactions Details."""
    indemnification_decision: NotRequired[TransactionIndemnificationDecision]
    r"""Describes whether the transaction is indemnified by Bolt for fraud.

    """
    indemnification_reason: NotRequired[TransactionIndemnificationReason]
    r"""Describes the reason that the transaction is or is not indemnified by Bolt for fraud.

    """
    last_viewed_utc: NotRequired[int]
    r"""The last view time as UTC."""
    last4: NotRequired[str]
    r"""The card's last 4 digits. **Nullable** for Transactions Details."""
    manual_disputes: NotRequired[ManualDisputesTypedDict]
    merchant: NotRequired[MerchantTypedDict]
    merchant_division: NotRequired[MerchantDivisionTypedDict]
    merchant_order_number: NotRequired[str]
    r"""The merchant's internal order number for this transaction."""
    order: NotRequired[OrderViewTypedDict]
    order_decision: NotRequired[OrderDecisionTypedDict]
    r"""Decision and score for an order."""
    platform_metadata: NotRequired[Dict[str, str]]
    processor: NotRequired[TransactionProcessor]
    r"""The processor used. **Nullable** for Transactions Details."""
    reference: NotRequired[str]
    r"""The transaction's 12-digit Bolt reference ID. **Nullable** for Transactions Details."""
    refund_transaction_ids: NotRequired[List[str]]
    r"""**Nullable** for Transactions Details.

    """
    refund_transactions: NotRequired[List[TransactionViewTypedDict]]
    r"""**Nullable** for Transactions Details.

    """
    refunded_amount: NotRequired[AmountViewTypedDict]
    review_ticket: NotRequired[ReviewTicketTypedDict]
    r"""Internal use only."""
    risk_insights: NotRequired[RiskInsightsYmlTypedDict]
    r"""Displays fraud decisioning insights based on key factors. This information can either be forwarded via a `risk_insights` transaction webhook type or be polled by sending a `GET` request to Bolt's [transactions endpoint](/api-bolt/#operation/transaction-details).

    """
    risk_review_status: NotRequired[RiskReviewStatus]
    r"""Describes the current Risk Review status. A transaction could be unreviewed, reviewed, or pending manual review by the Bolt team."""
    risk_score: NotRequired[int]
    source_transaction: NotRequired[TransactionViewTypedDict]
    splits: NotRequired[List[SplitsViewTypedDict]]
    r"""A list of splits. **Nullable** for Transactions Details."""
    status: NotRequired[TransactionStatus]
    r"""The transaction's status."""
    timeline: NotRequired[TransactionTimelineViewTypedDict]
    to_consumer: NotRequired[ConsumerSelfViewTypedDict]
    to_credit_card: NotRequired[CreditCardViewTypedDict]
    r"""Contains details about the credit card transaction."""
    transaction_properties: NotRequired[Dict[str, str]]
    transaction_rejection_details: NotRequired[TransactionRejectionDetailsViewTypedDict]
    type: NotRequired[TransactionType]
    r"""The type of transaction."""
    view_status: NotRequired[str]
    void: NotRequired[CreditCardVoidViewTypedDict]
    void_cause: NotRequired[str]


class TransactionDetails(BaseModel):
    r"""Transaction Details Retrieved"""

    address_change_request_metadata: Optional[AddressChangeRequestMetadataView] = None

    adjust_transactions: Optional[List[TransactionView]] = None
    r"""**Nullable** for Transactions Details.

    """

    amount: Optional[AmountView] = None

    auth_verification_status: Optional[AuthorizationVerificationStatus] = None
    r"""Used to track the status of micro-authorizations. **Nullable** for Transactions Details."""

    authorization: Optional[CreditCardAuthorizationView] = None

    authorization_id: Optional[str] = None
    r"""The authorization's id."""

    capture: Optional[CaptureView] = None
    r"""Deprecated. Use `captures`."""

    captures: Optional[List[CaptureView]] = None
    r"""All captures associated with the transaction. **Nullable** for Transactions Details."""

    chargeback_details: Optional[ChargebackDetails] = None

    credit: Optional[Credit] = None

    custom_fields: Optional[CustomFields] = None

    customer_list_status: Optional[CustomerListStatus] = None

    date_: Annotated[Optional[int], pydantic.Field(alias="date")] = None
    r"""Transaction date. **Nullable** for Transactions Details."""

    from_consumer: Optional[CreditCardUser] = None
    r"""The credit card user."""

    from_consumer_membership_users: Optional[ConsumerUserMembership] = None
    r"""**Nullable** for Transactions Details.

    """

    from_credit_card: Optional[CreditCardView] = None
    r"""Contains details about the credit card transaction."""

    id: Optional[str] = None
    r"""The unique ID associated with the transaction. **Nullable** for Transactions Details."""

    indemnification_decision: Optional[TransactionIndemnificationDecision] = None
    r"""Describes whether the transaction is indemnified by Bolt for fraud.

    """

    indemnification_reason: Optional[TransactionIndemnificationReason] = None
    r"""Describes the reason that the transaction is or is not indemnified by Bolt for fraud.

    """

    last_viewed_utc: Optional[int] = None
    r"""The last view time as UTC."""

    last4: Optional[str] = None
    r"""The card's last 4 digits. **Nullable** for Transactions Details."""

    manual_disputes: Optional[ManualDisputes] = None

    merchant: Optional[Merchant] = None

    merchant_division: Optional[MerchantDivision] = None

    merchant_order_number: Optional[str] = None
    r"""The merchant's internal order number for this transaction."""

    order: Optional[OrderView] = None

    order_decision: Optional[OrderDecision] = None
    r"""Decision and score for an order."""

    platform_metadata: Optional[Dict[str, str]] = None

    processor: Optional[TransactionProcessor] = None
    r"""The processor used. **Nullable** for Transactions Details."""

    reference: Optional[str] = None
    r"""The transaction's 12-digit Bolt reference ID. **Nullable** for Transactions Details."""

    refund_transaction_ids: Optional[List[str]] = None
    r"""**Nullable** for Transactions Details.

    """

    refund_transactions: Optional[List[TransactionView]] = None
    r"""**Nullable** for Transactions Details.

    """

    refunded_amount: Optional[AmountView] = None

    review_ticket: Optional[ReviewTicket] = None
    r"""Internal use only."""

    risk_insights: Optional[RiskInsightsYml] = None
    r"""Displays fraud decisioning insights based on key factors. This information can either be forwarded via a `risk_insights` transaction webhook type or be polled by sending a `GET` request to Bolt's [transactions endpoint](/api-bolt/#operation/transaction-details).

    """

    risk_review_status: Optional[RiskReviewStatus] = None
    r"""Describes the current Risk Review status. A transaction could be unreviewed, reviewed, or pending manual review by the Bolt team."""

    risk_score: Optional[int] = None

    source_transaction: Optional[TransactionView] = None

    splits: Optional[List[SplitsView]] = None
    r"""A list of splits. **Nullable** for Transactions Details."""

    status: Optional[TransactionStatus] = None
    r"""The transaction's status."""

    timeline: Optional[TransactionTimelineView] = None

    to_consumer: Optional[ConsumerSelfView] = None

    to_credit_card: Optional[CreditCardView] = None
    r"""Contains details about the credit card transaction."""

    transaction_properties: Optional[Dict[str, str]] = None

    transaction_rejection_details: Optional[TransactionRejectionDetailsView] = None

    type: Optional[TransactionType] = None
    r"""The type of transaction."""

    view_status: Optional[str] = None

    void: Optional[CreditCardVoidView] = None

    void_cause: Optional[str] = None
